import type { LibraryCardSeed, LibraryLearningSeed } from "./biochimie-s1.js";
import { single, multi } from "./qcm-helpers.js";

const RECTUM_COURSE = `# Le rectum et le canal anal

## 1. Généralités et situation
- Le gros intestin se divise en **cæcum, côlon, rectum et canal anal**.
- Le **rectum** est la portion distale du gros intestin, entre le côlon sigmoïde et le canal anal. Contrairement au reste du côlon, il est dépourvu des caractères cardinaux du gros intestin : pas de **tænias coli**, pas de **haustrations**, pas d'**appendices épiploïques**.
- Il est situé dans la partie postérieure du petit bassin, en avant des trois dernières pièces sacrées et du coccyx, en arrière de la vessie chez l'homme et de l'utérus chez la femme.
- Longueur : **12 cm**. Le calibre n'est pas uniforme : ~4 cm dans sa partie supérieure (comme le sigmoïde), avec une dilatation dans la partie basse appelée **ampoule rectale**. Vide, les parois antérieure et postérieure de l'ampoule sont au contact l'une de l'autre.

## 2. Trajet et courbures
- Le rectum commence en avant de S3, dans le prolongement du sigmoïde ; la limite (**jonction recto-sigmoïdienne**) est marquée par l'extrémité inférieure du méso-sigmoïde.
- Il devient le canal anal 2 à 3 cm en avant et un peu au-dessous de la pointe du coccyx (**jonction ano-rectale**, qui correspond chez l'homme à l'apex de la prostate).
- Trajet : tiers supérieur dirigé en bas et en arrière ; tiers moyen vertical ; tiers inférieur dirigé en bas et en avant.
- **Courbures antéro-postérieures** : courbure sacrée (concavité du sacrum/coccyx) et courbure périnéale (au niveau de la jonction ano-rectale, maintenue par la sangle du muscle pubo-rectal, faisceau du releveur de l'anus).
- **Courbures latérales** : supérieure convexe à droite (jonction S3-S4), moyenne convexe à gauche (la plus marquée, à la jonction sacro-coccygienne), inférieure convexe à droite (pointe du coccyx).

## 3. Rapports péritonéaux
- Tiers supérieur du rectum : recouvert de péritoine en avant et sur les côtés.
- Tiers moyen : recouvert de péritoine seulement en avant.
- Tiers inférieur (ampoule) : entièrement sous-péritonéal ; il se situe sous le niveau du cul-de-sac recto-vésical (homme) ou recto-utérin (femme).

## 4. Rapports antérieurs
- **Chez l'homme** : le tiers inférieur (sous-péritonéal) répond à la base de la vessie, aux uretères terminaux, aux vésicules séminales, aux ampoules déférentielles et à la prostate — toutes ces structures étant séparées du rectum par le **fascia recto-vésical de Denonvilliers**. Le fascia recto-prostatique (Denonvilliers) est une cloison membraneuse au fond du cul-de-sac recto-vésical qui sépare prostate et vessie du rectum. Les deux tiers supérieurs (péritonéaux) répondent au cul-de-sac recto-vésical et aux anses grêles/sigmoïdiennes qu'il contient.
- **Chez la femme** : les deux tiers supérieurs répondent au cul-de-sac recto-utérin (de Douglas) ; le tiers inférieur répond au vagin, dont il est séparé par un fascia recto-vaginal mal défini.

## 5. Rapports postérieurs et latéraux
- Dans le plan médian : les trois dernières pièces sacrées, le coccyx, le raphé ano-coccygien, le **ganglion impar** (ganglion terminal impair de la chaîne sympathique, rétropéritonéal), l'artère sacrée médiane (branche de l'aorte) et l'**artère rectale supérieure** (branche de la mésentérique inférieure, en regard de S3 seulement). Le **fascia de Waldeyer** relie l'ampoule rectale au sacrum et au coccyx.
- De chaque côté : muscles piriforme, coccygien et releveur de l'anus (formé de trois faisceaux : pubo-coccygien, ilio-coccygien, pubo-rectal), chaînes sympathiques, rameaux antérieurs de S3-S4-S5 et du nerf coccygien, nerfs splanchniques pelviens (parasympathiques), artère sacrée latérale.
- Latéralement, la partie haute du rectum répond aux fossettes pararectales (dépressions péritonéales, extension latérale du cul-de-sac recto-vésical/recto-utérin) ; la partie basse est intimement entourée et soutenue par les releveurs de l'anus.

## 6. Configuration interne et vascularisation du rectum
- La muqueuse présente des plis **temporaires** (longitudinaux, disparaissant à la distension) et des plis **permanents** — les **valvules de Houston**, plis transversaux semi-lunaires (en général au nombre de trois), qui soutiennent les matières fécales et limitent la distension excessive de l'ampoule.
- **Artères** : artère rectale supérieure (prolongement de la mésentérique inférieure, vascularise toute la muqueuse jusqu'aux valvules anales et la musculature du haut rectum) ; artères rectales moyennes (×2, branches de la division antérieure de l'iliaque interne, ne vascularisent que les tuniques superficielles) ; artères rectales inférieures (×2, branches de la honteuse interne) ; artère sacrée médiane (paroi postérieure de la jonction ano-rectale).
- **Veines** : veine rectale supérieure → veine mésentérique inférieure → veine splénique (système porte) ; veines rectales moyennes → veine iliaque interne (système systémique) ; veines rectales inférieures → veine honteuse interne. Le rectum est ainsi un site d'**anastomose porto-cave**.
- **Lymphatiques** : moitié supérieure → nœuds mésentériques inférieurs (relais pararectaux) ; moitié inférieure → nœuds iliaques internes.
- **Innervation** : fibres sympathiques (L1-L2) et parasympathiques (S2-S3-S4).

## 7. Le canal anal
- Portion terminale du gros intestin (**3,8 cm**), situé dans le périnée sous le diaphragme pelvien, également dépourvu de haustrations/tænias/appendices épiploïques.
- Entouré d'un sphincter interne involontaire et d'un sphincter externe volontaire dont le tonus maintient le canal fermé sauf lors de la défécation.
- Situé dans le triangle anal du périnée, entre les fosses ischio-rectales (graisseuses) qui permettent l'expansion du canal lors de la défécation.
- Trajet : de la jonction ano-rectale (apex de la prostate) vers le bas et l'arrière, s'ouvrant à l'orifice anal dans le sillon interfessier, ~4 cm en avant et au-dessous de la pointe du coccyx.
- **Rapports** : en avant, le corps périnéal, le bulbe du pénis et l'urètre spongieux (homme) ou la partie basse du vagin (femme) ; en arrière, le raphé ano-coccygien et la pointe du coccyx ; latéralement, la fosse ischio-rectale.

## 8. Configuration interne du canal anal
- Il est divisé en parties haute et basse par la **ligne pectinée (dentée)**. La partie haute (jonction ano-rectale → ligne pectinée) dérive de l'intestin postérieur endodermique ; la partie basse (ligne pectinée → marge anale) dérive du proctodéum ectodermique — d'où des différences de développement, vascularisation, drainage lymphatique et innervation.
- Partie haute : **colonnes anales (de Morgagni)**, plis muqueux longitudinaux permanents contenant les radicelles de la veine rectale supérieure ; **valvules anales (de Morgagni)**, plis semi-lunaires reliant les extrémités basses des colonnes adjacentes, dont la ligne d'implantation dessine la ligne pectinée ; **sinus anaux**, récessus verticaux entre colonnes et au-dessus des valvules, recevant les canaux des glandes anales.
- Partie basse : région supérieure (**pecten**), de la ligne pectinée à la **ligne blanche de Hilton** (jonction entre sphincter externe sous-cutané et extrémité basse du sphincter interne), muqueuse bleutée du fait du plexus veineux sous-jacent ; région inférieure, revêtue de peau vraie avec glandes sudoripares/sébacées et pigmentation.

## 9. Sphincters anaux
- **Sphincter interne** : épaississement du muscle lisse circulaire involontaire, continu en haut avec la couche circulaire du rectum, s'arrêtant en bas au niveau de la ligne de Hilton. Innervation autonome (sympathique et parasympathique) — involontaire.
- **Sphincter externe** : muscle strié volontaire entourant toute la longueur du canal anal, en trois parties — profonde (se prolonge par le faisceau pubo-rectal formant une sangle autour de la jonction ano-rectale), superficielle (naît du coccyx/raphé ano-coccygien, s'insère sur le corps périnéal) et sous-cutanée (entoure la partie basse du canal). Innervation somatique (nerf rectal inférieur, branche périnéale de S4) — volontaire.
- Sensibilité muqueuse : moitié haute sensible à l'étirement (sympathique L1-L2, parasympathique S2-S4) ; moitié basse sensible à la douleur/température/toucher/pression (nerfs rectaux inférieurs).

## 10. Vascularisation du canal anal
- Artères : partie haute par l'artère rectale supérieure, partie basse par l'artère rectale inférieure.
- Veines : partie haute drainée par la veine rectale supérieure vers le système porte ; partie basse par les veines rectales inférieures vers le système cave.
- Les plexus veineux **interne** (sous-muqueux, au-dessus de la ligne de Hilton) et **externe** (entre peau périanale et sphincter externe sous-cutané) communiquent entre eux, formant l'**annulus hemorrhoidalis** — les hémorroïdes sont des dilatations variqueuses de ces plexus.
- Lymphatiques : partie haute → nœuds iliaques internes ; partie basse → nœuds inguinaux superficiels.

## Points à retenir
- Le rectum est dépourvu de tænias/haustrations/appendices épiploïques ; il présente 3 courbures antéro-postérieures/latérales et se termine par l'ampoule rectale, non péritonisée.
- Le fascia de Denonvilliers sépare le rectum de la prostate/vessie chez l'homme ; le cul-de-sac de Douglas sépare le rectum de l'utérus chez la femme.
- La ligne pectinée marque la transition embryologique (endoderme/ectoderme) du canal anal et la limite entre drainage porte/cave et innervation viscérale/somatique.
- Sphincter interne (lisse, involontaire) vs sphincter externe (strié, volontaire, 3 parties) ; les hémorroïdes résultent de la dilatation du plexus veineux anastomotique interne-externe.`;

export const RECTUM_LEARNING: LibraryLearningSeed = {
  resource: {
    resource_type: "course",
    titre_fr: "Cours condensé — Le rectum et le canal anal",
    source_label: "Anatomie — Lecture 10",
    content_fr: RECTUM_COURSE,
  },
  qcm: [
    single("Quels caractères cardinaux du gros intestin sont absents sur le rectum ?", "A", "Le rectum est dépourvu de tænias coli, de haustrations et d'appendices épiploïques, contrairement au reste du côlon.", ["Tænias coli, haustrations et appendices épiploïques", "Seulement les haustrations", "Seulement les tænias coli", "Aucun, le rectum possède tous ces caractères"]),
    single("Quelle est la longueur du rectum ?", "B", "Le rectum mesure environ 12 cm de long.", ["6 cm", "12 cm", "20 cm", "25 cm"]),
    single("Comment s'appelle la dilatation de la partie basse du rectum ?", "C", "La partie basse du rectum forme une dilatation appelée ampoule rectale.", ["Le sinus rectal", "La valvule de Houston", "L'ampoule rectale", "Le pecten"]),
    single("Quelle structure marque la jonction recto-sigmoïdienne ?", "A", "La jonction recto-sigmoïdienne est indiquée par l'extrémité inférieure du méso-sigmoïde.", ["L'extrémité inférieure du méso-sigmoïde", "La ligne pectinée", "Le fascia de Waldeyer", "Le ganglion impar"]),
    single("À quel niveau se situe la jonction ano-rectale chez l'homme ?", "B", "Chez l'homme, la jonction ano-rectale correspond à l'apex de la prostate.", ["Au niveau du col vésical", "À l'apex de la prostate", "Au niveau du promontoire sacré", "À la base de la vessie"]),
    multi("Quelles sont les courbures antéro-postérieures du rectum ?", ["A", "B"], "Les courbures antéro-postérieures sont la courbure sacrée (concavité du sacrum/coccyx) et la courbure périnéale (jonction ano-rectale, maintenue par la sangle pubo-rectale).", ["Courbure sacrée", "Courbure périnéale", "Courbure supérieure droite", "Courbure moyenne gauche"]),
    single("Quelle portion du rectum n'est pas du tout recouverte par le péritoine ?", "C", "Le tiers inférieur (ampoule rectale) est entièrement sous-péritonéal.", ["Le tiers supérieur", "Le tiers moyen", "Le tiers inférieur (ampoule)", "Le rectum est entièrement péritonisé"]),
    single("Quel fascia sépare le rectum de la prostate et de la vessie chez l'homme ?", "B", "Le fascia recto-vésical de Denonvilliers sépare le rectum de la prostate, des vésicules séminales et de la vessie.", ["Le fascia de Waldeyer", "Le fascia de Denonvilliers", "Le fascia de Toldt", "Le fascia de Zuckerkandl"]),
    single("Quel cul-de-sac péritonéal est en rapport avec les deux tiers supérieurs du rectum chez la femme ?", "A", "Chez la femme, les deux tiers supérieurs du rectum répondent au cul-de-sac recto-utérin (de Douglas).", ["Le cul-de-sac recto-utérin (de Douglas)", "Le cul-de-sac vésico-utérin", "Le cul-de-sac recto-vésical", "La fosse ovarienne"]),
    single("Quelle artère est la principale source de vascularisation du rectum ?", "C", "L'artère rectale supérieure, prolongement de l'artère mésentérique inférieure, est l'artère principale du rectum.", ["L'artère sacrée médiane", "L'artère rectale moyenne", "L'artère rectale supérieure", "L'artère honteuse interne"]),
    single("Dans quel système veineux se draine la veine rectale supérieure ?", "A", "La veine rectale supérieure draine dans la veine mésentérique inférieure puis la veine splénique, appartenant au système porte.", ["Le système porte, via la veine mésentérique inférieure", "Le système cave, via la veine iliaque interne", "Directement dans la veine cave inférieure", "Le système azygos"]),
    single("Que représentent les valvules de Houston ?", "B", "Les valvules de Houston sont des plis muqueux transverses semi-lunaires permanents, habituellement au nombre de trois, situés en regard des courbures latérales du rectum.", ["Des plis temporaires disparaissant à la distension", "Des plis muqueux transverses semi-lunaires permanents", "Les sphincters du canal anal", "Les colonnes anales de Morgagni"]),
    single("Quelle est la longueur du canal anal ?", "B", "Le canal anal mesure environ 3,8 cm de long.", ["1 cm", "3,8 cm", "8 cm", "12 cm"]),
    single("Quelle structure marque la limite entre les parties haute et basse du canal anal ?", "C", "La ligne pectinée (dentée) sépare la partie haute (origine endodermique) de la partie basse (origine ectodermique) du canal anal.", ["La ligne blanche de Hilton", "Le raphé ano-coccygien", "La ligne pectinée (dentée)", "Le fascia de Waldeyer"]),
    single("Quelle est l'origine embryologique de la partie haute du canal anal ?", "A", "La partie haute du canal anal, au-dessus de la ligne pectinée, dérive de l'intestin postérieur endodermique.", ["L'intestin postérieur endodermique", "Le proctodéum ectodermique", "Le mésoderme intermédiaire", "La crête neurale"]),
    single("Que sont les colonnes anales de Morgagni ?", "A", "Les colonnes de Morgagni sont des plis muqueux longitudinaux permanents contenant les radicelles de la veine rectale supérieure.", ["Des plis muqueux longitudinaux permanents contenant les radicelles de la veine rectale supérieure", "Les sphincters volontaires du canal anal", "Des glandes sécrétant du mucus lubrifiant", "Les valvules semi-lunaires reliant les colonnes"]),
    single("Quel type de muscle compose le sphincter anal interne ?", "B", "Le sphincter interne est formé de muscle lisse involontaire, épaississement de la couche circulaire du rectum.", ["Muscle strié volontaire", "Muscle lisse involontaire", "Muscle cardiaque", "Tissu conjonctif dense uniquement"]),
    single("Le sphincter anal externe est-il sous contrôle volontaire ou involontaire ?", "A", "Le sphincter externe est un muscle strié, sous contrôle volontaire, innervé par le nerf rectal inférieur (branche du nerf honteux).", ["Volontaire, muscle strié", "Involontaire, muscle lisse", "Mixte, moitié volontaire moitié involontaire", "Non innervé"]),
    single("Que forment les plexus veineux internes et externes du canal anal ?", "C", "Ces deux plexus communiquent entre eux et forment l'annulus hemorrhoidalis ; leur dilatation variqueuse constitue les hémorroïdes.", ["Le fascia de Waldeyer", "La ligne de Hilton", "L'annulus hemorrhoidalis, dont la dilatation cause les hémorroïdes", "Le pecten"]),
    single("Vers quels nœuds lymphatiques draine la partie basse du canal anal ?", "B", "La partie basse du canal anal (sous la ligne pectinée) draine vers les nœuds inguinaux superficiels.", ["Les nœuds iliaques internes", "Les nœuds inguinaux superficiels", "Les nœuds mésentériques inférieurs", "Les nœuds para-aortiques"]),
  ],
  exam: { titre_fr: "Examen chronométré — Le rectum et le canal anal", duration_seconds: 1_600 },
};

export const RECTUM_FLASHCARDS: LibraryCardSeed[] = [
  { question_fr: "Quelles sont les 4 subdivisions du gros intestin ?", question_en: "What are the 4 subdivisions of the large intestine?", answer_fr: "Le cæcum, le côlon, le rectum et le canal anal.", answer_en: "The cecum, colon, rectum, and anal canal." },
  { question_fr: "Quels sont les trois caractères cardinaux du gros intestin absents sur le rectum ?", question_en: "What are the three cardinal features of the large intestine absent from the rectum?", answer_fr: "Les tænias coli, les haustrations et les appendices épiploïques.", answer_en: "Taenia coli, sacculations (haustra), and appendices epiploicae." },
  { question_fr: "Quelle est la longueur du rectum ?", question_en: "What is the length of the rectum?", answer_fr: "12 cm.", answer_en: "12 cm." },
  { question_fr: "Comment appelle-t-on la dilatation basse du rectum ?", question_en: "What is the dilatation at the lower part of the rectum called?", answer_fr: "L'ampoule rectale.", answer_en: "The rectal ampulla." },
  { question_fr: "Quelle structure marque la jonction recto-sigmoïdienne ?", question_en: "What marks the rectosigmoid junction?", answer_fr: "L'extrémité inférieure du méso-sigmoïde.", answer_en: "The lower end of the sigmoid mesocolon." },
  { question_fr: "À quel niveau vertébral commence le rectum ?", question_en: "At what vertebral level does the rectum begin?", answer_fr: "En avant de S3.", answer_en: "In front of the S3 vertebra." },
  { question_fr: "Quelle structure correspond à la jonction ano-rectale chez l'homme ?", question_en: "What structure corresponds to the anorectal junction in the male?", answer_fr: "L'apex de la prostate.", answer_en: "The apex of the prostate." },
  { question_fr: "Nommez les deux courbures antéro-postérieures du rectum.", question_en: "Name the two anteroposterior curvatures of the rectum.", answer_fr: "La courbure sacrée et la courbure périnéale.", answer_en: "The sacral curvature and the perineal curvature." },
  { question_fr: "Qu'est-ce qui maintient la courbure périnéale du rectum ?", question_en: "What maintains the perineal curvature of the rectum?", answer_fr: "La sangle pubo-rectale, issue du muscle releveur de l'anus.", answer_en: "The puborectal sling, derived from the levator ani muscle." },
  { question_fr: "Combien de courbures latérales présente le rectum, et laquelle est la plus marquée ?", question_en: "How many lateral curvatures does the rectum have, and which is the most prominent?", answer_fr: "Trois ; la courbure latérale moyenne (convexe à gauche, à la jonction sacro-coccygienne) est la plus marquée.", answer_en: "Three; the middle lateral curvature (convex to the left, at the sacrococcygeal junction) is the most prominent." },
  { question_fr: "Quelle portion du rectum est recouverte de péritoine sur toute sa circonférence antérieure et latérale ?", question_en: "Which part of the rectum is covered by peritoneum on its entire anterior and lateral circumference?", answer_fr: "Le tiers supérieur.", answer_en: "The upper third." },
  { question_fr: "Quel fascia sépare le rectum de la prostate et de la vessie chez l'homme ?", question_en: "Which fascia separates the rectum from the prostate and bladder in the male?", answer_fr: "Le fascia recto-vésical de Denonvilliers.", answer_en: "The rectovesical fascia of Denonvilliers." },
  { question_fr: "Quel cul-de-sac péritonéal sépare le rectum de l'utérus ?", question_en: "Which peritoneal pouch separates the rectum from the uterus?", answer_fr: "Le cul-de-sac recto-utérin (de Douglas).", answer_en: "The rectouterine pouch (of Douglas)." },
  { question_fr: "Quel ganglion sympathique impair se situe en arrière du rectum, en avant de la jonction sacro-coccygienne ?", question_en: "Which unpaired sympathetic ganglion lies posterior to the rectum, anterior to the sacrococcygeal junction?", answer_fr: "Le ganglion impar.", answer_en: "The ganglion impar." },
  { question_fr: "Quel fascia relie l'ampoule rectale au sacrum et au coccyx ?", question_en: "Which fascia attaches the rectal ampulla to the sacrum and coccyx?", answer_fr: "Le fascia de Waldeyer.", answer_en: "The fascia of Waldeyer." },
  { question_fr: "Quelle artère vascularise la totalité de la muqueuse rectale jusqu'aux valvules anales ?", question_en: "Which artery supplies the entire rectal mucosa up to the anal valves?", answer_fr: "L'artère rectale supérieure.", answer_en: "The superior rectal artery." },
  { question_fr: "Dans quel système veineux se draine la veine rectale supérieure ?", question_en: "Into which venous system does the superior rectal vein drain?", answer_fr: "Le système porte (via la veine mésentérique inférieure puis la veine splénique).", answer_en: "The portal system (via the inferior mesenteric vein then the splenic vein)." },
  { question_fr: "Dans quel système veineux se drainent les veines rectales moyennes ?", question_en: "Into which venous system do the middle rectal veins drain?", answer_fr: "Le système systémique (cave), via la veine iliaque interne.", answer_en: "The systemic (caval) system, via the internal iliac vein." },
  { question_fr: "Comment appelle-t-on les plis muqueux transverses permanents du rectum ?", question_en: "What are the permanent transverse mucosal folds of the rectum called?", answer_fr: "Les valvules de Houston.", answer_en: "Houston's valves." },
  { question_fr: "Combien de valvules de Houston sont habituellement présentes ?", question_en: "How many Houston's valves are usually present?", answer_fr: "Trois.", answer_en: "Three." },
  { question_fr: "De quels segments spinaux proviennent les fibres sympathiques du rectum ?", question_en: "From which spinal segments do the sympathetic fibers of the rectum arise?", answer_fr: "L1-L2.", answer_en: "L1-L2." },
  { question_fr: "De quels segments spinaux proviennent les fibres parasympathiques du rectum ?", question_en: "From which spinal segments do the parasympathetic fibers of the rectum arise?", answer_fr: "S2-S3-S4.", answer_en: "S2-S3-S4." },
  { question_fr: "Quelle est la longueur du canal anal ?", question_en: "What is the length of the anal canal?", answer_fr: "3,8 cm.", answer_en: "3.8 cm." },
  { question_fr: "Quelle ligne sépare les parties haute et basse du canal anal ?", question_en: "Which line separates the upper and lower parts of the anal canal?", answer_fr: "La ligne pectinée (ou dentée).", answer_en: "The pectinate line (or dentate line)." },
  { question_fr: "Quelle est l'origine embryologique de la partie haute du canal anal ?", question_en: "What is the embryological origin of the upper anal canal?", answer_fr: "L'intestin postérieur endodermique.", answer_en: "The endodermal hindgut." },
  { question_fr: "Quelle est l'origine embryologique de la partie basse du canal anal ?", question_en: "What is the embryological origin of the lower anal canal?", answer_fr: "Le proctodéum ectodermique.", answer_en: "The ectodermal proctodeum." },
  { question_fr: "Qu'est-ce que les colonnes anales de Morgagni ?", question_en: "What are the anal columns of Morgagni?", answer_fr: "Des plis muqueux longitudinaux permanents contenant les radicelles de la veine rectale supérieure.", answer_en: "Permanent longitudinal mucosal folds containing radicles of the superior rectal vein." },
  { question_fr: "Qu'est-ce que les sinus anaux ?", question_en: "What are the anal sinuses?", answer_fr: "Des récessus verticaux entre les colonnes anales, au-dessus des valvules anales, recevant les glandes anales.", answer_en: "Vertical recesses between the anal columns, above the anal valves, receiving the anal glands." },
  { question_fr: "Quelle ligne marque la jonction entre le sphincter externe sous-cutané et l'extrémité basse du sphincter interne ?", question_en: "Which line marks the junction between the subcutaneous external sphincter and the lower end of the internal sphincter?", answer_fr: "La ligne blanche de Hilton.", answer_en: "The white line of Hilton." },
  { question_fr: "De quel type musculaire est fait le sphincter anal interne, et quelle est sa commande ?", question_en: "What muscle type is the internal anal sphincter made of, and how is it controlled?", answer_fr: "Muscle lisse, contrôle involontaire (autonome).", answer_en: "Smooth muscle, involuntary (autonomic) control." },
  { question_fr: "De quel type musculaire est fait le sphincter anal externe, et quelle est sa commande ?", question_en: "What muscle type is the external anal sphincter made of, and how is it controlled?", answer_fr: "Muscle strié, contrôle volontaire (nerf rectal inférieur).", answer_en: "Striated muscle, voluntary control (inferior rectal nerve)." },
  { question_fr: "Quelles sont les trois parties du sphincter anal externe ?", question_en: "What are the three parts of the external anal sphincter?", answer_fr: "Profonde, superficielle et sous-cutanée.", answer_en: "Deep, superficial, and subcutaneous." },
  { question_fr: "Quelle structure du sphincter externe forme une sangle autour de la jonction ano-rectale ?", question_en: "Which structure of the external sphincter forms a sling around the anorectal junction?", answer_fr: "Le faisceau pubo-rectal (fusionné à la partie profonde).", answer_en: "The puborectalis (blended with the deep part)." },
  { question_fr: "Quelle est la vascularisation artérielle de la partie haute du canal anal ?", question_en: "What is the arterial supply of the upper anal canal?", answer_fr: "L'artère rectale supérieure.", answer_en: "The superior rectal artery." },
  { question_fr: "Quelle est la vascularisation artérielle de la partie basse du canal anal ?", question_en: "What is the arterial supply of the lower anal canal?", answer_fr: "L'artère rectale inférieure.", answer_en: "The inferior rectal artery." },
  { question_fr: "Comment appelle-t-on l'anneau veineux formé par la communication des plexus veineux interne et externe du canal anal ?", question_en: "What is the venous ring formed by the communication of the internal and external venous plexuses of the anal canal called?", answer_fr: "L'annulus hemorrhoidalis.", answer_en: "The annulus hemorrhoidalis." },
  { question_fr: "Que sont les hémorroïdes sur le plan anatomique ?", question_en: "What are hemorrhoids anatomically?", answer_fr: "Des dilatations variqueuses des plexus veineux sous-muqueux anaux et périanaux.", answer_en: "Variceal dilatations of the submucosal anal and perianal venous plexuses." },
  { question_fr: "Vers quels nœuds lymphatiques draine la partie haute du canal anal ?", question_en: "Where does the upper anal canal drain lymphatically?", answer_fr: "Les nœuds iliaques internes.", answer_en: "The internal iliac nodes." },
  { question_fr: "Vers quels nœuds lymphatiques draine la partie basse du canal anal ?", question_en: "Where does the lower anal canal drain lymphatically?", answer_fr: "Les nœuds inguinaux superficiels.", answer_en: "The superficial inguinal nodes." },
  { question_fr: "Quelle est la sensibilité de la moitié haute de la muqueuse anale ?", question_en: "What is the sensitivity of the upper half of the anal mucosa?", answer_fr: "Sensible à l'étirement uniquement (innervation viscérale).", answer_en: "Sensitive to stretch only (visceral innervation)." },
  { question_fr: "Quelle est la sensibilité de la moitié basse de la muqueuse anale ?", question_en: "What is the sensitivity of the lower half of the anal mucosa?", answer_fr: "Sensible à la douleur, la température, le toucher et la pression (innervation somatique par le nerf rectal inférieur).", answer_en: "Sensitive to pain, temperature, touch, and pressure (somatic innervation via the inferior rectal nerve)." },
];

const KIDNEY_URETER_BLADDER_URETHRA_COURSE = `# Le rein, l'uretère, la vessie et l'urètre

## 1. Le rein — situation et rapports généraux
- Les reins sont deux organes en forme de haricot, rouge-brun, situés sur la paroi abdominale postérieure, rétropéritonéaux, en regard de T12 à L3.
- Le rein droit est légèrement plus bas que le gauche (présence du foie) ; le rein gauche est un peu plus proche du plan médian que le droit.
- Le grand axe de chaque rein est légèrement oblique (dirigé en bas et en dehors), rapprochant les pôles supérieurs l'un de l'autre : pôles supérieurs à 2-2,5 cm de la ligne médiane, pôles inférieurs à 6-7,5 cm.
- Les deux reins se déplacent verticalement d'environ 2,5 cm pendant la respiration. Le **plan transpylorique** passe par la partie supérieure du hile droit et la partie inférieure du hile gauche.

## 2. Configuration externe et capsules
- Chaque rein présente : deux pôles (supérieur, épais et arrondi, en rapport avec la surrénale ; inférieur, plus mince et pointu), deux surfaces (antérieure convexe, postérieure plane), deux bords (latéral convexe, médial concave au milieu où se trouve le **hile**) et un hile.
- Le hile transmet d'avant en arrière : veine rénale, artère rénale, bassinet (pelvis rénal), branche subsidiaire de l'artère rénale, lymphatiques et nerfs.
- **Rapports antérieurs du rein droit** : surrénale droite, lobe droit du foie, deuxième portion du duodénum, angle colique droit, jéjunum (foie et jéjunum séparés par le péritoine).
- **Rapports antérieurs du rein gauche** : surrénale gauche, rate, estomac, pancréas et vaisseaux spléniques, angle colique gauche, jéjunum (estomac, rate et jéjunum séparés par le péritoine).
- **Rapports postérieurs** (identiques sauf le nombre de côtes) : quatre muscles (diaphragme, carré des lombes, psoas majeur, transverse de l'abdomen) ; trois nerfs (subcostal, ilio-hypogastrique, ilio-inguinal, L1) ; une ou deux côtes (12e à droite ; 11e et 12e à gauche).
- **Capsules, de dedans en dehors** : capsule fibreuse (vraie capsule, se prolonge dans le hile pour tapisser le sinus rénal) ; graisse périrénale ; fascia rénal (fausse capsule, ou fascia de Gerota, avec un feuillet antérieur mal défini — fascia de Toldt — et un feuillet postérieur bien défini — fascia de Zuckerkandl) ; graisse pararénale, en dehors du fascia rénal.

## 3. Structure macroscopique
- Coupé longitudinalement, le rein présente le **rein proprement dit** et le **sinus rénal**.
- Le rein proprement dit comprend un **cortex** externe (sous la capsule, se prolongeant entre les pyramides sous forme de colonnes de Bertin) et une **médulla** interne, formée de 5 à 11 masses coniques (**pyramides de Malpighi**) dont l'apex forme les papilles rénales, s'invaginant dans les petits calices. Une pyramide et son cortex forment un lobe rénal.
- Le **sinus rénal** est une cavité s'ouvrant au hile, contenant la majeure partie du bassinet et des calices, les vaisseaux rénaux, les lymphatiques, les nerfs et de la graisse.
- Chaque papille est associée à un **petit calice** ; plusieurs petits calices fusionnent en un **grand calice** ; l'urine passe ensuite dans le **bassinet** (pelvis rénal), structure aplatie en entonnoir, puis dans l'uretère.

## 4. Structure microscopique
- Le rein est constitué de **néphrons** et de tubes collecteurs. Le **néphron** est l'unité structurale et fonctionnelle du rein (1 à 3 millions par rein).
- Chaque néphron comprend un **corpuscule rénal** (glomérule, pelote capillaire, entouré de la capsule de Bowman) et un système tubulaire (tube contourné proximal, anse de Henlé, tube contourné distal).
- Chaque tube collecteur débute par un tube de jonction issu du tube contourné distal ; plusieurs tubes collecteurs s'unissent en un **canal collecteur (de Bellini)**, qui s'ouvre à l'apex de la papille. Les tubes collecteurs forment, en rayonnant vers le cortex, les **rayons médullaires**.

## 5. Vascularisation et innervation du rein
- Chaque rein reçoit habituellement une **artère rénale** (artères rénales accessoires chez ~30 % des sujets), naissant directement de l'aorte abdominale juste sous l'origine de l'artère mésentérique supérieure (niveau du disque L1-L2). L'artère rénale droite passe en arrière de la veine cave inférieure et de la veine rénale droite ; la gauche passe en arrière de la veine rénale gauche.
- Près du hile, chaque artère rénale se divise en division antérieure (segments apical, supérieur, moyen, inférieur) et division postérieure (segment postérieur seul). La limite entre ces territoires est la **ligne de Brödel**, plan avasculaire fonctionnel, site chirurgical privilégié.
- Les artères segmentaires donnent des branches lobaires, puis interlobaires (dans les colonnes rénales), puis **artères arquées** (à la base des pyramides, parallèles à la surface), puis **artères interlobulaires** (radiaires), puis artérioles afférentes → capillaires glomérulaires → artérioles efférentes → plexus capillaire péritubulaire. Le retour veineux suit un trajet symétrique (veines interlobulaires → arquées → interlobaires → veine rénale).
- Innervation : plexus rénal, issu du plexus cœliaque, fibres sympathiques (T10-L1) et parasympathiques (nerfs vagues).

## 6. L'uretère
- Tube musculaire étroit, épais et extensible, conduisant l'urine du rein à la vessie par péristaltisme. Longueur 25-30 cm, diamètre 3 mm.
- **Trajet** : continuation du bassinet, descend obliquement en dedans sur le psoas majeur, croise en avant la bifurcation de l'artère iliaque commune au détroit supérieur (en avant de l'articulation sacro-iliaque) pour entrer dans le pelvis. Dans le pelvis, il descend d'abord en arrière et en dehors le long du bord antérieur de la grande échancrure sciatique, puis, en regard de l'épine ischiatique, se dirige en avant et en dedans vers la base de la vessie, qu'il traverse obliquement. Il chemine derrière le péritoine pariétal, auquel il est étroitement appliqué.
- **Parties et rapports** : divisé en partie abdominale et partie pelvienne (à la bifurcation de l'iliaque commune). À droite, rapports antérieurs avec le 2e duodénum, les vaisseaux coliques/iléo-coliques droits, les vaisseaux génitaux droits, la racine du mésentère ; à gauche, avec les vaisseaux coliques gauches, sigmoïdiens, génitaux gauches, le méso-sigmoïde. Dans le pelvis, rapports avec l'artère iliaque interne, le nerf obturateur, diverses artères viscérales, et chez l'homme le déférent qui le croise médialement, chez la femme l'artère utérine qui le croise.
- **Rétrécissements physiologiques** (sites d'arrêt des calculs) : jonction pyélo-urétérale (~5 cm du hile) ; croisement du détroit supérieur (bifurcation iliaque) ; jonction urétéro-vésicale.
- Vascularisation par de multiples branches (rénale, génitale, aortique directe, iliaque interne, vésicale, rectale moyenne, utérine) ; innervation sympathique T12-L1, parasympathique S2-S4.

## 7. La vessie — situation et configuration externe
- Réservoir musculaire de l'urine, situé dans la partie antérieure du petit bassin, derrière la symphyse pubienne, en avant du rectum (homme) ou de l'utérus (femme). Sa position varie avec son degré de réplétion : vide, elle est entièrement pelvienne ; pleine, elle s'étend en haut et en avant dans l'abdomen.
- Configuration : apex, base, col, trois surfaces (supérieure, deux inféro-latérales), quatre bords (antérieur, postérieur, deux latéraux).
- **Apex** : donne insertion au ligament ombilical médian (vestige de l'ouraque), en arrière du bord supérieur de la symphyse.
- **Base (surface postérieure/fond)**, triangulaire : les angles supéro-latéraux reçoivent les uretères, l'angle inférieur donne naissance à l'urètre. Chez l'homme, séparée du rectum en haut par le cul-de-sac recto-vésical, en bas par les ampoules déférentielles et vésicules séminales, puis par le fascia de Denonvilliers. Chez la femme, séparée du col utérin par le cul-de-sac vésico-utérin.
- **Col** : partie la plus fixe et la plus basse, traversée par l'urètre, ~3-4 cm derrière la symphyse ; repose sur la prostate chez l'homme, en rapport avec le diaphragme urogénital chez la femme.
- **Surface supérieure**, triangulaire, entièrement péritonisée chez l'homme (séparée des anses iléales/sigmoïde) ; chez la femme, péritonisée sauf une petite zone près du bord postérieur (réflexion en cul-de-sac vésico-utérin sur l'isthme utérin).
- **Surfaces inféro-latérales**, non péritonisées, en rapport en avant avec l'espace rétropubien (de Retzius), la symphyse, les ligaments pubo-prostatiques ; en arrière avec l'obturateur interne (en haut) et le releveur de l'anus (en bas).

## 8. Moyens de fixité, structure et configuration interne de la vessie
- **Ligaments vrais** : ligaments latéraux (vers l'arc tendineux du fascia pelvien) ; ligaments pubo-prostatiques (fixent le col) — pubo-vésicaux chez la femme ; ligament ombilical médian (reliquat de l'ouraque) ; ligaments postérieurs.
- **Structure pariétale**, de dedans en dehors : muqueuse plissée en rugae à vide ; sous-muqueuse ; **muscle détrusor** (trois couches de fibres lisses : longitudinale externe, circulaire moyenne — formant autour du méat urétral interne le sphincter lisse interne, continu avec la musculature prostatique —, longitudinale interne) ; adventice fibro-élastique.
- **Trigone vésical** : zone triangulaire à paroi lisse délimitée par les deux orifices urétéraux et le méat urétral interne. La **crête inter-urétérique (barre de Mercier)** relie les deux orifices urétéraux ; les **replis urétéro-urétraux (barres de Bell)** guident vers le méat urétral en cystoscopie. L'**uvule vésicale** est une saillie muqueuse juste en arrière du méat urétral interne, produite par le lobe médian de la prostate.
- Vascularisation par les artères vésicales supérieure, moyenne et inférieure (homme) ou vaginale (femme), branches de la division antérieure de l'iliaque interne. Drainage veineux par le plexus veineux vésical vers les veines iliaques internes. Lymphatiques vers les nœuds iliaques externes principalement.
- **Innervation** : parasympathique (nervi erigentes, S2-S4, moteur pour le détrusor, inhibiteur pour le sphincter — responsable de la vidange) ; sympathique (T11-L2, inhibiteur pour le détrusor, moteur pour le sphincter — responsable du remplissage) ; somatique (nerf honteux, S2-S4, moteur pour le sphincter externe strié — contrôle volontaire de la miction).

## 9. L'urètre masculin
- Conduit à la fois l'urine et le sperme. Longueur ~18-20 cm, du méat urétral interne (col vésical) au méat urétral externe (gland). En érection il devient en « J » (disparition de la courbure distale) contre un trajet en « S » à l'état flaccide.
- **Trois parties** : prostatique (traverse la prostate) ; membraneuse (traverse le diaphragme urogénital, entourée du sphincter urétral strié volontaire) ; spongieuse/pénienne (traverse le corps spongieux).
- Partie prostatique : crête urétrale médiane, avec le **colliculus séminal (veru montanum)** portant l'orifice de l'utricule prostatique et, de part et d'autre, les orifices des canaux éjaculateurs ; sinus prostatiques de chaque côté recevant les orifices des glandes prostatiques.
- Partie membraneuse : la plus courte, entourée du sphincter urétral strié (continence volontaire).
- Partie spongieuse : présente deux dilatations (fosse intrabulbaire dans le bulbe, fosse naviculaire dans le gland) ; reçoit les glandes urétrales de Littré et les lacunes de Morgagni (sauf dans la fosse naviculaire).

## 10. L'urètre féminin
- Longueur ~4 cm, du méat urétral interne (col vésical) au vestibule vaginal (en avant de l'orifice vaginal, 2-3 cm en arrière du clitoris), traversant le diaphragme urogénital, embedded dans la paroi antérieure du vagin.
- Vascularisation par les artères honteuses internes, vaginales et les branches vésicales inférieures des artères vaginales.

## Points à retenir
- Le rein est rétropéritonéal, en regard de T12-L3, entouré de quatre capsules (fibreuse, graisse périrénale, fascia de Gerota, graisse pararénale) ; le néphron (1-3 millions/rein) en est l'unité fonctionnelle.
- L'uretère présente trois rétrécissements physiologiques (jonction pyélo-urétérale, croisement iliaque, jonction urétéro-vésicale), sites d'enclavement des calculs.
- La vessie a un trigone lisse délimité par les orifices urétéraux et le méat urétral interne ; sa continence dépend du sphincter lisse interne (involontaire) et du sphincter strié externe (volontaire, S2-S4).
- L'urètre masculin (18-20 cm, 3 parties) sert au transport de l'urine et du sperme ; l'urètre féminin (4 cm) ne transporte que l'urine.`;

export const KIDNEY_URETER_BLADDER_URETHRA_LEARNING: LibraryLearningSeed = {
  resource: {
    resource_type: "course",
    titre_fr: "Cours condensé — Le rein, l'uretère, la vessie et l'urètre",
    source_label: "Anatomie — Lecture 11",
    content_fr: KIDNEY_URETER_BLADDER_URETHRA_COURSE,
  },
  qcm: [
    single("À quel niveau vertébral se situent les reins ?", "C", "Les reins se situent en regard de T12 à L3, de part et d'autre du rachis.", ["T6-T10", "L4-S1", "T12-L3", "C7-T4"]),
    single("Pourquoi le rein droit est-il un peu plus bas que le gauche ?", "A", "Le rein droit est abaissé par la présence du foie du côté droit.", ["La présence du foie", "La présence de la rate", "Le trajet de l'aorte", "L'implantation de l'uretère droit"]),
    single("Que transmet le hile du rein, d'avant en arrière ?", "B", "D'avant en arrière : veine rénale, artère rénale, puis bassinet (pelvis rénal).", ["Artère, veine, bassinet", "Veine, artère, bassinet", "Bassinet, artère, veine", "Nerfs, veine, artère"]),
    multi("Quelles structures composent le fascia rénal (fascia de Gerota) ?", ["A", "B"], "Le fascia de Gerota comprend un feuillet antérieur mal défini (fascia de Toldt) et un feuillet postérieur bien défini (fascia de Zuckerkandl).", ["Le fascia de Toldt (feuillet antérieur)", "Le fascia de Zuckerkandl (feuillet postérieur)", "La capsule fibreuse vraie", "La graisse pararénale"]),
    single("Dans quel ordre, de dedans en dehors, se disposent les enveloppes du rein ?", "A", "De dedans en dehors : capsule fibreuse, graisse périrénale, fascia rénal (de Gerota), graisse pararénale.", ["Capsule fibreuse, graisse périrénale, fascia rénal, graisse pararénale", "Fascia rénal, capsule fibreuse, graisse périrénale, graisse pararénale", "Graisse pararénale, fascia rénal, graisse périrénale, capsule fibreuse", "Capsule fibreuse, fascia rénal, graisse périrénale, graisse pararénale"]),
    single("Comment s'appellent les masses coniques de la médulla rénale ?", "B", "Les pyramides de Malpighi forment la médulla rénale ; leur apex constitue les papilles rénales.", ["Les colonnes de Bertin", "Les pyramides de Malpighi", "Les corpuscules de Bowman", "Les rayons médullaires"]),
    single("Qu'est-ce qu'un lobe rénal ?", "C", "Un lobe rénal est constitué d'une pyramide de Malpighi et de sa coiffe corticale.", ["Le regroupement de tous les néphrons du cortex", "Une subdivision du sinus rénal", "Une pyramide de Malpighi avec sa coiffe corticale", "Le bassinet et ses calices"]),
    single("Combien de néphrons compte environ chaque rein ?", "C", "Chaque rein contient environ 1 à 3 millions de néphrons.", ["100 000 à 300 000", "500 000", "1 à 3 millions", "10 millions"]),
    single("Que forme la fusion de plusieurs tubes collecteurs ?", "B", "Plusieurs tubes collecteurs s'unissent pour former le canal collecteur (canal de Bellini), qui s'ouvre à l'apex de la papille.", ["Le tube contourné distal", "Le canal collecteur (de Bellini)", "L'anse de Henlé", "Le bassinet"]),
    single("D'où naît l'artère rénale ?", "B", "L'artère rénale naît directement de l'aorte abdominale, juste sous l'origine de l'artère mésentérique supérieure.", ["De l'artère mésentérique inférieure", "De l'aorte abdominale, juste sous l'artère mésentérique supérieure", "De l'artère iliaque commune", "De la veine cave inférieure"]),
    single("Qu'est-ce que la ligne de Brödel ?", "A", "La ligne de Brödel est la limite fonctionnelle avasculaire entre les territoires des divisions antérieure et postérieure de l'artère rénale, site chirurgical privilégié.", ["La limite avasculaire entre divisions antérieure et postérieure de l'artère rénale", "La limite entre cortex et médulla", "Le trajet de l'uretère dans le sinus rénal", "La ligne de jonction pyélo-urétérale"]),
    single("Quelle est la longueur habituelle de l'uretère ?", "B", "L'uretère mesure 25 à 30 cm de long.", ["10-15 cm", "25-30 cm", "40-45 cm", "50-60 cm"]),
    multi("Quels sont les trois rétrécissements physiologiques de l'uretère ?", ["A", "B", "C"], "Les trois rétrécissements sont la jonction pyélo-urétérale, le croisement du détroit supérieur (bifurcation iliaque) et la jonction urétéro-vésicale — sites d'enclavement des calculs.", ["La jonction pyélo-urétérale", "Le croisement de l'artère iliaque commune au détroit supérieur", "La jonction urétéro-vésicale", "Le croisement de l'artère mésentérique supérieure"]),
    single("Que croise l'uretère en entrant dans le pelvis ?", "C", "L'uretère croise en avant la bifurcation de l'artère iliaque commune au niveau du détroit supérieur.", ["L'artère rénale", "L'aorte abdominale", "La bifurcation de l'artère iliaque commune", "L'artère mésentérique inférieure"]),
    single("Chez l'homme, quelle structure croise médialement l'uretère pelvien ?", "A", "Chez l'homme, le canal déférent croise l'uretère et passe médialement à celui-ci.", ["Le canal déférent", "La vésicule séminale", "L'artère honteuse interne", "Le nerf obturateur"]),
    single("Quelle est la forme du trigone vésical, et quelle particularité présente sa muqueuse ?", "B", "Le trigone est une zone triangulaire délimitée par les orifices urétéraux et le méat urétral interne, à muqueuse lisse (sans rugae), contrairement au reste de la vessie.", ["Ovale, avec rugae marquées", "Triangulaire, à muqueuse lisse", "Circulaire, richement vascularisée", "Triangulaire, tapissée de villosités"]),
    single("Qu'est-ce que la crête inter-urétérique (barre de Mercier) ?", "A", "C'est le relief qui relie les deux orifices urétéraux et forme la limite supérieure du trigone.", ["Le relief reliant les deux orifices urétéraux, bordant le trigone en haut", "Le sphincter lisse du col vésical", "Le ligament ombilical médian", "Une structure présente uniquement chez la femme"]),
    single("Quelles sont les trois couches musculaires du détrusor ?", "C", "Le détrusor comprend une couche longitudinale externe, une couche circulaire moyenne et une couche longitudinale interne.", ["Circulaire externe, oblique moyenne, longitudinale interne", "Longitudinale unique", "Longitudinale externe, circulaire moyenne, longitudinale interne", "Radiaire, circulaire, spirale"]),
    single("Quel système nerveux est responsable du remplissage vésical ?", "B", "Le système sympathique (T11-L2) inhibe le détrusor et stimule le sphincter, favorisant le remplissage.", ["Le parasympathique", "Le sympathique", "Le système somatique seul", "Le système entérique"]),
    single("Quel système nerveux est responsable de la vidange vésicale (contraction du détrusor) ?", "A", "Le parasympathique (nervi erigentes, S2-S4) est moteur pour le détrusor et inhibiteur pour le sphincter, permettant la vidange.", ["Le parasympathique", "Le sympathique", "Le système somatique seul", "Aucun, la vidange est un réflexe purement local"]),
    single("Quel nerf assure le contrôle volontaire du sphincter urétral externe ?", "C", "Le nerf honteux (pudendal), fibres somatiques S2-S4, innerve le sphincter urétral externe strié.", ["Le nerf obturateur", "Le nerf splanchnique pelvien", "Le nerf honteux (pudendal)", "Le nerf fémoral"]),
    single("Quelle est la longueur approximative de l'urètre masculin ?", "C", "L'urètre masculin mesure environ 18-20 cm.", ["4 cm", "8-10 cm", "18-20 cm", "25 cm"]),
    single("Quelles sont les trois parties de l'urètre masculin ?", "A", "L'urètre masculin comprend une partie prostatique, une partie membraneuse et une partie spongieuse (pénienne).", ["Prostatique, membraneuse, spongieuse", "Prostatique, bulbaire, naviculaire", "Vésicale, membraneuse, glandulaire", "Interne, moyenne, externe"]),
    single("Qu'est-ce que le colliculus séminal (veru montanum) ?", "B", "C'est une élévation sur la crête urétrale, dans la partie prostatique de l'urètre, portant l'orifice de l'utricule prostatique et des canaux éjaculateurs.", ["Le sphincter urétral externe", "Une élévation de la crête urétrale portant l'orifice de l'utricule prostatique et des canaux éjaculateurs", "La partie la plus large de l'urètre spongieux", "Un repli muqueux de l'urètre féminin"]),
    single("Quelle est la longueur approximative de l'urètre féminin ?", "B", "L'urètre féminin mesure environ 4 cm.", ["1 cm", "4 cm", "10 cm", "15 cm"]),
  ],
  exam: { titre_fr: "Examen chronométré — Rein, uretère, vessie et urètre", duration_seconds: 2_000 },
};

export const KIDNEY_URETER_BLADDER_URETHRA_FLASHCARDS: LibraryCardSeed[] = [
  { question_fr: "En regard de quels niveaux vertébraux se situent les reins ?", question_en: "At what vertebral levels are the kidneys located?", answer_fr: "T12 à L3.", answer_en: "T12 to L3." },
  { question_fr: "Quel plan horizontal passe par les deux hiles rénaux ?", question_en: "Which horizontal plane passes through both renal hila?", answer_fr: "Le plan transpylorique.", answer_en: "The transpyloric plane." },
  { question_fr: "Quelles structures traversent le hile rénal ?", question_en: "What structures pass through the renal hilum?", answer_fr: "La veine rénale, l'artère rénale, le bassinet, une branche subsidiaire de l'artère, les lymphatiques et les nerfs (d'avant en arrière).", answer_en: "The renal vein, renal artery, renal pelvis, a subsidiary arterial branch, lymphatics, and nerves (front to back)." },
  { question_fr: "Nommez les quatre enveloppes du rein, de dedans en dehors.", question_en: "Name the four coverings of the kidney, from inside out.", answer_fr: "Capsule fibreuse, graisse périrénale, fascia rénal (de Gerota), graisse pararénale.", answer_en: "Fibrous capsule, perirenal fat, renal fascia (of Gerota), pararenal fat." },
  { question_fr: "Quels sont les deux feuillets du fascia de Gerota ?", question_en: "What are the two layers of Gerota's fascia?", answer_fr: "Le fascia de Toldt (antérieur) et le fascia de Zuckerkandl (postérieur).", answer_en: "The fascia of Toldt (anterior) and the fascia of Zuckerkandl (posterior)." },
  { question_fr: "Que contient le cortex rénal entre les pyramides ?", question_en: "What does the renal cortex contain between the pyramids?", answer_fr: "Les colonnes de Bertin.", answer_en: "The columns of Bertin." },
  { question_fr: "Comment s'appellent les masses coniques de la médulla rénale ?", question_en: "What are the conical masses of the renal medulla called?", answer_fr: "Les pyramides de Malpighi.", answer_en: "The pyramids of Malpighi." },
  { question_fr: "Que forme l'apex d'une pyramide rénale ?", question_en: "What does the apex of a renal pyramid form?", answer_fr: "La papille rénale, qui s'invagine dans un petit calice.", answer_en: "The renal papilla, which invaginates into a minor calyx." },
  { question_fr: "Quel est l'ordre de drainage de l'urine, du calice au bassinet ?", question_en: "What is the drainage order of urine, from calyx to pelvis?", answer_fr: "Petit calice → grand calice → bassinet (pelvis rénal) → uretère.", answer_en: "Minor calyx → major calyx → renal pelvis → ureter." },
  { question_fr: "Quelle est l'unité fonctionnelle du rein ?", question_en: "What is the functional unit of the kidney?", answer_fr: "Le néphron.", answer_en: "The nephron." },
  { question_fr: "De quoi est composé le corpuscule rénal ?", question_en: "What is the renal corpuscle composed of?", answer_fr: "Le glomérule (pelote capillaire) entouré de la capsule de Bowman.", answer_en: "The glomerulus (capillary tuft) surrounded by Bowman's capsule." },
  { question_fr: "Quelles sont les trois parties du système tubulaire du néphron ?", question_en: "What are the three parts of the nephron's tubular system?", answer_fr: "Le tube contourné proximal, l'anse de Henlé, le tube contourné distal.", answer_en: "The proximal convoluted tubule, the loop of Henle, and the distal convoluted tubule." },
  { question_fr: "Comment s'appelle le canal formé par la fusion des tubes collecteurs ?", question_en: "What is the canal formed by the fusion of collecting tubules called?", answer_fr: "Le canal collecteur (de Bellini).", answer_en: "The collecting duct (of Bellini)." },
  { question_fr: "D'où naît l'artère rénale ?", question_en: "Where does the renal artery arise from?", answer_fr: "De l'aorte abdominale, juste sous l'artère mésentérique supérieure (niveau L1-L2).", answer_en: "From the abdominal aorta, just below the superior mesenteric artery (L1-L2 level)." },
  { question_fr: "En quelles deux divisions se sépare l'artère rénale près du hile ?", question_en: "Into which two divisions does the renal artery split near the hilum?", answer_fr: "Une division antérieure et une division postérieure.", answer_en: "An anterior division and a posterior division." },
  { question_fr: "Qu'est-ce que la ligne de Brödel ?", question_en: "What is Brödel's line?", answer_fr: "Le plan avasculaire fonctionnel entre les territoires des divisions antérieure et postérieure de l'artère rénale, site chirurgical.", answer_en: "The functional avascular plane between the territories of the anterior and posterior divisions of the renal artery, a surgical landmark." },
  { question_fr: "Quelles sont les artères, dans l'ordre, entre l'artère segmentaire et le glomérule ?", question_en: "What arteries lie, in order, between the segmental artery and the glomerulus?", answer_fr: "Artère lobaire → interlobaire → arquée → interlobulaire → artériole afférente.", answer_en: "Lobar artery → interlobar → arcuate → interlobular → afferent arteriole." },
  { question_fr: "D'où provient l'innervation parasympathique du rein ?", question_en: "Where does the parasympathetic innervation of the kidney come from?", answer_fr: "Des nerfs vagues.", answer_en: "The vagus nerves." },
  { question_fr: "Quelle est la longueur et le diamètre de l'uretère ?", question_en: "What is the length and diameter of the ureter?", answer_fr: "25-30 cm de long, 3 mm de diamètre.", answer_en: "25-30 cm long, 3 mm in diameter." },
  { question_fr: "Comment l'urine progresse-t-elle dans l'uretère ?", question_en: "How does urine move through the ureter?", answer_fr: "Par péristaltisme (contractions du muscle lisse de sa paroi).", answer_en: "By peristalsis (contractions of the smooth muscle in its wall)." },
  { question_fr: "Qu'est-ce que l'uretère croise pour entrer dans le pelvis ?", question_en: "What does the ureter cross to enter the pelvis?", answer_fr: "La bifurcation de l'artère iliaque commune, au détroit supérieur.", answer_en: "The bifurcation of the common iliac artery, at the pelvic brim." },
  { question_fr: "Nommez les trois rétrécissements physiologiques de l'uretère.", question_en: "Name the three physiological constrictions of the ureter.", answer_fr: "Jonction pyélo-urétérale, croisement du détroit supérieur, jonction urétéro-vésicale.", answer_en: "Pelviureteric junction, pelvic brim crossing, and ureterovesical junction." },
  { question_fr: "Quelle structure croise l'uretère médialement chez l'homme ?", question_en: "What structure crosses the ureter medially in the male?", answer_fr: "Le canal déférent.", answer_en: "The ductus (vas) deferens." },
  { question_fr: "Quelle artère croise l'uretère chez la femme ?", question_en: "Which artery crosses the ureter in the female?", answer_fr: "L'artère utérine.", answer_en: "The uterine artery." },
  { question_fr: "Où se situe la vessie par rapport à la symphyse pubienne ?", question_en: "Where is the bladder located relative to the pubic symphysis?", answer_fr: "Immédiatement en arrière de la symphyse pubienne.", answer_en: "Immediately posterior to the pubic symphysis." },
  { question_fr: "À quelle structure fibreuse l'apex de la vessie donne-t-il attache ?", question_en: "What fibrous structure attaches at the apex of the bladder?", answer_fr: "Le ligament ombilical médian (reliquat de l'ouraque).", answer_en: "The median umbilical ligament (remnant of the urachus)." },
  { question_fr: "Chez l'homme, quel fascia sépare la base de la vessie du rectum ?", question_en: "In the male, which fascia separates the bladder base from the rectum?", answer_fr: "Le fascia recto-vésical de Denonvilliers.", answer_en: "The rectovesical fascia of Denonvilliers." },
  { question_fr: "Quel cul-de-sac péritonéal sépare la base de la vessie du col utérin chez la femme ?", question_en: "Which peritoneal pouch separates the bladder base from the cervix in the female?", answer_fr: "Le cul-de-sac vésico-utérin.", answer_en: "The vesicouterine pouch." },
  { question_fr: "Sur quelle structure repose le col vésical chez l'homme ?", question_en: "What structure does the bladder neck rest on in the male?", answer_fr: "La prostate.", answer_en: "The prostate." },
  { question_fr: "Qu'est-ce que le trigone vésical ?", question_en: "What is the trigone of the bladder?", answer_fr: "Une zone triangulaire à muqueuse lisse délimitée par les deux orifices urétéraux et le méat urétral interne.", answer_en: "A triangular, smooth-walled area bounded by the two ureteric orifices and the internal urethral meatus." },
  { question_fr: "Qu'est-ce que la crête inter-urétérique (barre de Mercier) ?", question_en: "What is the interureteric crest (bar of Mercier)?", answer_fr: "Le relief reliant les deux orifices urétéraux, formant la limite supérieure du trigone.", answer_en: "The ridge connecting the two ureteric orifices, forming the superior boundary of the trigone." },
  { question_fr: "Qu'est-ce que l'uvule vésicale, et qu'est-ce qui la produit ?", question_en: "What is the uvula vesicae, and what produces it?", answer_fr: "Une élévation muqueuse juste au-dessus du méat urétral interne, produite par le lobe médian de la prostate.", answer_en: "A mucosal elevation just above the internal urethral orifice, produced by the median lobe of the prostate." },
  { question_fr: "Comment s'appelle le muscle de la paroi vésicale, et combien de couches comporte-t-il ?", question_en: "What is the bladder wall muscle called, and how many layers does it have?", answer_fr: "Le muscle détrusor, trois couches (longitudinale externe, circulaire moyenne, longitudinale interne).", answer_en: "The detrusor muscle, three layers (outer longitudinal, middle circular, inner longitudinal)." },
  { question_fr: "Que forme la couche circulaire moyenne du détrusor autour du méat urétral interne ?", question_en: "What does the middle circular layer of the detrusor form around the internal urethral orifice?", answer_fr: "Le sphincter lisse interne (sphincter vésical), continu avec la musculature prostatique.", answer_en: "The internal (smooth) urethral sphincter, continuous with the prostatic musculature." },
  { question_fr: "Quel système nerveux est moteur pour le détrusor et inhibiteur pour le sphincter, permettant la vidange ?", question_en: "Which nervous system is motor to the detrusor and inhibitory to the sphincter, enabling emptying?", answer_fr: "Le parasympathique (nervi erigentes, S2-S4).", answer_en: "The parasympathetic system (nervi erigentes, S2-S4)." },
  { question_fr: "Quel système nerveux est inhibiteur pour le détrusor et moteur pour le sphincter, permettant le remplissage ?", question_en: "Which nervous system is inhibitory to the detrusor and motor to the sphincter, enabling filling?", answer_fr: "Le sympathique (T11-L2).", answer_en: "The sympathetic system (T11-L2)." },
  { question_fr: "Quel nerf assure le contrôle volontaire de la miction via le sphincter externe ?", question_en: "Which nerve provides voluntary control of micturition via the external sphincter?", answer_fr: "Le nerf honteux (pudendal, S2-S4).", answer_en: "The pudendal nerve (S2-S4)." },
  { question_fr: "Quelle est la longueur de l'urètre masculin ?", question_en: "What is the length of the male urethra?", answer_fr: "18-20 cm.", answer_en: "18-20 cm." },
  { question_fr: "Nommez les trois parties de l'urètre masculin.", question_en: "Name the three parts of the male urethra.", answer_fr: "Prostatique, membraneuse, spongieuse (pénienne).", answer_en: "Prostatic, membranous, and spongy (penile)." },
  { question_fr: "Quelle partie de l'urètre masculin est entourée du sphincter urétral strié ?", question_en: "Which part of the male urethra is surrounded by the striated urethral sphincter?", answer_fr: "La partie membraneuse.", answer_en: "The membranous part." },
  { question_fr: "Qu'est-ce que le colliculus séminal (veru montanum) ?", question_en: "What is the seminal colliculus (verumontanum)?", answer_fr: "Une élévation sur la crête urétrale, dans la partie prostatique, portant l'orifice de l'utricule prostatique et des canaux éjaculateurs.", answer_en: "An elevation on the urethral crest, in the prostatic part, bearing the opening of the prostatic utricle and the ejaculatory ducts." },
  { question_fr: "Quelles glandes s'ouvrent dans la partie spongieuse de l'urètre masculin ?", question_en: "Which glands open into the spongy part of the male urethra?", answer_fr: "Les glandes urétrales (de Littré).", answer_en: "The urethral glands (of Littré)." },
  { question_fr: "Quelle est la longueur de l'urètre féminin ?", question_en: "What is the length of the female urethra?", answer_fr: "Environ 4 cm.", answer_en: "About 4 cm." },
  { question_fr: "Où s'ouvre l'urètre féminin ?", question_en: "Where does the female urethra open?", answer_fr: "Dans le vestibule du vagin, en avant de l'orifice vaginal.", answer_en: "Into the vestibule of the vagina, in front of the vaginal orifice." },
];

const FEMALE_GENITAL_ORGANS_COURSE = `# Les organes génitaux internes féminins et masculins

## 1. Les ovaires — généralités
- Les organes génitaux internes féminins comprennent une paire d'**ovaires**, une paire de **trompes utérines**, un **utérus** et un **vagin**.
- Les ovaires sont les gonades féminines, homologues des testicules. Fonctions : production des **ovocytes** (gamètes) et sécrétion des stéroïdes sexuels (**œstrogène** et **progestérone**).
- Forme amygdalienne, gris rosé ; surface lisse chez la nullipare, irrégulière chez la multipare. Dimensions : ~4 cm de long, 2 cm de large, 1 cm d'épaisseur.

## 2. Situation et rapports péritonéaux de l'ovaire
- Chez la nullipare, chaque ovaire est logé dans la **fossette ovarienne**, dépression péritonéale de la paroi pelvienne latérale sous le détroit supérieur, limitée en arrière par l'uretère et les vaisseaux iliaques internes, en haut par les vaisseaux iliaques externes, en avant par l'artère ombilicale oblitérée, en bas par le nerf obturateur et ses vaisseaux.
- L'ovaire est relié à la face postérieure du ligament large par un court repli péritonéal, le **mésovarium**, qui sert de hile (passage des vaisseaux/nerfs). L'ovaire est presque entièrement recouvert de péritoine sauf le long de son bord mésovarien.
- Extrémités : supérieure (en rapport avec la trompe et la veine iliaque externe, donnant attache au **ligament suspenseur de l'ovaire** contenant les vaisseaux ovariens) et inférieure (plus étroite, reliée à l'angle utérin par le **ligament propre de l'ovaire**).
- Surfaces : latérale (convexe, au contact du péritoine pariétal de la fossette ovarienne) et médiale (recouverte par la trompe, séparée par la bourse ovarienne).
- Bords : antérieur (mésovarien) et postérieur (libre, convexe, en rapport avec l'uretère).

## 3. Structure et vascularisation de l'ovaire
- Histologiquement : **cortex** périphérique (follicules ovariens à différents stades, épithélium germinatif, tunique albuginée sous-jacente) et **médulla** centrale (tissu conjonctif lâche, gros vaisseaux).
- Artère : **artère ovarienne**, née de l'aorte au niveau de L1, cheminant dans le ligament suspenseur puis le mésovarium, s'anastomosant avec l'artère utérine. Apport complémentaire par le rameau ovarien de l'artère utérine.
- Veines : plexus pampiniforme puis veine ovarienne unique ; la veine ovarienne droite se draine dans la veine cave inférieure, la gauche dans la veine rénale gauche.
- Lymphatiques : vers les nœuds pré-aortiques et para-aortiques. Innervation sympathique (T10-T11) et parasympathique (S2-S4).

## 4. Les trompes utérines
- Relient la cavité péritonéale à la cavité utérine ; site de fécondation et de transport de l'ovocyte. Longueur ~10 cm, logée dans le mésosalpinx du ligament large.
- Extrémité médiale : ouverture dans l'angle utérin (ostium utérin, 1 mm). Extrémité latérale (**pavillon**) : communique avec la cavité péritonéale, bordée de franges (**fimbriae**), dont une plus longue, la **frange ovarique**, appliquée à l'ovaire.
- **Quatre parties**, de latéral à médial : **infundibulum** (1 cm, en entonnoir, porte l'ostium abdominal et les franges) ; **ampoule** (5 cm, la plus large et longue, site de la fécondation) ; **isthme** (2,5-3 cm, étroit, à paroi musculaire épaisse) ; **partie intra-murale/interstitielle** (1 cm, traverse la paroi utérine).
- Structure en trois tuniques : séreuse (péritonéale), musculaire (circulaire interne, longitudinale externe), muqueuse (cellules sécrétrices nourrissant l'ovocyte, cellules ciliées battant vers l'utérus).
- Vascularisation par les artères ovarienne (tiers latéral) et utérine (deux tiers médiaux). Innervation sympathique (T11-L2), parasympathique (vague pour la partie latérale, nerfs splanchniques pelviens S2-S4 pour la partie médiale).

## 5. L'utérus — forme, dimensions et parties
- Organe musculaire creux à paroi épaisse, siège de l'implantation et du développement de l'embryon. Situé obliquement dans le petit bassin entre vessie et rectum ; communique en haut avec les trompes, en bas avec le vagin.
- Piriforme, aplati d'avant en arrière. Dimensions : longueur 7,5-8 cm, largeur (au fond) 5 cm, épaisseur 2,5-3 cm, poids 30-40 g.
- Deux parties principales : le **corps** (2/3 supérieurs) et le **col (cervix)** (1/3 inférieur), séparés par l'**isthme**. Le **fundus** est l'extrémité supérieure convexe du corps, au-dessus du plan des orifices tubaires. Le point de fusion trompe-corps est le **cornu utérin**.
- Le corps présente une surface antérieure (plate, péritonisée jusqu'à l'isthme puis réfléchie sur la vessie en formant le **cul-de-sac vésico-utérin**) et une surface postérieure (convexe, péritoine se prolongeant jusqu'au fornix vaginal postérieur puis réfléchi sur le rectum en formant le **cul-de-sac recto-utérin (de Douglas)**), et deux bords latéraux non péritonisés donnant attache au ligament large, en rapport avec l'artère utérine.
- Le col se divise en portion supravaginale (haute) et portion vaginale (basse, faisant saillie dans le vagin).

## 6. Position, cavité et rapports de l'utérus
- Position normale : **antéversion** (angle d'environ 90° entre l'axe du col et l'axe du vagin) et **antéflexion** (angle d'environ 170° entre l'axe du corps et l'axe du col, au niveau de l'isthme).
- **Rapports antérieurs** : le corps répond au cul-de-sac vésico-utérin et à la face supérieure de la vessie ; le col supravaginal à la face postérieure de la vessie ; le col vaginal au fornix antérieur.
- **Rapports postérieurs** : le corps répond au cul-de-sac recto-utérin (avec anses iléales/sigmoïdiennes) ; le col supravaginal au cul-de-sac recto-utérin et au rectum ; le col vaginal au fornix postérieur.
- **Rapports latéraux** : le corps répond au ligament large et aux vaisseaux utérins ; le col supravaginal à l'uretère et à l'artère utérine ; le col vaginal aux fornix latéraux.
- **Cavité utérine** : cavité du corps (triangulaire en coupe coronale, virtuelle en coupe sagittale) continue en bas, via l'**orifice interne**, avec le canal cervical (fusiforme, plus large au milieu), qui communique en bas, via l'**orifice externe**, avec le vagin. L'**arbor vitae uteri** désigne les plis muqueux obliques (plicae palmatae) du canal cervical.

## 7. Ligaments et moyens de fixité de l'utérus
- **Ligaments faux** (replis péritonéaux, sans rôle de soutien) : ligaments larges (pairs) ; replis recto-utérins (pairs, contenant les ligaments utéro-sacrés) ; repli vésico-utérin (impair, antérieur) ; repli recto-vaginal (impair, postérieur).
- **Ligaments vrais** (fibromusculaires, soutien réel) : **ligaments ronds** (de l'angle utérin, traversent le canal inguinal, se terminent dans le tissu du grand lèvre — tirent le fundus en avant, maintenant l'antéversion/antéflexion) ; **ligaments cervicaux transverses (de Mackenrodt)**, dits ligaments cardinaux, condensation du fascia pelvien autour des vaisseaux utérins — les plus importants ; **ligaments utéro-sacrés** (col → S2-S3, tirent le col en arrière) ; **ligaments pubo-cervicaux**.
- **Soutiens primaires** : musculaires (diaphragme pelvien, corps périnéal, diaphragme urogénital), viscéraux (vessie, vagin), fibromusculaires (les 4 ligaments vrais ci-dessus). **Soutiens secondaires** : ligaments larges, replis vésico-utérin et recto-vaginal.
- Le **corps périnéal** (centre tendineux du périnée) est une masse fibromusculaire pyramidale médiane, à la jonction des triangles urogénital et anal — entre vagin et anus chez la femme, entre bulbe du pénis et anus chez l'homme.

## 8. Le ligament large et sa structure
- Replis péritonéaux allant du bord latéral de l'utérus à la paroi pelvienne, divisant la cavité pelvienne en une partie antérieure (vessie) et une partie postérieure (rectum, anses).
- **Parties** : **mésosalpinx** (entre trompe et ligament propre de l'ovaire) ; **mésomètre** (du plancher pelvien à l'ovaire/ligament propre/corps utérin) ; **mésovarium** ; **ligament infundibulo-pelvien (suspenseur de l'ovaire)**, contenant les vaisseaux ovariens.
- **Contenu** : trompes et ovaires ; ligaments rond et propre de l'ovaire ; artères utérine et ovarienne ; plexus utéro-vaginal et ovarien ; vestiges embryonnaires (épo-oophore/canal de Gartner, para-oophore) ; vaisseaux/nœuds lymphatiques, tissu fibro-aréolaire.

## 9. Vascularisation, drainage et innervation de l'utérus
- **Artère utérine** (branche de la division antérieure de l'iliaque interne) : chemine dans la base du ligament large, croise l'uretère par au-dessus, monte le long de l'utérus et s'anastomose en haut avec l'artère ovarienne. Donne des rameaux urétérique, vaginal, cervical (anastomose circulaire péri-isthmique), des branches arquées transversales sur le corps et des rameaux tubaires/ovariens.
- Veines correspondant aux artères, plexus latéral drainant vers les veines iliaques internes.
- **Lymphatiques** : fundus/corps haut → nœuds pré/para-aortiques (le long des vaisseaux ovariens), quelques vaisseaux vers les nœuds inguinaux superficiels (le long du ligament rond) ; corps bas → nœuds iliaques externes ; col → nœuds iliaques externes/obturateurs (latéralement), iliaques internes (postéro-latéralement), sacrés (postérieurement).
- Innervation : sympathique (T12-L2, contraction/vasoconstriction) et parasympathique (S2-S4, inhibition/vasodilatation). Les afférences douloureuses du corps suivent les voies sympathiques (douleur référée en T12-L2) ; celles du col suivent les nerfs splanchniques pelviens (douleur référée aux dermatomes sacrés).

## 10. Structure de l'utérus et le vagin
- Paroi du corps utérin, de superficiel en profond : **périmétrium** (séreuse péritonéale) ; **myométrium** (couche la plus épaisse, faisceaux de muscle lisse compacts) ; **endomètre** (muqueuse à modifications cycliques). Le col n'est pas tapissé d'endomètre et ne présente pas de cycle.
- Le **vagin** est l'organe de la copulation, partie basse de la filière génitale ; il s'étend du vestibule vulvaire à l'utérus, entre vessie/urètre en avant et rectum/canal anal en arrière.
- Dimensions : paroi antérieure 7,5 cm, paroi postérieure 9 cm ; diamètre croissant de bas (2,5 cm) en haut (5 cm). Le **fornix vaginal** (autour du col) comprend quatre parties (antérieure, postérieure, deux latérales) — le fornix postérieur est ~2 cm plus profond.
- Structure en trois couches : adventice, musculaire lisse (longitudinale externe, circulaire interne), muqueuse (sans glandes ; lubrification par le mucus cervical et les glandes de Bartholin, situées de part et d'autre de l'orifice vaginal). L'**hymen** est un repli muqueux incomplet fermant partiellement l'orifice vaginal.
- Vascularisation par les artères vaginale, vaginale de l'utérine, honteuse interne, rectale moyenne, vésicale inférieure ; drainage veineux par un plexus vers les veines iliaques internes. Innervation : deux tiers supérieurs insensibles au toucher/douleur mais sensibles à l'étirement (sympathique L1-L2, parasympathique S2-S3) ; tiers inférieur très sensible au toucher (nerf honteux).

## 11. Organes génitaux internes masculins — vue d'ensemble
- Comprennent testicules et épididymes, prostate, glandes bulbo-urétrales, vésicules séminales, canaux éjaculateurs, canaux déférents.

## 12. La prostate
- Plus grosse glande annexe de l'appareil reproducteur masculin, de la taille d'une châtaigne, traversée par l'urètre et les canaux éjaculateurs. Située sous le col vésical, au-dessus du sphincter urétral externe ; le releveur de l'anus est inféro-latéral, le rectum est en arrière (ampoule rectale).
- Fonction : sécrétion d'un liquide clair laiteux (~30 % du sperme), alcalin, nourrissant les spermatozoïdes.
- Entourée de deux capsules : vraie (condensation du stroma fibreux glandulaire) et fausse (fascia pelvien condensé).
- Configuration : apex dirigé en bas entre les releveurs de l'anus, reposant sur le fascia du diaphragme urogénital ; base dirigée en haut, entourant le col vésical, traversée par l'urètre près de sa face antérieure. Quatre surfaces : antérieure (étroite, convexe, séparée de la symphyse par l'espace rétropubien/cave de Retzius contenant le plexus veineux prostatique) ; postérieure (large, triangulaire, séparée de l'ampoule rectale par le fascia de Denonvilliers, divisée par un sillon en lobe médian haut et deux lobes latéraux bas, traversée par les canaux éjaculateurs) ; deux surfaces inféro-latérales (en rapport avec le releveur de l'anus).
- **Zones histologiques (classification de McNeal)** : zone centrale (~25 %, entoure les canaux éjaculateurs, peu sujette au reflux urinaire) ; zone de transition (~5-10 %, entoure l'urètre, siège de l'hypertrophie bénigne — HBP) ; zone périphérique (~65 %, principal volume glandulaire, postérieure, palpable au toucher rectal, siège préférentiel du cancer prostatique).

## 13. Vésicules séminales, canaux déférents et éjaculateurs
- **Vésicules séminales** : paire de glandes tubulaires (~5 cm), situées entre le fond vésical et le rectum. Leur canal s'unit au déférent pour former le canal éjaculateur. Fonction : sécrétion d'un liquide alcalin riche en nutriments, ~60 % du volume séminal.
- **Canal déférent** : tube musculaire épais, transporte les spermatozoïdes de l'épididyme au canal éjaculateur. Continue le canal épididymaire, monte en arrière du testicule, traverse le cordon spermatique puis le canal inguinal, entre dans l'abdomen puis le pelvis, passe en arrière de la base de la vessie (en avant de l'ampoule rectale, médialement à la vésicule séminale) et rejoint le canal de la vésicule séminale à la base de la prostate.
- **Canaux éjaculateurs** : deux tubes étroits (~1 cm), formés par l'union du canal de la vésicule séminale et du déférent, traversent la prostate et s'ouvrent dans l'urètre prostatique. Fonction : expulsion des sécrétions testiculaires et vésiculaires dans l'urètre prostatique.

## 14. Testicule et épididyme
- **Testicule** : gonade masculine, homologue de l'ovaire, organe mobile logé dans le scrotum, suspendu par le cordon spermatique. Fonctions : production de spermatozoïdes et sécrétion de testostérone.
- Configuration : deux pôles (supérieur donnant attache au cordon spermatique, inférieur), deux bords (antérieur, postérieur donnant attache à l'épididyme), deux surfaces (médiale, latérale).
- Trois tuniques, de superficiel en profond : **tunique vaginale**, **tunique albuginée**, **tunique vasculaire**.
- **Épididyme** : tube hautement pelotonné reliant le testicule au canal déférent. Fonctions : stockage et maturation des spermatozoïdes, absorption de fluide, addition de substances nourricières au liquide séminal.

## Points à retenir
- L'ovaire est logé dans la fossette ovarienne, relié au ligament large par le mésovarium ; la trompe utérine comprend infundibulum, ampoule (site de fécondation), isthme et portion intra-murale.
- L'utérus, normalement en antéversion-antéflexion, est soutenu par 4 ligaments vrais (ronds, cervicaux transverses/cardinaux, utéro-sacrés, pubo-cervicaux) ; le cul-de-sac de Douglas le sépare du rectum.
- La prostate se divise en 3 zones histologiques (centrale, transition — siège de l'HBP —, périphérique — siège préférentiel du cancer et palpable au toucher rectal).
- Les vésicules séminales et le déférent s'unissent pour former le canal éjaculateur, qui traverse la prostate et s'ouvre dans l'urètre prostatique.`;

export const FEMALE_GENITAL_ORGANS_LEARNING: LibraryLearningSeed = {
  resource: {
    resource_type: "course",
    titre_fr: "Cours condensé — Organes génitaux internes féminins et masculins",
    source_label: "Anatomie — Lecture 12",
    content_fr: FEMALE_GENITAL_ORGANS_COURSE,
  },
  qcm: [
    single("Quelles sont les fonctions principales de l'ovaire ?", "C", "L'ovaire produit les ovocytes et sécrète les stéroïdes sexuels œstrogène et progestérone.", ["Uniquement la production d'ovocytes", "Uniquement la sécrétion hormonale", "La production d'ovocytes et la sécrétion d'œstrogène et de progestérone", "Le transport des spermatozoïdes"]),
    single("Où se situe l'ovaire chez la femme nullipare ?", "B", "Chez la nullipare, l'ovaire est logé dans la fossette ovarienne, sur la paroi pelvienne latérale sous le détroit supérieur.", ["Dans le ligament large uniquement", "Dans la fossette ovarienne, sur la paroi pelvienne latérale", "Dans le cul-de-sac de Douglas", "Accolé à la vessie"]),
    single("Quel repli péritonéal relie l'ovaire au ligament large et sert de hile ?", "A", "Le mésovarium relie l'ovaire à la face postérieure du ligament large et sert de hile pour les vaisseaux et nerfs.", ["Le mésovarium", "Le mésosalpinx", "Le ligament infundibulo-pelvien", "Le ligament propre de l'ovaire"]),
    single("Quel ligament relie l'extrémité inférieure de l'ovaire à l'angle utérin ?", "B", "Le ligament propre de l'ovaire relie l'extrémité inférieure de l'ovaire à l'angle latéral de l'utérus.", ["Le ligament suspenseur de l'ovaire", "Le ligament propre de l'ovaire", "Le ligament rond", "Le ligament infundibulo-pelvien"]),
    single("Quelle est la longueur habituelle de la trompe utérine ?", "C", "La trompe utérine mesure environ 10 cm de long.", ["2 cm", "5 cm", "10 cm", "20 cm"]),
    single("Quelle partie de la trompe utérine est le site habituel de la fécondation ?", "B", "L'ampoule, partie la plus large et la plus longue de la trompe, est le site habituel de fécondation de l'ovocyte.", ["L'infundibulum", "L'ampoule", "L'isthme", "La partie intra-murale"]),
    multi("Quelles sont les quatre parties de la trompe utérine, de latéral à médial ?", ["A", "B", "C", "D"], "De latéral à médial : infundibulum, ampoule, isthme, partie intra-murale (interstitielle).", ["Infundibulum", "Ampoule", "Isthme", "Partie intra-murale"]),
    single("Comment est disposé l'utérus normalement (deux caractéristiques) ?", "A", "L'utérus normal est en antéversion (angle col/vagin ~90°) et antéflexion (angle corps/col ~170°).", ["En antéversion et antéflexion", "En rétroversion et rétroflexion", "En position strictement verticale", "En latéroversion droite"]),
    single("Quelle proportion de l'utérus forme le corps ?", "B", "Le corps forme les deux tiers supérieurs de l'utérus, le col le tiers inférieur.", ["La moitié", "Les deux tiers supérieurs", "Le tiers supérieur", "Les trois quarts"]),
    single("Quel cul-de-sac péritonéal sépare la face postérieure du corps utérin du rectum ?", "C", "Le cul-de-sac recto-utérin (de Douglas) sépare le corps utérin du rectum en arrière.", ["Le cul-de-sac vésico-utérin", "Le cul-de-sac vaginal antérieur", "Le cul-de-sac recto-utérin (de Douglas)", "La fossette ovarienne"]),
    single("Quels sont les ligaments vrais (fibromusculaires) qui soutiennent l'utérus ?", "D", "Les ligaments vrais sont les ligaments ronds, les ligaments cervicaux transverses (cardinaux, de Mackenrodt), les ligaments utéro-sacrés et les ligaments pubo-cervicaux.", ["Uniquement les ligaments larges", "Uniquement les replis vésico-utérin et recto-vaginal", "Uniquement les ligaments ronds", "Ligaments ronds, cervicaux transverses, utéro-sacrés et pubo-cervicaux"]),
    single("Quel est le trajet du ligament rond de l'utérus ?", "B", "Le ligament rond part de l'angle utérin, traverse le canal inguinal, et se termine dans le tissu fibro-aréolaire du grand lèvre.", ["Il relie l'ovaire à l'utérus", "Il traverse le canal inguinal jusqu'au grand lèvre", "Il relie le col utérin au sacrum", "Il forme le hile de l'ovaire"]),
    single("Quels sont les ligaments cervicaux transverses également appelés ligaments cardinaux ?", "A", "Les ligaments cervicaux transverses (de Mackenrodt), formés par condensation du fascia pelvien autour des vaisseaux utérins, sont les ligaments les plus importants de l'utérus.", ["Les ligaments de Mackenrodt", "Les ligaments ronds", "Les ligaments utéro-sacrés", "Les ligaments pubo-cervicaux"]),
    single("Quelle artère vascularise principalement l'utérus ?", "B", "L'artère utérine, branche de la division antérieure de l'artère iliaque interne, est la principale source vasculaire de l'utérus.", ["L'artère ovarienne", "L'artère utérine", "L'artère honteuse interne", "L'artère rectale moyenne"]),
    single("Que croise l'artère utérine près du col utérin ?", "C", "L'artère utérine croise l'uretère par au-dessus, latéralement au col et au fornix vaginal.", ["L'artère ovarienne", "Le ligament rond", "L'uretère", "Le nerf obturateur"]),
    single("Vers quels ganglions drainent principalement le fond et le haut du corps utérin ?", "A", "Le fond et la partie haute du corps drainent principalement vers les nœuds pré- et para-aortiques, le long des vaisseaux ovariens.", ["Les nœuds pré- et para-aortiques", "Les nœuds inguinaux profonds uniquement", "Les nœuds sacrés uniquement", "Les nœuds axillaires"]),
    single("Quelles sont les trois couches de la paroi du corps utérin ?", "C", "De superficiel en profond : périmétrium (séreuse), myométrium (muscle lisse), endomètre (muqueuse cyclique).", ["Adventice, musculeuse, muqueuse", "Séreuse, sous-muqueuse, musculeuse", "Périmétrium, myométrium, endomètre", "Fibreuse, glandulaire, épithéliale"]),
    single("Quelle couche utérine présente des modifications cycliques ?", "B", "L'endomètre, muqueuse la plus interne, subit des modifications cycliques au cours du cycle menstruel.", ["Le périmétrium", "L'endomètre", "Le myométrium", "Le col utérin dans son ensemble"]),
    single("Quelle est la longueur approximative du vagin (paroi postérieure) ?", "C", "La paroi postérieure du vagin mesure environ 9 cm.", ["3 cm", "5 cm", "9 cm", "15 cm"]),
    single("Combien de parties comprend le fornix vaginal ?", "B", "Le fornix vaginal comprend quatre parties : antérieure, postérieure et deux latérales.", ["Deux", "Quatre", "Six", "Une seule, circulaire"]),
    single("Qu'est-ce qui lubrifie normalement la muqueuse vaginale, en l'absence de glandes propres ?", "A", "Le mucus cervical et les sécrétions des glandes de Bartholin lubrifient le vagin, dépourvu de glandes propres.", ["Le mucus cervical et les glandes de Bartholin", "Les glandes vaginales propres", "Le liquide séminal uniquement", "Les glandes urétrales"]),
    single("Quelle glande annexe masculine sécrète un liquide alcalin représentant environ 30 % du sperme ?", "C", "La prostate sécrète un liquide clair alcalin représentant environ 30 % du volume séminal.", ["Les vésicules séminales", "Les glandes bulbo-urétrales", "La prostate", "L'épididyme"]),
    single("Quelle zone histologique de la prostate est le siège principal de l'hypertrophie bénigne (HBP) ?", "B", "La zone de transition, qui entoure l'urètre, est le siège typique de l'hypertrophie bénigne de la prostate.", ["La zone centrale", "La zone de transition", "La zone périphérique", "La capsule fibreuse"]),
    single("Quelle zone prostatique est la plus volumineuse et le siège préférentiel du cancer de la prostate ?", "C", "La zone périphérique (~65 % du volume glandulaire), postérieure et palpable au toucher rectal, est le siège préférentiel du cancer prostatique.", ["La zone centrale", "La zone de transition", "La zone périphérique", "La capsule vraie"]),
    single("Que forme l'union du canal de la vésicule séminale et du canal déférent ?", "A", "Leur union forme le canal éjaculateur, qui traverse la prostate et s'ouvre dans l'urètre prostatique.", ["Le canal éjaculateur", "Le canal épididymaire", "L'urètre prostatique", "Le cordon spermatique"]),
    single("Quelles sont les fonctions de l'épididyme ?", "D", "L'épididyme stocke et fait maturer les spermatozoïdes, absorbe du fluide et ajoute des substances nourricières au liquide séminal.", ["Uniquement la production de spermatozoïdes", "Uniquement la sécrétion de testostérone", "Uniquement le transport rapide des spermatozoïdes", "Le stockage, la maturation des spermatozoïdes et l'enrichissement du liquide séminal"]),
  ],
  exam: { titre_fr: "Examen chronométré — Organes génitaux internes", duration_seconds: 2_100 },
};

export const FEMALE_GENITAL_ORGANS_FLASHCARDS: LibraryCardSeed[] = [
  { question_fr: "Quelles sont les fonctions de l'ovaire ?", question_en: "What are the functions of the ovary?", answer_fr: "Produire les ovocytes et sécréter l'œstrogène et la progestérone.", answer_en: "Producing oocytes and secreting estrogen and progesterone." },
  { question_fr: "Comment s'appelle la dépression péritonéale où loge l'ovaire chez la nullipare ?", question_en: "What is the peritoneal depression where the ovary sits in the nulliparous woman called?", answer_fr: "La fossette ovarienne.", answer_en: "The ovarian fossa." },
  { question_fr: "Quel repli péritonéal relie l'ovaire au ligament large ?", question_en: "Which peritoneal fold connects the ovary to the broad ligament?", answer_fr: "Le mésovarium.", answer_en: "The mesovarium." },
  { question_fr: "Quel ligament relie l'extrémité supérieure de l'ovaire à la paroi pelvienne et contient les vaisseaux ovariens ?", question_en: "Which ligament connects the superior pole of the ovary to the pelvic wall and contains the ovarian vessels?", answer_fr: "Le ligament suspenseur de l'ovaire.", answer_en: "The suspensory ligament of the ovary." },
  { question_fr: "Quel ligament relie l'extrémité inférieure de l'ovaire à l'utérus ?", question_en: "Which ligament connects the inferior pole of the ovary to the uterus?", answer_fr: "Le ligament propre de l'ovaire.", answer_en: "The ligament of the ovary." },
  { question_fr: "Quelles sont les deux couches histologiques de l'ovaire ?", question_en: "What are the two histological layers of the ovary?", answer_fr: "Le cortex (follicules) et la médulla (tissu conjonctif lâche et vaisseaux).", answer_en: "The cortex (follicles) and the medulla (loose connective tissue and vessels)." },
  { question_fr: "D'où naît l'artère ovarienne ?", question_en: "Where does the ovarian artery arise from?", answer_fr: "De l'aorte, au niveau de L1.", answer_en: "From the aorta, at the L1 level." },
  { question_fr: "Où se draine la veine ovarienne droite ? Et la gauche ?", question_en: "Where does the right ovarian vein drain? And the left?", answer_fr: "La droite dans la veine cave inférieure, la gauche dans la veine rénale gauche.", answer_en: "The right into the inferior vena cava, the left into the left renal vein." },
  { question_fr: "Quelle est la longueur de la trompe utérine ?", question_en: "What is the length of the uterine tube?", answer_fr: "Environ 10 cm.", answer_en: "About 10 cm." },
  { question_fr: "Dans quel repli péritonéal chemine la trompe utérine ?", question_en: "In which peritoneal fold does the uterine tube travel?", answer_fr: "Le mésosalpinx.", answer_en: "The mesosalpinx." },
  { question_fr: "Quelle est la partie la plus large et la plus longue de la trompe, site de la fécondation ?", question_en: "What is the widest and longest part of the tube, the site of fertilization?", answer_fr: "L'ampoule.", answer_en: "The ampulla." },
  { question_fr: "Quelle frange de l'infundibulum est appliquée à l'ovaire ?", question_en: "Which fimbria of the infundibulum is applied to the ovary?", answer_fr: "La frange ovarique.", answer_en: "The ovarian fimbria." },
  { question_fr: "Quelle partie de la trompe traverse la paroi utérine ?", question_en: "Which part of the tube traverses the uterine wall?", answer_fr: "La partie intra-murale (interstitielle).", answer_en: "The intramural (interstitial) part." },
  { question_fr: "Quelle est la forme générale de l'utérus ?", question_en: "What is the general shape of the uterus?", answer_fr: "Piriforme, aplati d'avant en arrière.", answer_en: "Pear-shaped, flattened anteroposteriorly." },
  { question_fr: "Quelles sont les deux parties principales de l'utérus ?", question_en: "What are the two main parts of the uterus?", answer_fr: "Le corps (2/3 supérieurs) et le col (1/3 inférieur).", answer_en: "The body (upper two-thirds) and the cervix (lower third)." },
  { question_fr: "Comment appelle-t-on la position normale de l'utérus par rapport au vagin et au col ?", question_en: "What is the normal position of the uterus relative to the vagina and cervix called?", answer_fr: "Antéversion (col/vagin) et antéflexion (corps/col).", answer_en: "Anteversion (cervix/vagina) and anteflexion (body/cervix)." },
  { question_fr: "Quel cul-de-sac péritonéal se forme entre la vessie et l'utérus ?", question_en: "Which peritoneal pouch forms between the bladder and the uterus?", answer_fr: "Le cul-de-sac vésico-utérin.", answer_en: "The vesicouterine pouch." },
  { question_fr: "Quel cul-de-sac péritonéal se forme entre l'utérus et le rectum ?", question_en: "Which peritoneal pouch forms between the uterus and the rectum?", answer_fr: "Le cul-de-sac recto-utérin (de Douglas).", answer_en: "The rectouterine pouch (of Douglas)." },
  { question_fr: "Quel ligament utérin traverse le canal inguinal ?", question_en: "Which uterine ligament traverses the inguinal canal?", answer_fr: "Le ligament rond.", answer_en: "The round ligament." },
  { question_fr: "Comment appelle-t-on aussi les ligaments cervicaux transverses ?", question_en: "What are the transverse cervical ligaments also called?", answer_fr: "Les ligaments cardinaux (ou ligaments de Mackenrodt).", answer_en: "The cardinal ligaments (or Mackenrodt's ligaments)." },
  { question_fr: "Quels ligaments tirent le col utérin en arrière ?", question_en: "Which ligaments pull the cervix backward?", answer_fr: "Les ligaments utéro-sacrés.", answer_en: "The uterosacral ligaments." },
  { question_fr: "Nommez les parties du ligament large.", question_en: "Name the parts of the broad ligament.", answer_fr: "Le mésosalpinx, le mésomètre, le mésovarium, et le ligament infundibulo-pelvien.", answer_en: "The mesosalpinx, the mesometrium, the mesovarium, and the infundibulopelvic ligament." },
  { question_fr: "Quelle artère est la principale source de vascularisation de l'utérus ?", question_en: "Which artery is the main blood supply to the uterus?", answer_fr: "L'artère utérine.", answer_en: "The uterine artery." },
  { question_fr: "Quelle structure l'artère utérine croise-t-elle près du col ?", question_en: "What structure does the uterine artery cross near the cervix?", answer_fr: "L'uretère.", answer_en: "The ureter." },
  { question_fr: "Quelles sont les trois couches de la paroi du corps utérin, de superficiel en profond ?", question_en: "What are the three layers of the uterine body wall, from outer to inner?", answer_fr: "Périmétrium, myométrium, endomètre.", answer_en: "Perimetrium, myometrium, endometrium." },
  { question_fr: "Quelle couche utérine est la plus épaisse ?", question_en: "Which uterine layer is the thickest?", answer_fr: "Le myométrium.", answer_en: "The myometrium." },
  { question_fr: "Quelle est la longueur de la paroi antérieure du vagin ?", question_en: "What is the length of the anterior vaginal wall?", answer_fr: "Environ 7,5 cm.", answer_en: "About 7.5 cm." },
  { question_fr: "Combien de parties compte le fornix vaginal, et laquelle est la plus profonde ?", question_en: "How many parts does the vaginal fornix have, and which is the deepest?", answer_fr: "Quatre parties (antérieure, postérieure, deux latérales) ; le fornix postérieur est le plus profond.", answer_en: "Four parts (anterior, posterior, two lateral); the posterior fornix is the deepest." },
  { question_fr: "Quelles glandes lubrifient l'orifice vaginal ?", question_en: "Which glands lubricate the vaginal orifice?", answer_fr: "Les glandes de Bartholin.", answer_en: "Bartholin's glands." },
  { question_fr: "Qu'est-ce que l'hymen ?", question_en: "What is the hymen?", answer_fr: "Un repli muqueux incomplet fermant partiellement l'orifice vaginal.", answer_en: "An incomplete mucosal fold partially closing the vaginal orifice." },
  { question_fr: "Nommez les organes génitaux internes masculins.", question_en: "Name the male internal genital organs.", answer_fr: "Testicules et épididymes, prostate, glandes bulbo-urétrales, vésicules séminales, canaux éjaculateurs, canaux déférents.", answer_en: "Testes and epididymis, prostate, bulbourethral glands, seminal vesicles, ejaculatory ducts, vasa deferentia." },
  { question_fr: "Quelle proportion du sperme est sécrétée par la prostate ?", question_en: "What proportion of semen is secreted by the prostate?", answer_fr: "Environ 30 %.", answer_en: "About 30%." },
  { question_fr: "Quel fascia sépare la face postérieure de la prostate de l'ampoule rectale ?", question_en: "Which fascia separates the posterior surface of the prostate from the rectal ampulla?", answer_fr: "Le fascia de Denonvilliers.", answer_en: "The fascia of Denonvilliers." },
  { question_fr: "Nommez les trois zones histologiques de la prostate (classification de McNeal).", question_en: "Name the three histological zones of the prostate (McNeal classification).", answer_fr: "La zone centrale, la zone de transition et la zone périphérique.", answer_en: "The central zone, the transition zone, and the peripheral zone." },
  { question_fr: "Quelle zone prostatique est le siège de l'hypertrophie bénigne (HBP) ?", question_en: "Which prostatic zone is the site of benign hyperplasia (BPH)?", answer_fr: "La zone de transition.", answer_en: "The transition zone." },
  { question_fr: "Quelle zone prostatique est palpable au toucher rectal et siège préférentiel du cancer ?", question_en: "Which prostatic zone is palpable on rectal exam and the preferential site of cancer?", answer_fr: "La zone périphérique.", answer_en: "The peripheral zone." },
  { question_fr: "Quelle proportion du liquide séminal proviennent des vésicules séminales ?", question_en: "What proportion of seminal fluid comes from the seminal vesicles?", answer_fr: "Environ 60 %.", answer_en: "About 60%." },
  { question_fr: "Que forme l'union du canal de la vésicule séminale et du canal déférent ?", question_en: "What is formed by the union of the seminal vesicle duct and the vas deferens?", answer_fr: "Le canal éjaculateur.", answer_en: "The ejaculatory duct." },
  { question_fr: "Où s'ouvrent les canaux éjaculateurs ?", question_en: "Where do the ejaculatory ducts open?", answer_fr: "Dans l'urètre prostatique.", answer_en: "Into the prostatic urethra." },
  { question_fr: "Quel trajet suit le canal déférent depuis l'épididyme ?", question_en: "What path does the vas deferens follow from the epididymis?", answer_fr: "Il monte en arrière du testicule, traverse le cordon spermatique puis le canal inguinal, entre dans l'abdomen puis le pelvis.", answer_en: "It ascends behind the testis, passes through the spermatic cord then the inguinal canal, entering the abdomen and then the pelvis." },
  { question_fr: "Quelles sont les fonctions du testicule ?", question_en: "What are the functions of the testis?", answer_fr: "Production de spermatozoïdes et sécrétion de testostérone.", answer_en: "Production of spermatozoa and secretion of testosterone." },
  { question_fr: "Nommez les trois tuniques du testicule, de superficiel en profond.", question_en: "Name the three coverings of the testis, from outer to inner.", answer_fr: "Tunique vaginale, tunique albuginée, tunique vasculaire.", answer_en: "Tunica vaginalis, tunica albuginea, tunica vasculosa." },
  { question_fr: "Quelles sont les fonctions de l'épididyme ?", question_en: "What are the functions of the epididymis?", answer_fr: "Stockage et maturation des spermatozoïdes, absorption de fluide, enrichissement du liquide séminal.", answer_en: "Storage and maturation of spermatozoa, fluid absorption, and enrichment of seminal fluid." },
];
