import type { LibraryChapterSeed } from "./biochimie-s1.js";
import {
  GENERAL_ANATOMY_LEARNING,
  GENERAL_ANATOMY_FLASHCARDS,
  EMBRYOLOGY_LEARNING,
  EMBRYOLOGY_FLASHCARDS,
  UPPER_LIMB_MUSCLES_JOINTS_1_LEARNING,
  UPPER_LIMB_MUSCLES_JOINTS_1_FLASHCARDS,
} from "./anatomie-s1-lot1.js";
import {
  UPPER_LIMB_MUSCLES_2_LEARNING,
  UPPER_LIMB_MUSCLES_2_FLASHCARDS,
  UPPER_LIMB_VESSELS_NERVES_LEARNING,
  UPPER_LIMB_VESSELS_NERVES_FLASHCARDS,
  LOWER_LIMB_MUSCLES_LEARNING,
  LOWER_LIMB_MUSCLES_FLASHCARDS,
} from "./anatomie-s1-lot2.js";
import {
  LOWER_LIMB_JOINTS_LEARNING,
  LOWER_LIMB_JOINTS_FLASHCARDS,
  LOWER_LIMB_VESSELS_NERVES_LEARNING,
  LOWER_LIMB_VESSELS_NERVES_FLASHCARDS,
  ABDOMINAL_WALL_LEARNING,
  ABDOMINAL_WALL_FLASHCARDS,
} from "./anatomie-s1-lot3.js";
import {
  PERITONEUM_LEARNING,
  PERITONEUM_FLASHCARDS,
  DUODENUM_PANCREAS_LEARNING,
  DUODENUM_PANCREAS_FLASHCARDS,
  STOMACH_SPLEEN_LIVER_LEARNING,
  STOMACH_SPLEEN_LIVER_FLASHCARDS,
} from "./anatomie-s1-lot4.js";
import {
  RECTUM_LEARNING,
  RECTUM_FLASHCARDS,
  KIDNEY_URETER_BLADDER_URETHRA_LEARNING,
  KIDNEY_URETER_BLADDER_URETHRA_FLASHCARDS,
  FEMALE_GENITAL_ORGANS_LEARNING,
  FEMALE_GENITAL_ORGANS_FLASHCARDS,
} from "./anatomie-s1-lot5.js";

// Contenu officiel pré-rédigé : Anatomie, Année 1, Semestre 1.
// Cours magistraux reels (diaporamas .pptx) fournis par l'utilisatrice --
// membre superieur, membre inferieur, puis paroi abdominale et organes
// abdomino-pelviens.
export const ANATOMIE_S1: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Anatomie generale",
    titre_en: "General Anatomy",
    description_fr: "Terminologie, plans et axes anatomiques, notions fondamentales d'anatomie descriptive",
    description_en: "Terminology, anatomical planes and axes, fundamental concepts of descriptive anatomy",
    icone: "🦴",
    learning: GENERAL_ANATOMY_LEARNING,
    cards: GENERAL_ANATOMY_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Embryologie humaine generale",
    titre_en: "Human General Embryology",
    description_fr: "Fecondation, segmentation, gastrulation et formation des feuillets embryonnaires",
    description_en: "Fertilization, cleavage, gastrulation, and formation of the embryonic layers",
    icone: "🧬",
    learning: EMBRYOLOGY_LEARNING,
    cards: EMBRYOLOGY_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Muscles et articulations du membre superieur",
    titre_en: "Muscles and Joints of the Upper Limb",
    description_fr: "Organisation musculaire et articulaire de l'epaule, du bras, de l'avant-bras et de la main",
    description_en: "Muscular and articular organization of the shoulder, arm, forearm, and hand",
    icone: "💪",
    learning: UPPER_LIMB_MUSCLES_JOINTS_1_LEARNING,
    cards: UPPER_LIMB_MUSCLES_JOINTS_1_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Muscles du membre superieur (suite)",
    titre_en: "Muscles of the Upper Limb (Continuation)",
    description_fr: "Suite de l'etude des muscles du membre superieur",
    description_en: "Continuation of the study of the upper limb muscles",
    icone: "💪",
    learning: UPPER_LIMB_MUSCLES_2_LEARNING,
    cards: UPPER_LIMB_MUSCLES_2_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Arteres, veines et nerfs du membre superieur",
    titre_en: "Arteries, Veins, and Nerves of the Upper Limb",
    description_fr: "Vascularisation arterielle et veineuse et innervation du membre superieur",
    description_en: "Arterial and venous vascularization and innervation of the upper limb",
    icone: "🩸",
    learning: UPPER_LIMB_VESSELS_NERVES_LEARNING,
    cards: UPPER_LIMB_VESSELS_NERVES_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Muscles du membre inferieur",
    titre_en: "Muscles of the Lower Limb",
    description_fr: "Organisation musculaire de la hanche, de la cuisse, de la jambe et du pied",
    description_en: "Muscular organization of the hip, thigh, leg, and foot",
    icone: "🦵",
    learning: LOWER_LIMB_MUSCLES_LEARNING,
    cards: LOWER_LIMB_MUSCLES_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Articulations du membre inferieur (suite)",
    titre_en: "Joints of the Lower Limb (Continuation)",
    description_fr: "Hanche, genou, cheville et articulations du pied",
    description_en: "Hip, knee, ankle, and joints of the foot",
    icone: "🦵",
    learning: LOWER_LIMB_JOINTS_LEARNING,
    cards: LOWER_LIMB_JOINTS_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Arteres, veines et nerfs du membre inferieur",
    titre_en: "Arteries, Veins, and Nerves of the Lower Limb",
    description_fr: "Vascularisation arterielle et veineuse et innervation du membre inferieur",
    description_en: "Arterial and venous vascularization and innervation of the lower limb",
    icone: "🩸",
    learning: LOWER_LIMB_VESSELS_NERVES_LEARNING,
    cards: LOWER_LIMB_VESSELS_NERVES_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Paroi abdominale antero-laterale",
    titre_en: "Anterior and Lateral Abdominal Wall",
    description_fr: "Couches et muscles de la paroi abdominale antero-laterale",
    description_en: "Layers and muscles of the anterior and lateral abdominal wall",
    icone: "🧱",
    learning: ABDOMINAL_WALL_LEARNING,
    cards: ABDOMINAL_WALL_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Peritoine",
    titre_en: "Peritoneum",
    description_fr: "Organisation du peritoine, cavites et replis peritoneaux",
    description_en: "Organization of the peritoneum, peritoneal cavities and folds",
    icone: "🫁",
    learning: PERITONEUM_LEARNING,
    cards: PERITONEUM_FLASHCARDS,
  },
  {
    ordre: 11,
    titre_fr: "Duodenum et pancreas",
    titre_en: "Duodenum and Pancreas",
    description_fr: "Anatomie descriptive et rapports du duodenum et du pancreas",
    description_en: "Descriptive anatomy and relations of the duodenum and pancreas",
    icone: "🫘",
    learning: DUODENUM_PANCREAS_LEARNING,
    cards: DUODENUM_PANCREAS_FLASHCARDS,
  },
  {
    ordre: 12,
    titre_fr: "Estomac, rate et foie",
    titre_en: "Stomach, Spleen, and Liver",
    description_fr: "Anatomie descriptive et rapports de l'estomac, de la rate et du foie",
    description_en: "Descriptive anatomy and relations of the stomach, spleen, and liver",
    icone: "🫀",
    learning: STOMACH_SPLEEN_LIVER_LEARNING,
    cards: STOMACH_SPLEEN_LIVER_FLASHCARDS,
  },
  {
    ordre: 13,
    titre_fr: "Rectum",
    titre_en: "The Rectum",
    description_fr: "Anatomie descriptive et rapports du rectum",
    description_en: "Descriptive anatomy and relations of the rectum",
    icone: "🔽",
    learning: RECTUM_LEARNING,
    cards: RECTUM_FLASHCARDS,
  },
  {
    ordre: 14,
    titre_fr: "Rein, uretere, vessie et uretre",
    titre_en: "Kidney, Ureter, Urinary Bladder, and Urethra",
    description_fr: "Anatomie descriptive de l'appareil urinaire",
    description_en: "Descriptive anatomy of the urinary apparatus",
    icone: "💧",
    learning: KIDNEY_URETER_BLADDER_URETHRA_LEARNING,
    cards: KIDNEY_URETER_BLADDER_URETHRA_FLASHCARDS,
  },
  {
    ordre: 15,
    titre_fr: "Organes genitaux internes (feminins et masculins)",
    titre_en: "Internal Genital Organs (Female and Male)",
    description_fr: "Anatomie descriptive des organes genitaux internes feminins et masculins",
    description_en: "Descriptive anatomy of the female and male internal genital organs",
    icone: "🌸",
    learning: FEMALE_GENITAL_ORGANS_LEARNING,
    cards: FEMALE_GENITAL_ORGANS_FLASHCARDS,
  },
];
