import type { LibraryChapterSeed } from "./biochimie-s1.js";
import {
  GLYCOLYSIS_LEARNING,
  GLYCOLYSIS_FLASHCARDS,
  GLYCOLYSIS_REGULATION_LEARNING,
  GLYCOLYSIS_REGULATION_FLASHCARDS,
  TRANSITION_STAGE_LEARNING,
  TRANSITION_STAGE_FLASHCARDS,
  TRANSITION_STAGE_REGULATION_LEARNING,
  TRANSITION_STAGE_REGULATION_FLASHCARDS,
  KREBS_CYCLE_LEARNING,
  KREBS_CYCLE_FLASHCARDS,
} from "./biochimie-s2-glycolyse.js";
import {
  ETC_OVERVIEW_LEARNING,
  ETC_OVERVIEW_FLASHCARDS,
  ETC_COMPLEX_I_LEARNING,
  ETC_COMPLEX_I_FLASHCARDS,
  ETC_COMPLEX_II_III_LEARNING,
  ETC_COMPLEX_II_III_FLASHCARDS,
  ETC_COMPLEX_IV_ATP_SYNTHASE_LEARNING,
  ETC_COMPLEX_IV_ATP_SYNTHASE_FLASHCARDS,
  GLYCOGENESIS_LEARNING,
  GLYCOGENESIS_FLASHCARDS,
} from "./biochimie-s2-etc.js";

// Contenu officiel pré-rédigé : Biochimie, Année 1, Semestre 2.
// Synthèse de la playlist "Metabolism" de Ninja Nerd (31 vidéos), reformulée
// en cours condensés + flashcards détaillées + QCM, un chapitre par vidéo,
// dans l'ordre de la playlist. Déployé par lots successifs.
export const BIOCHIMIE_S2: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Glycolyse",
    titre_en: "Glycolysis",
    description_fr: "Les 10 étapes enzymatiques de la glycolyse, phase d'investissement et phase de rendement énergétique",
    description_en: "The 10 enzymatic steps of glycolysis, energy investment and energy payoff phases",
    icone: "🍬",
    learning: GLYCOLYSIS_LEARNING,
    cards: GLYCOLYSIS_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Régulation de la glycolyse",
    titre_en: "Regulation of Glycolysis",
    description_fr: "Contrôle allostérique et hormonal de l'hexokinase, de la PFK-1 et de la pyruvate kinase",
    description_en: "Allosteric and hormonal control of hexokinase, PFK-1 and pyruvate kinase",
    icone: "🎛️",
    learning: GLYCOLYSIS_REGULATION_LEARNING,
    cards: GLYCOLYSIS_REGULATION_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Stade de transition (phase préparatoire)",
    titre_en: "Transition Stage (Preparatory Phase)",
    description_fr: "Décarboxylation oxydative du pyruvate en acétyl-CoA par le complexe pyruvate déshydrogénase",
    description_en: "Oxidative decarboxylation of pyruvate into acetyl-CoA by the pyruvate dehydrogenase complex",
    icone: "🔀",
    learning: TRANSITION_STAGE_LEARNING,
    cards: TRANSITION_STAGE_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Régulation du stade de transition",
    titre_en: "Regulation of the Transition Stage",
    description_fr: "Contrôle du complexe pyruvate déshydrogénase par phosphorylation et par les ratios ATP/ADP, NADH/NAD+, acétyl-CoA/CoA",
    description_en: "Control of the pyruvate dehydrogenase complex by phosphorylation and by ATP/ADP, NADH/NAD+, acetyl-CoA/CoA ratios",
    icone: "🎛️",
    learning: TRANSITION_STAGE_REGULATION_LEARNING,
    cards: TRANSITION_STAGE_REGULATION_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Le cycle de Krebs",
    titre_en: "The Krebs Cycle",
    description_fr: "Les 8 réactions du cycle de l'acide citrique, production de NADH, FADH2 et GTP/ATP",
    description_en: "The 8 reactions of the citric acid cycle, production of NADH, FADH2 and GTP/ATP",
    icone: "🔄",
    learning: KREBS_CYCLE_LEARNING,
    cards: KREBS_CYCLE_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Chaîne de transport des électrons — Vue d'ensemble",
    titre_en: "Electron Transport Chain — Overview",
    description_fr: "Les complexes I à V, le gradient de protons, la phosphorylation oxydative et les principaux inhibiteurs",
    description_en: "Complexes I to V, the proton gradient, oxidative phosphorylation, and key inhibitors",
    icone: "⚡",
    learning: ETC_OVERVIEW_LEARNING,
    cards: ETC_OVERVIEW_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Chaîne de transport des électrons (1) — Le complexe I",
    titre_en: "Electron Transport Chain (1) — Complex I",
    description_fr: "Mécanisme du complexe I, FMN, centres fer-soufre, pompage de protons et production de radicaux libres",
    description_en: "Complex I mechanism, FMN, iron-sulfur centers, proton pumping, and free radical production",
    icone: "🔋",
    learning: ETC_COMPLEX_I_LEARNING,
    cards: ETC_COMPLEX_I_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Chaîne de transport des électrons (2) — Les complexes II et III",
    titre_en: "Electron Transport Chain (2) — Complexes II and III",
    description_fr: "Succinate déshydrogénase, cycle Q, protéine de Rieske et cytochromes",
    description_en: "Succinate dehydrogenase, the Q cycle, the Rieske protein, and cytochromes",
    icone: "🔌",
    learning: ETC_COMPLEX_II_III_LEARNING,
    cards: ETC_COMPLEX_II_III_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Chaîne de transport des électrons (3) — Le complexe IV et l'ATP synthase",
    titre_en: "Electron Transport Chain (3) — Complex IV and ATP Synthase",
    description_fr: "Cytochrome c oxydase, réduction de l'O2 en eau, et mécanisme rotatif de l'ATP synthase",
    description_en: "Cytochrome c oxidase, O2 reduction to water, and the rotary mechanism of ATP synthase",
    icone: "⚙️",
    learning: ETC_COMPLEX_IV_ATP_SYNTHASE_LEARNING,
    cards: ETC_COMPLEX_IV_ATP_SYNTHASE_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Glycogénogenèse",
    titre_en: "Glycogenesis",
    description_fr: "Synthèse du glycogène : UDP-glucose, glycogène synthase, enzyme branchante et glycogénine",
    description_en: "Glycogen synthesis: UDP-glucose, glycogen synthase, the branching enzyme, and glycogenin",
    icone: "🧵",
    learning: GLYCOGENESIS_LEARNING,
    cards: GLYCOGENESIS_FLASHCARDS,
  },
];
