import type { LibraryChapterSeed } from "./biochimie-s1.js";
import {
  GLYCOLYSIS_LEARNING,
  GLYCOLYSIS_FLASHCARDS,
  GLYCOLYSIS_REGULATION_LEARNING,
  GLYCOLYSIS_REGULATION_FLASHCARDS,
  TRANSITION_STAGE_LEARNING,
  TRANSITION_STAGE_FLASHCARDS,
  TRANSITION_STAGE_REGULATION_LEARNING,
  TRANSITION_STAGE_REGULATION_FLASHCARDS,
  KREBS_CYCLE_LEARNING,
  KREBS_CYCLE_FLASHCARDS,
} from "./biochimie-s2-glycolyse.js";
import { LAB_S2_1_LEARNING, LAB_S2_2_LEARNING, LAB_S2_3_LEARNING } from "./biochimie-s2-labo-1-2-3.js";
import { LAB_S2_4_LEARNING, LAB_S2_5_LEARNING, LAB_S2_67_LEARNING } from "./biochimie-s2-labo-4-5-67.js";
import { LAB_S2_8_LEARNING, LAB_S2_9_LEARNING, LAB_S2_10_LEARNING } from "./biochimie-s2-labo-8-9-10.js";
import { LAB_S2_11_LEARNING, LAB_S2_12_LEARNING, LAB_S2_13_LEARNING } from "./biochimie-s2-labo-11-12-13.js";
import {
  ETC_OVERVIEW_LEARNING,
  ETC_OVERVIEW_FLASHCARDS,
  ETC_COMPLEX_I_LEARNING,
  ETC_COMPLEX_I_FLASHCARDS,
  ETC_COMPLEX_II_III_LEARNING,
  ETC_COMPLEX_II_III_FLASHCARDS,
  ETC_COMPLEX_IV_ATP_SYNTHASE_LEARNING,
  ETC_COMPLEX_IV_ATP_SYNTHASE_FLASHCARDS,
  GLYCOGENESIS_LEARNING,
  GLYCOGENESIS_FLASHCARDS,
} from "./biochimie-s2-etc.js";
import {
  GLYCOGENOLYSIS_LEARNING,
  GLYCOGENOLYSIS_FLASHCARDS,
  GLYCOGEN_METABOLISM_REGULATION_LEARNING,
  GLYCOGEN_METABOLISM_REGULATION_FLASHCARDS,
} from "./biochimie-s2-glycogenolyse.js";
import {
  GLUCONEOGENESIS_LEARNING,
  GLUCONEOGENESIS_FLASHCARDS,
  GLUCONEOGENESIS_REGULATION_LEARNING,
  GLUCONEOGENESIS_REGULATION_FLASHCARDS,
  FATTY_ACID_SYNTHESIS_1_LEARNING,
  FATTY_ACID_SYNTHESIS_1_FLASHCARDS,
} from "./biochimie-s2-neoglucogenese.js";
import {
  FATTY_ACID_SYNTHESIS_2_LEARNING,
  FATTY_ACID_SYNTHESIS_2_FLASHCARDS,
  TRIGLYCERIDE_SYNTHESIS_LEARNING,
  TRIGLYCERIDE_SYNTHESIS_FLASHCARDS,
} from "./biochimie-s2-fa-synthesis2.js";
import {
  TRIGLYCERIDE_MOBILIZATION_LEARNING,
  TRIGLYCERIDE_MOBILIZATION_FLASHCARDS,
  FATTY_ACID_OXIDATION_1_LEARNING,
  FATTY_ACID_OXIDATION_1_FLASHCARDS,
  FATTY_ACID_OXIDATION_2_LEARNING,
  FATTY_ACID_OXIDATION_2_FLASHCARDS,
} from "./biochimie-s2-lipolyse-oxydation.js";
import {
  AMINO_ACID_METABOLISM_LEARNING,
  AMINO_ACID_METABOLISM_FLASHCARDS,
  UREA_CYCLE_LEARNING,
  UREA_CYCLE_FLASHCARDS,
} from "./biochimie-s2-acides-amines-uree.js";
import {
  KETONE_METABOLISM_LEARNING,
  KETONE_METABOLISM_FLASHCARDS,
  PENTOSE_PHOSPHATE_PATHWAY_LEARNING,
  PENTOSE_PHOSPHATE_PATHWAY_FLASHCARDS,
  PPP_REGULATION_LEARNING,
  PPP_REGULATION_FLASHCARDS,
} from "./biochimie-s2-cetones-ppp.js";
import {
  METABOLIC_MAP_CARBS_LEARNING,
  METABOLIC_MAP_CARBS_FLASHCARDS,
  METABOLIC_MAP_LIPIDS_LEARNING,
  METABOLIC_MAP_LIPIDS_FLASHCARDS,
  METABOLIC_MAP_PROTEINS_LEARNING,
  METABOLIC_MAP_PROTEINS_FLASHCARDS,
} from "./biochimie-s2-cartes-metaboliques.js";
import {
  CHOLESTEROL_METABOLISM_LEARNING,
  CHOLESTEROL_METABOLISM_FLASHCARDS,
  LIPOPROTEIN_METABOLISM_LEARNING,
  LIPOPROTEIN_METABOLISM_FLASHCARDS,
} from "./biochimie-s2-cholesterol-lipoproteines.js";
import {
  NUCLEOTIDE_SYNTHESIS_LEARNING,
  NUCLEOTIDE_SYNTHESIS_FLASHCARDS,
} from "./biochimie-s2-nucleotides.js";

// Contenu officiel pré-rédigé : Biochimie, Année 1, Semestre 2.
// Synthèse de la playlist "Metabolism" de Ninja Nerd (31 vidéos), reformulée
// en cours condensés + flashcards détaillées + QCM, un chapitre par vidéo,
// dans l'ordre de la playlist. Déployé par lots successifs.
export const BIOCHIMIE_S2: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Glycolyse",
    titre_en: "Glycolysis",
    description_fr: "Les 10 étapes enzymatiques de la glycolyse, phase d'investissement et phase de rendement énergétique",
    description_en: "The 10 enzymatic steps of glycolysis, energy investment and energy payoff phases",
    icone: "🍬",
    learning: GLYCOLYSIS_LEARNING,
    cards: GLYCOLYSIS_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Régulation de la glycolyse",
    titre_en: "Regulation of Glycolysis",
    description_fr: "Contrôle allostérique et hormonal de l'hexokinase, de la PFK-1 et de la pyruvate kinase",
    description_en: "Allosteric and hormonal control of hexokinase, PFK-1 and pyruvate kinase",
    icone: "🎛️",
    learning: GLYCOLYSIS_REGULATION_LEARNING,
    cards: GLYCOLYSIS_REGULATION_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Stade de transition (phase préparatoire)",
    titre_en: "Transition Stage (Preparatory Phase)",
    description_fr: "Décarboxylation oxydative du pyruvate en acétyl-CoA par le complexe pyruvate déshydrogénase",
    description_en: "Oxidative decarboxylation of pyruvate into acetyl-CoA by the pyruvate dehydrogenase complex",
    icone: "🔀",
    learning: TRANSITION_STAGE_LEARNING,
    cards: TRANSITION_STAGE_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Régulation du stade de transition",
    titre_en: "Regulation of the Transition Stage",
    description_fr: "Contrôle du complexe pyruvate déshydrogénase par phosphorylation et par les ratios ATP/ADP, NADH/NAD+, acétyl-CoA/CoA",
    description_en: "Control of the pyruvate dehydrogenase complex by phosphorylation and by ATP/ADP, NADH/NAD+, acetyl-CoA/CoA ratios",
    icone: "🎛️",
    learning: TRANSITION_STAGE_REGULATION_LEARNING,
    cards: TRANSITION_STAGE_REGULATION_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Le cycle de Krebs",
    titre_en: "The Krebs Cycle",
    description_fr: "Les 8 réactions du cycle de l'acide citrique, production de NADH, FADH2 et GTP/ATP",
    description_en: "The 8 reactions of the citric acid cycle, production of NADH, FADH2 and GTP/ATP",
    icone: "🔄",
    learning: KREBS_CYCLE_LEARNING,
    widget_key: "krebs-cycle",
    cards: KREBS_CYCLE_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Chaîne de transport des électrons — Vue d'ensemble",
    titre_en: "Electron Transport Chain — Overview",
    description_fr: "Les complexes I à V, le gradient de protons, la phosphorylation oxydative et les principaux inhibiteurs",
    description_en: "Complexes I to V, the proton gradient, oxidative phosphorylation, and key inhibitors",
    icone: "⚡",
    learning: ETC_OVERVIEW_LEARNING,
    cards: ETC_OVERVIEW_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Chaîne de transport des électrons (1) — Le complexe I",
    titre_en: "Electron Transport Chain (1) — Complex I",
    description_fr: "Mécanisme du complexe I, FMN, centres fer-soufre, pompage de protons et production de radicaux libres",
    description_en: "Complex I mechanism, FMN, iron-sulfur centers, proton pumping, and free radical production",
    icone: "🔋",
    learning: ETC_COMPLEX_I_LEARNING,
    cards: ETC_COMPLEX_I_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Chaîne de transport des électrons (2) — Les complexes II et III",
    titre_en: "Electron Transport Chain (2) — Complexes II and III",
    description_fr: "Succinate déshydrogénase, cycle Q, protéine de Rieske et cytochromes",
    description_en: "Succinate dehydrogenase, the Q cycle, the Rieske protein, and cytochromes",
    icone: "🔌",
    learning: ETC_COMPLEX_II_III_LEARNING,
    cards: ETC_COMPLEX_II_III_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Chaîne de transport des électrons (3) — Le complexe IV et l'ATP synthase",
    titre_en: "Electron Transport Chain (3) — Complex IV and ATP Synthase",
    description_fr: "Cytochrome c oxydase, réduction de l'O2 en eau, et mécanisme rotatif de l'ATP synthase",
    description_en: "Cytochrome c oxidase, O2 reduction to water, and the rotary mechanism of ATP synthase",
    icone: "⚙️",
    learning: ETC_COMPLEX_IV_ATP_SYNTHASE_LEARNING,
    cards: ETC_COMPLEX_IV_ATP_SYNTHASE_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Glycogénogenèse",
    titre_en: "Glycogenesis",
    description_fr: "Synthèse du glycogène : UDP-glucose, glycogène synthase, enzyme branchante et glycogénine",
    description_en: "Glycogen synthesis: UDP-glucose, glycogen synthase, the branching enzyme, and glycogenin",
    icone: "🧵",
    learning: GLYCOGENESIS_LEARNING,
    cards: GLYCOGENESIS_FLASHCARDS,
  },
  {
    ordre: 11,
    titre_fr: "Glycogénolyse",
    titre_en: "Glycogenolysis",
    description_fr: "Dégradation du glycogène : glycogène phosphorylase, enzyme débranchante et devenir tissulaire du glucose-6-phosphate",
    description_en: "Glycogen breakdown: glycogen phosphorylase, the debranching enzyme, and the tissue fate of glucose-6-phosphate",
    icone: "🧶",
    learning: GLYCOGENOLYSIS_LEARNING,
    cards: GLYCOGENOLYSIS_FLASHCARDS,
  },
  {
    ordre: 12,
    titre_fr: "Régulation du métabolisme du glycogène",
    titre_en: "Regulation of Glycogen Metabolism",
    description_fr: "Cascade hormonale glucagon/adrénaline, rôle du calcium musculaire et régulation croisée synthase/phosphorylase",
    description_en: "Glucagon/adrenaline hormonal cascade, the role of muscle calcium, and cross-regulation of synthase/phosphorylase",
    icone: "🎚️",
    learning: GLYCOGEN_METABOLISM_REGULATION_LEARNING,
    cards: GLYCOGEN_METABOLISM_REGULATION_FLASHCARDS,
  },
  {
    ordre: 13,
    titre_fr: "Néoglucogenèse",
    titre_en: "Gluconeogenesis",
    description_fr: "Synthèse du glucose à partir du lactate, de l'alanine et du glycérol, en contournant les étapes irréversibles de la glycolyse",
    description_en: "Glucose synthesis from lactate, alanine, and glycerol, bypassing the irreversible steps of glycolysis",
    icone: "🏗️",
    learning: GLUCONEOGENESIS_LEARNING,
    cards: GLUCONEOGENESIS_FLASHCARDS,
  },
  {
    ordre: 14,
    titre_fr: "Régulation de la néoglucogenèse",
    titre_en: "Regulation of Gluconeogenesis",
    description_fr: "Contrôle de la pyruvate carboxylase, de la PEPCK et de la FBPase-1, et rôle croisé du fructose-2,6-bisphosphate",
    description_en: "Control of pyruvate carboxylase, PEPCK, and FBPase-1, and the cross-regulatory role of fructose-2,6-bisphosphate",
    icone: "🎛️",
    learning: GLUCONEOGENESIS_REGULATION_LEARNING,
    cards: GLUCONEOGENESIS_REGULATION_FLASHCARDS,
  },
  {
    ordre: 15,
    titre_fr: "Synthèse des acides gras (1)",
    titre_en: "Fatty Acid Synthesis (1)",
    description_fr: "Navette du citrate, acétyl-CoA carboxylase et complexe acide gras synthase",
    description_en: "The citrate shuttle, acetyl-CoA carboxylase, and the fatty acid synthase complex",
    icone: "🫧",
    learning: FATTY_ACID_SYNTHESIS_1_LEARNING,
    cards: FATTY_ACID_SYNTHESIS_1_FLASHCARDS,
  },
  {
    ordre: 16,
    titre_fr: "Synthèse des acides gras (2)",
    titre_en: "Fatty Acid Synthesis (2)",
    description_fr: "Le cycle d'élongation du complexe FAS, la formation du palmitate, l'élongation et la désaturation ultérieures",
    description_en: "The FAS elongation cycle, palmitate formation, and further elongation and desaturation",
    icone: "🔗",
    learning: FATTY_ACID_SYNTHESIS_2_LEARNING,
    cards: FATTY_ACID_SYNTHESIS_2_FLASHCARDS,
  },
  {
    ordre: 17,
    titre_fr: "Synthèse des triglycérides",
    titre_en: "Triglyceride Synthesis",
    description_fr: "Voie du glycérol phosphate : GPAT, AGPAT, phosphatase et DGAT, et devenir des triglycérides synthétisés",
    description_en: "The glycerol phosphate pathway: GPAT, AGPAT, phosphatase, and DGAT, and the fate of synthesized triglycerides",
    icone: "💧",
    learning: TRIGLYCERIDE_SYNTHESIS_LEARNING,
    cards: TRIGLYCERIDE_SYNTHESIS_FLASHCARDS,
  },
  {
    ordre: 18,
    titre_fr: "Mobilisation des triglycérides",
    titre_en: "Mobilization of Triglycerides",
    description_fr: "La cascade lipolytique ATGL-HSL-MGL, la régulation hormonale et le devenir des acides gras et du glycérol libérés",
    description_en: "The ATGL-HSL-MGL lipolytic cascade, hormonal regulation, and the fate of released fatty acids and glycerol",
    icone: "💦",
    learning: TRIGLYCERIDE_MOBILIZATION_LEARNING,
    cards: TRIGLYCERIDE_MOBILIZATION_FLASHCARDS,
  },
  {
    ordre: 19,
    titre_fr: "Oxydation des acides gras (1)",
    titre_en: "Fatty Acid Oxidation (1)",
    description_fr: "Activation cytosolique, navette de la carnitine (CPT1/CPT2) et cycle de la β-oxydation",
    description_en: "Cytosolic activation, the carnitine shuttle (CPT1/CPT2), and the beta-oxidation cycle",
    icone: "🔥",
    learning: FATTY_ACID_OXIDATION_1_LEARNING,
    cards: FATTY_ACID_OXIDATION_1_FLASHCARDS,
  },
  {
    ordre: 20,
    titre_fr: "Oxydation des acides gras (2)",
    titre_en: "Fatty Acid Oxidation (2)",
    description_fr: "Bilan énergétique du palmitate, acides gras à nombre impair de carbones, régulation et corrélations cliniques",
    description_en: "Palmitate's energy balance, odd-chain fatty acids, regulation, and clinical correlations",
    icone: "⚗️",
    learning: FATTY_ACID_OXIDATION_2_LEARNING,
    cards: FATTY_ACID_OXIDATION_2_FLASHCARDS,
  },
  {
    ordre: 21,
    titre_fr: "Métabolisme des acides aminés",
    titre_en: "Amino Acid Metabolism",
    description_fr: "Transamination, désamination oxydative, et classification glucoformatrice/cétogène des acides aminés",
    description_en: "Transamination, oxidative deamination, and the glucogenic/ketogenic classification of amino acids",
    icone: "🧬",
    learning: AMINO_ACID_METABOLISM_LEARNING,
    cards: AMINO_ACID_METABOLISM_FLASHCARDS,
  },
  {
    ordre: 22,
    titre_fr: "Le cycle de l'urée",
    titre_en: "Urea Cycle",
    description_fr: "Détoxification de l'ammoniac en urée, les 5 réactions du cycle hépatique et les hyperammoniémies",
    description_en: "Detoxification of ammonia into urea, the 5 reactions of the hepatic cycle, and hyperammonemias",
    icone: "🚽",
    learning: UREA_CYCLE_LEARNING,
    cards: UREA_CYCLE_FLASHCARDS,
  },
  {
    ordre: 23,
    titre_fr: "Métabolisme des corps cétoniques",
    titre_en: "Ketone Metabolism",
    description_fr: "Cétogenèse hépatique, cétolyse périphérique, et acidocétose diabétique",
    description_en: "Hepatic ketogenesis, peripheral ketolysis, and diabetic ketoacidosis",
    icone: "🍊",
    learning: KETONE_METABOLISM_LEARNING,
    cards: KETONE_METABOLISM_FLASHCARDS,
  },
  {
    ordre: 24,
    titre_fr: "La voie des pentoses phosphates",
    titre_en: "Pentose Phosphate Pathway",
    description_fr: "Phase oxydative et non oxydative, production de NADPH et de ribose-5-phosphate",
    description_en: "Oxidative and non-oxidative phases, NADPH and ribose-5-phosphate production",
    icone: "🧪",
    learning: PENTOSE_PHOSPHATE_PATHWAY_LEARNING,
    cards: PENTOSE_PHOSPHATE_PATHWAY_FLASHCARDS,
  },
  {
    ordre: 25,
    titre_fr: "Régulation de la voie des pentoses phosphates",
    titre_en: "Regulation of the Pentose Phosphate Pathway",
    description_fr: "Contrôle de la G6PD, flexibilité NADPH/ribose-5-phosphate, et déficit en G6PD",
    description_en: "Control of G6PD, NADPH/ribose-5-phosphate flexibility, and G6PD deficiency",
    icone: "🩸",
    learning: PPP_REGULATION_LEARNING,
    cards: PPP_REGULATION_FLASHCARDS,
  },
  {
    ordre: 26,
    titre_fr: "Carte métabolique — Glucides",
    titre_en: "Metabolic Map — Carbohydrates",
    description_fr: "Synthèse intégrée : glucose-6-phosphate et pyruvate, carrefours centraux du métabolisme glucidique",
    description_en: "Integrated synthesis: glucose-6-phosphate and pyruvate, the central crossroads of carbohydrate metabolism",
    icone: "🗺️",
    learning: METABOLIC_MAP_CARBS_LEARNING,
    cards: METABOLIC_MAP_CARBS_FLASHCARDS,
  },
  {
    ordre: 27,
    titre_fr: "Carte métabolique — Lipides",
    titre_en: "Metabolic Map — Lipids",
    description_fr: "Synthèse intégrée : le malonyl-CoA comme interrupteur central entre lipogenèse et β-oxydation",
    description_en: "Integrated synthesis: malonyl-CoA as the central switch between lipogenesis and beta-oxidation",
    icone: "🗺️",
    learning: METABOLIC_MAP_LIPIDS_LEARNING,
    cards: METABOLIC_MAP_LIPIDS_FLASHCARDS,
  },
  {
    ordre: 28,
    titre_fr: "Carte métabolique — Protéines",
    titre_en: "Metabolic Map — Proteins",
    description_fr: "Synthèse intégrée : le glutamate et le fumarate, carrefours entre catabolisme azoté et cycle de Krebs",
    description_en: "Integrated synthesis: glutamate and fumarate, crossroads between nitrogen catabolism and the Krebs cycle",
    icone: "🗺️",
    learning: METABOLIC_MAP_PROTEINS_LEARNING,
    cards: METABOLIC_MAP_PROTEINS_FLASHCARDS,
  },
  {
    ordre: 29,
    titre_fr: "Métabolisme du cholestérol",
    titre_en: "Cholesterol Metabolism",
    description_fr: "Synthèse hépatique via la HMG-CoA réductase, régulation par SREBP-2, et devenirs biologiques du cholestérol",
    description_en: "Hepatic synthesis via HMG-CoA reductase, SREBP-2 regulation, and the biological fates of cholesterol",
    icone: "🥚",
    learning: CHOLESTEROL_METABOLISM_LEARNING,
    cards: CHOLESTEROL_METABOLISM_FLASHCARDS,
  },
  {
    ordre: 30,
    titre_fr: "Métabolisme des lipoprotéines",
    titre_en: "Lipoprotein Metabolism",
    description_fr: "Voies exogène et endogène (chylomicrons, VLDL, LDL) et transport inverse du cholestérol par les HDL",
    description_en: "Exogenous and endogenous pathways (chylomicrons, VLDL, LDL) and reverse cholesterol transport by HDL",
    icone: "🚚",
    learning: LIPOPROTEIN_METABOLISM_LEARNING,
    cards: LIPOPROTEIN_METABOLISM_FLASHCARDS,
  },
  {
    ordre: 31,
    titre_fr: "Synthèse des nucléotides",
    titre_en: "Nucleotide Synthesis",
    description_fr: "Voies de novo des purines et pyrimidines, formation des désoxyribonucléotides, et syndromes de Lesch-Nyhan et de déficit en ADA",
    description_en: "De novo purine and pyrimidine pathways, deoxyribonucleotide formation, and Lesch-Nyhan and ADA deficiency syndromes",
    icone: "🧬",
    learning: NUCLEOTIDE_SYNTHESIS_LEARNING,
    cards: NUCLEOTIDE_SYNTHESIS_FLASHCARDS,
  },

  // Chapitres de laboratoire (section "laboratoire"), notes officielles
  // "Biochimie II" (Lab 1 à Lab 13, labo 6&7 combiné dans le document
  // source). L'ordre part de 101 pour ne jamais entrer en collision avec
  // les chapitres de cours (ordre 1-31).
  {
    ordre: 101,
    section: "laboratoire",
    titre_fr: "Métabolisme des glucides — Glycémie et HGPO",
    titre_en: "Carbohydrate Metabolism — Blood Glucose and OGTT",
    description_fr: "Dosage du glucose dans les liquides biologiques et test de tolérance au glucose oral",
    description_en: "Determination of glucose in biological fluids and the oral glucose tolerance test",
    icone: "🩸",
    learning: LAB_S2_1_LEARNING,
    cards: [],
  },
  {
    ordre: 102,
    section: "laboratoire",
    titre_fr: "Métabolisme des glucides — Régulation et HbA1c",
    titre_en: "Carbohydrate Metabolism — Regulation and HbA1c",
    description_fr: "Régulation hormonale de la glycémie et dosage de l'hémoglobine glyquée",
    description_en: "Hormonal regulation of glycemia and determination of glycated hemoglobin",
    icone: "🍬",
    learning: LAB_S2_2_LEARNING,
    cards: [],
  },
  {
    ordre: 103,
    section: "laboratoire",
    titre_fr: "Métabolisme des lipides — Triglycérides et corps cétoniques",
    titre_en: "Lipid Metabolism — Triglycerides and Ketone Bodies",
    description_fr: "Dosage des triglycérides et identification des corps cétoniques dans l'urine",
    description_en: "Determination of triglycerides and identification of ketone bodies in urine",
    icone: "🍟",
    learning: LAB_S2_3_LEARNING,
    cards: [],
  },
  {
    ordre: 104,
    section: "laboratoire",
    titre_fr: "Métabolisme des lipides — Lipoprotéines et cholestérol",
    titre_en: "Lipid Metabolism — Lipoproteins and Cholesterol",
    description_fr: "Lipoprotéines plasmatiques et dosage du cholestérol total et HDL",
    description_en: "Plasma lipoproteins and determination of total and HDL cholesterol",
    icone: "🥚",
    learning: LAB_S2_4_LEARNING,
    cards: [],
  },
  {
    ordre: 105,
    section: "laboratoire",
    titre_fr: "Métabolisme minéral — pH et capacité tampon",
    titre_en: "Mineral Metabolism — pH and Buffering Capacity",
    description_fr: "Dosage du pH, capacité tampon sérique et dosage des ions dans les liquides biologiques",
    description_en: "pH determination, serum buffering capacity, and determination of ions in biological fluids",
    icone: "⚖️",
    learning: LAB_S2_5_LEARNING,
    cards: [],
  },
  {
    ordre: 106,
    section: "laboratoire",
    titre_fr: "Métabolisme des protéines — Acides aminés (Lab 6-7)",
    titre_en: "Protein Metabolism — Amino Acids (Lab 6-7)",
    description_fr: "Métabolisme des acides aminés et identification des désordres associés",
    description_en: "Amino acid metabolism and identification of amino acid metabolism disorders",
    icone: "🧬",
    learning: LAB_S2_67_LEARNING,
    cards: [],
  },
  {
    ordre: 107,
    section: "laboratoire",
    titre_fr: "Métabolisme des protéines — Transaminases",
    titre_en: "Protein Metabolism — Transaminases",
    description_fr: "Dosage des transaminases ALAT/ASAT et corrélations cliniques",
    description_en: "Determination of ALT/AST transaminases and clinical correlations",
    icone: "🧪",
    learning: LAB_S2_8_LEARNING,
    cards: [],
  },
  {
    ordre: 108,
    section: "laboratoire",
    titre_fr: "Métabolisme des protéines — Urée",
    titre_en: "Protein Metabolism — Urea",
    description_fr: "Métabolisme de l'ammoniac, cycle de l'urée et dosage de l'urée sanguine",
    description_en: "Ammonia metabolism, the urea cycle, and blood urea determination",
    icone: "🚽",
    learning: LAB_S2_9_LEARNING,
    cards: [],
  },
  {
    ordre: 109,
    section: "laboratoire",
    titre_fr: "Métabolisme des protéines — Créatinine",
    titre_en: "Protein Metabolism — Creatinine",
    description_fr: "Dosage de la créatinine sérique et urinaire et clairance rénale",
    description_en: "Determination of serum and urinary creatinine and renal clearance",
    icone: "🫘",
    learning: LAB_S2_10_LEARNING,
    cards: [],
  },
  {
    ordre: 110,
    section: "laboratoire",
    titre_fr: "Métabolisme des protéines — Hémoglobine et bilirubine",
    titre_en: "Protein Metabolism — Hemoglobin and Bilirubin",
    description_fr: "Dosage de l'hémoglobine et de la bilirubine, catabolisme de l'hème et ictères",
    description_en: "Determination of hemoglobin and bilirubin, heme catabolism, and jaundice",
    icone: "🩸",
    learning: LAB_S2_11_LEARNING,
    cards: [],
  },
  {
    ordre: 111,
    section: "laboratoire",
    titre_fr: "Métabolisme des acides nucléiques — Acide urique",
    titre_en: "Nucleic Acid Metabolism — Uric Acid",
    description_fr: "Catabolisme des purines et dosage de l'acide urique",
    description_en: "Purine catabolism and determination of uric acid",
    icone: "🧬",
    learning: LAB_S2_12_LEARNING,
    cards: [],
  },
  {
    ordre: 112,
    section: "laboratoire",
    titre_fr: "Analyse métabolique intégrative — Piccolo Xpress",
    titre_en: "Integrative Metabolic Analysis — Piccolo Xpress",
    description_fr: "Détermination de paramètres biochimiques avec le système automatique Piccolo Xpress",
    description_en: "Determination of biochemical parameters using the Piccolo Xpress automatic system",
    icone: "🔬",
    learning: LAB_S2_13_LEARNING,
    cards: [],
  },
];
