import type { LibraryChapterSeed } from "./biochimie-s1.js";
import {
  CELL_MEMBRANE_LEARNING,
  CELL_MEMBRANE_FLASHCARDS,
  RECEPTORS_SIGNALING_LEARNING,
  RECEPTORS_SIGNALING_FLASHCARDS,
  NEURON_PHYSIOLOGY_LEARNING,
  NEURON_PHYSIOLOGY_FLASHCARDS,
  MUSCLE_PHYSIOLOGY_LEARNING,
  MUSCLE_PHYSIOLOGY_FLASHCARDS,
} from "./physiologie-generale.js";
import {
  RED_BLOOD_CELLS_LEARNING,
  RED_BLOOD_CELLS_FLASHCARDS,
  HEMATOPOIESIS_LEUKOCYTES_LEARNING,
  HEMATOPOIESIS_LEUKOCYTES_FLASHCARDS,
  HEMOSTASIS_LEARNING,
  HEMOSTASIS_FLASHCARDS,
} from "./physiologie-sang.js";
import {
  RENAL_FILTRATION_LEARNING,
  RENAL_FILTRATION_FLASHCARDS,
  TUBULAR_FUNCTIONS_LEARNING,
  TUBULAR_FUNCTIONS_FLASHCARDS,
  RENAL_EXCRETION_LEARNING,
  RENAL_EXCRETION_FLASHCARDS,
  RENAL_REGULATION_LEARNING,
  RENAL_REGULATION_FLASHCARDS,
} from "./physiologie-renal.js";
import {
  DIGESTIVE_SECRETION_LEARNING,
  DIGESTIVE_SECRETION_FLASHCARDS,
  DIGESTION_ABSORPTION_LEARNING,
  DIGESTION_ABSORPTION_FLASHCARDS,
  GI_MOTILITY_LEARNING,
  GI_MOTILITY_FLASHCARDS,
} from "./physiologie-digestif.js";

// Contenu officiel pré-rédigé : Physiologie, Année 1, Semestre 1.
// Extrait des cours magistraux (UMFT "V. Babes" Timisoara, Department of
// Functional Sciences) fournis par l'utilisatrice — un chapitre par lecture,
// regroupé par grand systeme physiologique (general -> sang -> renal -> digestif).
export const PHYSIOLOGIE_S1: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Physiologie de la membrane cellulaire",
    titre_en: "Cell Membrane Physiology",
    description_fr: "Mecanismes de transport passif et actif a travers la membrane cellulaire",
    description_en: "Passive and active transport mechanisms across the cell membrane",
    icone: "🧫",
    learning: CELL_MEMBRANE_LEARNING,
    cards: CELL_MEMBRANE_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Recepteurs et signalisation intracellulaire",
    titre_en: "Receptors and Intracellular Signaling",
    description_fr: "Recepteurs membranaires, seconds messagers et role des boucles de retroaction",
    description_en: "Membrane receptors, second messengers, and the role of feedback loops",
    icone: "🔗",
    learning: RECEPTORS_SIGNALING_LEARNING,
    cards: RECEPTORS_SIGNALING_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Physiologie du neurone",
    titre_en: "Neuron Physiology",
    description_fr: "Potentiels membranaires et conduction de l'influx dans les fibres nerveuses",
    description_en: "Membrane potentials and conduction through nerve fibers",
    icone: "⚡",
    learning: NEURON_PHYSIOLOGY_LEARNING,
    cards: NEURON_PHYSIOLOGY_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Physiologie du muscle lisse et strie",
    titre_en: "Smooth and Striated Muscle Physiology",
    description_fr: "Mecanismes de contraction et particularites fonctionnelles des muscles lisse et strie",
    description_en: "Contraction mechanisms and functional particularities of smooth and striated muscle",
    icone: "💪",
    learning: MUSCLE_PHYSIOLOGY_LEARNING,
    cards: MUSCLE_PHYSIOLOGY_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Milieu interieur et globules rouges",
    titre_en: "Internal Environment and Red Blood Cells",
    description_fr: "Composition du milieu interieur et physiologie des globules rouges",
    description_en: "Composition of the internal environment and red blood cell physiology",
    icone: "🩸",
    learning: RED_BLOOD_CELLS_LEARNING,
    cards: RED_BLOOD_CELLS_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Volemie, hematopoiese et leucocytes",
    titre_en: "Volemia, Hematopoiesis, and Leukocytes",
    description_fr: "Regulation de la volemie, hematopoiese et role des leucocytes dans la defense de l'organisme",
    description_en: "Volemia regulation, hematopoiesis, and the role of leukocytes in the body's defense",
    icone: "🛡️",
    learning: HEMATOPOIESIS_LEUKOCYTES_LEARNING,
    cards: HEMATOPOIESIS_LEUKOCYTES_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Hemostase physiologique",
    titre_en: "Physiological Hemostasis",
    description_fr: "Hemostase primaire, coagulation et fibrinolyse",
    description_en: "Primary hemostasis, coagulation, and fibrinolysis",
    icone: "🩹",
    learning: HEMOSTASIS_LEARNING,
    cards: HEMOSTASIS_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Organisation du rein et filtration glomerulaire",
    titre_en: "Kidney Organization and Glomerular Filtration",
    description_fr: "Organisation fonctionnelle du rein, circulation renale et filtration glomerulaire",
    description_en: "Functional organization of the kidney, renal circulation, and glomerular filtration",
    icone: "🫘",
    learning: RENAL_FILTRATION_LEARNING,
    cards: RENAL_FILTRATION_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Fonctions tubulaires",
    titre_en: "Tubular Functions",
    description_fr: "Mecanismes generaux du transport tubulaire et physiologie du tube contourne proximal",
    description_en: "General mechanisms of tubular transport and physiology of the proximal convoluted tubule",
    icone: "🧪",
    learning: TUBULAR_FUNCTIONS_LEARNING,
    cards: TUBULAR_FUNCTIONS_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Excretion renale et epargne plasmatique",
    titre_en: "Renal Excretion and Plasma Sparing",
    description_fr: "Epargne et excretion renale des principaux composants plasmatiques",
    description_en: "Renal sparing and excretion of the main plasma components",
    icone: "💧",
    learning: RENAL_EXCRETION_LEARNING,
    cards: RENAL_EXCRETION_FLASHCARDS,
  },
  {
    ordre: 11,
    titre_fr: "Regulation de la fonction renale et miction",
    titre_en: "Regulation of Renal Function and Micturition",
    description_fr: "Controle nerveux et hormonal du rein, accumulation et evacuation de l'urine",
    description_en: "Nervous and hormonal control of the kidney, urine accumulation and evacuation",
    icone: "🚽",
    learning: RENAL_REGULATION_LEARNING,
    cards: RENAL_REGULATION_FLASHCARDS,
  },
  {
    ordre: 12,
    titre_fr: "Fonction secretoire du tube digestif",
    titre_en: "Secretory Function of the Digestive Tract",
    description_fr: "Secretions salivaire, gastrique, pancreatique et biliaire",
    description_en: "Salivary, gastric, pancreatic, and biliary secretions",
    icone: "🦷",
    learning: DIGESTIVE_SECRETION_LEARNING,
    cards: DIGESTIVE_SECRETION_FLASHCARDS,
  },
  {
    ordre: 13,
    titre_fr: "Digestion et absorption des principes nutritifs",
    titre_en: "Digestion and Absorption of Nutrients",
    description_fr: "Digestion et absorption des glucides, lipides et proteines",
    description_en: "Digestion and absorption of carbohydrates, lipids, and proteins",
    icone: "🍽️",
    learning: DIGESTION_ABSORPTION_LEARNING,
    cards: DIGESTION_ABSORPTION_FLASHCARDS,
  },
  {
    ordre: 14,
    titre_fr: "Motilite gastro-intestinale",
    titre_en: "Gastrointestinal Motility",
    description_fr: "Particularites du muscle lisse visceral et motilite des differents segments digestifs",
    description_en: "Particularities of visceral smooth muscle and motility of the digestive segments",
    icone: "🌀",
    learning: GI_MOTILITY_LEARNING,
    cards: GI_MOTILITY_FLASHCARDS,
  },
];
