import type { LibraryChapterSeed } from "./biochimie-s1.js";
import {
  CARDIAC_MEMBRANE_POTENTIAL_LEARNING,
  CARDIAC_MEMBRANE_POTENTIAL_FLASHCARDS,
  EXCITO_CONDUCTORY_SYSTEM_LEARNING,
  EXCITO_CONDUCTORY_SYSTEM_FLASHCARDS,
  ECG_PHYSIOLOGY_LEARNING,
  ECG_PHYSIOLOGY_FLASHCARDS,
  HEART_CONTRACTILITY_LEARNING,
  HEART_CONTRACTILITY_FLASHCARDS,
} from "./physiologie-cardio-1.js";
import {
  CARDIAC_CYCLE_OUTPUT_LEARNING,
  CARDIAC_CYCLE_OUTPUT_FLASHCARDS,
  HEMODYNAMICS_CIRCULATION_LEARNING,
  HEMODYNAMICS_CIRCULATION_FLASHCARDS,
  CV_NERVOUS_REGULATION_LEARNING,
  CV_NERVOUS_REGULATION_FLASHCARDS,
  CV_REGULATION_2_LEARNING,
  CV_REGULATION_2_FLASHCARDS,
} from "./physiologie-cardio-2.js";
import {
  RESPIRATORY_MECHANICS_LEARNING,
  RESPIRATORY_MECHANICS_FLASHCARDS,
  PULMONARY_VENTILATION_LEARNING,
  PULMONARY_VENTILATION_FLASHCARDS,
  VENTILATION_REGULATION_LEARNING,
  VENTILATION_REGULATION_FLASHCARDS,
} from "./physiologie-respiratoire.js";
import {
  HYPOTHALAMUS_PITUITARY_THYROID_LEARNING,
  HYPOTHALAMUS_PITUITARY_THYROID_FLASHCARDS,
  ADRENAL_SEXUAL_HORMONES_LEARNING,
  ADRENAL_SEXUAL_HORMONES_FLASHCARDS,
  PANCREAS_BONE_CALCIUM_LEARNING,
  PANCREAS_BONE_CALCIUM_FLASHCARDS,
} from "./physiologie-endocrine.js";

// Contenu officiel pré-rédigé : Physiologie, Année 1, Semestre 2.
// Cours magistraux reels (Physiology Department) fournis par l'utilisatrice --
// cardiovasculaire (8 lectures), respiratoire (3) et endocrinien (3).
export const PHYSIOLOGIE_S2: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Potentiel membranaire des fibres cardiaques",
    titre_en: "Membrane Potential of Cardiac Fibers",
    description_fr: "Introduction au systeme cardiovasculaire, potentiel de repos et potentiel d'action des fibres cardiaques",
    description_en: "Introduction to the cardiovascular system, resting and action membrane potential of cardiac fibers",
    icone: "🫀",
    learning: CARDIAC_MEMBRANE_POTENTIAL_LEARNING,
    cards: CARDIAC_MEMBRANE_POTENTIAL_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Systeme excito-conducteur cardiaque",
    titre_en: "Cardiac Excito-Conductory System",
    description_fr: "Excitabilite et conductibilite cardiaques, physiologie du systeme excito-conducteur",
    description_en: "Cardiac excitability and conductibility, physiology of the excito-conductory system",
    icone: "⚡",
    learning: EXCITO_CONDUCTORY_SYSTEM_LEARNING,
    cards: EXCITO_CONDUCTORY_SYSTEM_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Bases physiologiques de l'electrocardiogramme",
    titre_en: "Physiological Basis of the Electrocardiogram",
    description_fr: "Enregistrement et caracteristiques de l'ECG normal",
    description_en: "Recording and characteristics of the normal ECG",
    icone: "📈",
    learning: ECG_PHYSIOLOGY_LEARNING,
    cards: ECG_PHYSIOLOGY_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Contractilite cardiaque",
    titre_en: "Heart Contractility",
    description_fr: "Relation force-vitesse, mecanisme de Frank-Starling, precharge, postcharge et inotropisme",
    description_en: "Force-velocity relationship, Frank-Starling mechanism, preload, afterload, and inotropism",
    icone: "💪",
    learning: HEART_CONTRACTILITY_LEARNING,
    cards: HEART_CONTRACTILITY_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Cycle cardiaque et debit cardiaque",
    titre_en: "Cardiac Cycle and Cardiac Output",
    description_fr: "Cycle cardiaque, bruits du coeur, debit cardiaque et physiologie de la circulation coronaire",
    description_en: "Cardiac cycle, heart sounds, cardiac output, and coronary circulation physiology",
    icone: "🔄",
    learning: CARDIAC_CYCLE_OUTPUT_LEARNING,
    cards: CARDIAC_CYCLE_OUTPUT_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Hemodynamique et circulation peripherique",
    titre_en: "Hemodynamics and Peripheral Circulation",
    description_fr: "Parametres hemodynamiques, circulation arterielle, microcirculation, circulation veineuse et lymphatique",
    description_en: "Hemodynamic parameters, arterial circulation, microcirculation, venous and lymphatic circulation",
    icone: "🩸",
    learning: HEMODYNAMICS_CIRCULATION_LEARNING,
    cards: HEMODYNAMICS_CIRCULATION_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Regulation nerveuse de la fonction cardiovasculaire",
    titre_en: "Nervous Regulation of Cardiovascular Function",
    description_fr: "Centres bulbaires et protuberantiels, regulation nerveuse du coeur et des vaisseaux",
    description_en: "Medullary and pontine centers, nervous regulation of the heart and vessels",
    icone: "🧠",
    learning: CV_NERVOUS_REGULATION_LEARNING,
    cards: CV_NERVOUS_REGULATION_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Regulation cardiovasculaire (2) — autoregulation et endothelium",
    titre_en: "Cardiovascular Regulation (2) — Autoregulation and Endothelium",
    description_fr: "Autoregulation myogenique et regulation par l'endothelium vasculaire",
    description_en: "Myogenic autoregulation and vascular endothelium-mediated regulation",
    icone: "🎛️",
    learning: CV_REGULATION_2_LEARNING,
    cards: CV_REGULATION_2_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Mecanique respiratoire et volumes pulmonaires",
    titre_en: "Respiratory Mechanics and Pulmonary Volumes",
    description_fr: "Organisation fonctionnelle du systeme respiratoire, mecanique ventilatoire, volumes et capacites pulmonaires",
    description_en: "Functional organization of the respiratory system, ventilatory mechanics, pulmonary volumes and capacities",
    icone: "🫁",
    learning: RESPIRATORY_MECHANICS_LEARNING,
    cards: RESPIRATORY_MECHANICS_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Physiologie de la ventilation pulmonaire",
    titre_en: "Physiology of Pulmonary Ventilation",
    description_fr: "Debits ventilatoires et rapport ventilation/perfusion",
    description_en: "Ventilatory flows and the ventilation/perfusion ratio",
    icone: "💨",
    learning: PULMONARY_VENTILATION_LEARNING,
    cards: PULMONARY_VENTILATION_FLASHCARDS,
  },
  {
    ordre: 11,
    titre_fr: "Regulation de la ventilation",
    titre_en: "Regulation of Ventilation",
    description_fr: "Centres nerveux de la ventilation et regulation du tonus broncho-moteur",
    description_en: "Nervous centers of ventilation and regulation of bronchomotor tone",
    icone: "🎚️",
    learning: VENTILATION_REGULATION_LEARNING,
    cards: VENTILATION_REGULATION_FLASHCARDS,
  },
  {
    ordre: 12,
    titre_fr: "Hypothalamus endocrinien, hypophyse et thyroide",
    titre_en: "Endocrine Hypothalamus, Pituitary, and Thyroid",
    description_fr: "Hypothalamus endocrinien, hormones hypophysaires et hormones thyroidiennes",
    description_en: "Endocrine hypothalamus, pituitary hormones, and thyroid hormones",
    icone: "🦋",
    learning: HYPOTHALAMUS_PITUITARY_THYROID_LEARNING,
    cards: HYPOTHALAMUS_PITUITARY_THYROID_FLASHCARDS,
  },
  {
    ordre: 13,
    titre_fr: "Hormones surrenaliennes et sexuelles",
    titre_en: "Adrenal and Sexual Hormones",
    description_fr: "Hormones du cortex et de la medulla surrenale, hormones sexuelles",
    description_en: "Adrenal cortex and medulla hormones, sexual hormones",
    icone: "⚙️",
    learning: ADRENAL_SEXUAL_HORMONES_LEARNING,
    cards: ADRENAL_SEXUAL_HORMONES_FLASHCARDS,
  },
  {
    ordre: 14,
    titre_fr: "Pancreas endocrine et homeostasie phosphocalcique",
    titre_en: "Endocrine Pancreas and Phosphate-Calcium Homeostasis",
    description_fr: "Pancreas endocrine, physiologie osseuse et hormones de l'homeostasie phosphocalcique",
    description_en: "Endocrine pancreas, bone physiology, and hormones of phosphate-calcium homeostasis",
    icone: "🦴",
    learning: PANCREAS_BONE_CALCIUM_LEARNING,
    cards: PANCREAS_BONE_CALCIUM_FLASHCARDS,
  },
];
