import type { LibraryChapterSeed, LibraryLearningSeed, LibraryCardSeed } from "./biochimie-s1.js";
import {
  CELL_MEMBRANE_LEARNING,
  CELL_MEMBRANE_FLASHCARDS,
  RECEPTORS_SIGNALING_LEARNING,
  RECEPTORS_SIGNALING_FLASHCARDS,
  NEURON_PHYSIOLOGY_LEARNING,
  NEURON_PHYSIOLOGY_FLASHCARDS,
  MUSCLE_PHYSIOLOGY_LEARNING,
  MUSCLE_PHYSIOLOGY_FLASHCARDS,
} from "./physiologie-generale.js";
import {
  RED_BLOOD_CELLS_LEARNING,
  RED_BLOOD_CELLS_FLASHCARDS,
  HEMATOPOIESIS_LEUKOCYTES_LEARNING,
  HEMATOPOIESIS_LEUKOCYTES_FLASHCARDS,
  HEMOSTASIS_LEARNING,
  HEMOSTASIS_FLASHCARDS,
} from "./physiologie-sang.js";
import {
  RENAL_FILTRATION_LEARNING,
  RENAL_FILTRATION_FLASHCARDS,
  TUBULAR_FUNCTIONS_LEARNING,
  TUBULAR_FUNCTIONS_FLASHCARDS,
  RENAL_EXCRETION_LEARNING,
  RENAL_EXCRETION_FLASHCARDS,
  RENAL_REGULATION_LEARNING,
  RENAL_REGULATION_FLASHCARDS,
} from "./physiologie-renal.js";
import {
  DIGESTIVE_SECRETION_LEARNING,
  DIGESTIVE_SECRETION_FLASHCARDS,
  DIGESTION_ABSORPTION_LEARNING,
  DIGESTION_ABSORPTION_FLASHCARDS,
  GI_MOTILITY_LEARNING,
  GI_MOTILITY_FLASHCARDS,
} from "./physiologie-digestif.js";
import {
  OSMOLARITY_LEARNING,
  OSMOLARITY_FLASHCARDS,
  IONOGRAMME_LEARNING,
  IONOGRAMME_FLASHCARDS,
  HEMATOGRAMME_LEARNING,
  HEMATOGRAMME_FLASHCARDS,
} from "./physiologie-labo-s1-lotA.js";
import {
  ABB_LEARNING,
  ABB_FLASHCARDS,
  HEMOSTASIS_PARTIAL_LEARNING,
  HEMOSTASIS_PARTIAL_FLASHCARDS,
} from "./physiologie-labo-s1-lotB.js";
import {
  PROTEINOGRAM_LEARNING,
  PROTEINOGRAM_FLASHCARDS,
  URINE_FORMULA_LEARNING as URINE_FORMULA_LEARNING_1_8,
  URINE_FORMULA_FLASHCARDS as URINE_FORMULA_FLASHCARDS_1_8,
} from "./physiologie-labo-s1-lotC.js";
import {
  LEUKOGRAM_LEARNING,
  LEUKOGRAM_FLASHCARDS,
  URINE_FORMULA_LEARNING as URINE_FORMULA_LEARNING_9_10,
  URINE_FORMULA_FLASHCARDS as URINE_FORMULA_FLASHCARDS_9_10,
  ANEMIA_DIFFERENTIAL_LEARNING,
  ANEMIA_DIFFERENTIAL_FLASHCARDS,
} from "./physiologie-labo-s1-lotD.js";
import {
  REFERENCE_VALUES_LEARNING,
  REFERENCE_VALUES_FLASHCARDS,
  INTERPRETATION_PATTERNS_LEARNING,
  INTERPRETATION_PATTERNS_FLASHCARDS,
} from "./physiologie-labo-s1-lotE.js";

// Le quiz "Formule Urine" (10 questions) a ete capture en deux morceaux
// (Q1-8 dans le lot C, Q9-10 dans le lot D) : on les fusionne en un seul
// chapitre de laboratoire.
const URINE_FORMULA_LEARNING: LibraryLearningSeed = {
  resource: URINE_FORMULA_LEARNING_1_8.resource,
  qcm: [...URINE_FORMULA_LEARNING_1_8.qcm, ...URINE_FORMULA_LEARNING_9_10.qcm],
  exam: {
    titre_fr: URINE_FORMULA_LEARNING_1_8.exam.titre_fr,
    duration_seconds: URINE_FORMULA_LEARNING_1_8.exam.duration_seconds + URINE_FORMULA_LEARNING_9_10.exam.duration_seconds,
  },
};
const URINE_FORMULA_FLASHCARDS: LibraryCardSeed[] = [...URINE_FORMULA_FLASHCARDS_1_8, ...URINE_FORMULA_FLASHCARDS_9_10];

// Contenu officiel pré-rédigé : Physiologie, Année 1, Semestre 1.
// Extrait des cours magistraux (UMFT "V. Babes" Timisoara, Department of
// Functional Sciences) fournis par l'utilisatrice — un chapitre par lecture,
// regroupé par grand systeme physiologique (general -> sang -> renal -> digestif).
export const PHYSIOLOGIE_S1: LibraryChapterSeed[] = [
  {
    ordre: 1,
    titre_fr: "Physiologie de la membrane cellulaire",
    titre_en: "Cell Membrane Physiology",
    description_fr: "Mecanismes de transport passif et actif a travers la membrane cellulaire",
    description_en: "Passive and active transport mechanisms across the cell membrane",
    icone: "🧫",
    learning: CELL_MEMBRANE_LEARNING,
    cards: CELL_MEMBRANE_FLASHCARDS,
  },
  {
    ordre: 2,
    titre_fr: "Recepteurs et signalisation intracellulaire",
    titre_en: "Receptors and Intracellular Signaling",
    description_fr: "Recepteurs membranaires, seconds messagers et role des boucles de retroaction",
    description_en: "Membrane receptors, second messengers, and the role of feedback loops",
    icone: "🔗",
    learning: RECEPTORS_SIGNALING_LEARNING,
    cards: RECEPTORS_SIGNALING_FLASHCARDS,
  },
  {
    ordre: 3,
    titre_fr: "Physiologie du neurone",
    titre_en: "Neuron Physiology",
    description_fr: "Potentiels membranaires et conduction de l'influx dans les fibres nerveuses",
    description_en: "Membrane potentials and conduction through nerve fibers",
    icone: "⚡",
    learning: NEURON_PHYSIOLOGY_LEARNING,
    cards: NEURON_PHYSIOLOGY_FLASHCARDS,
  },
  {
    ordre: 4,
    titre_fr: "Physiologie du muscle lisse et strie",
    titre_en: "Smooth and Striated Muscle Physiology",
    description_fr: "Mecanismes de contraction et particularites fonctionnelles des muscles lisse et strie",
    description_en: "Contraction mechanisms and functional particularities of smooth and striated muscle",
    icone: "💪",
    learning: MUSCLE_PHYSIOLOGY_LEARNING,
    cards: MUSCLE_PHYSIOLOGY_FLASHCARDS,
  },
  {
    ordre: 5,
    titre_fr: "Milieu interieur et globules rouges",
    titre_en: "Internal Environment and Red Blood Cells",
    description_fr: "Composition du milieu interieur et physiologie des globules rouges",
    description_en: "Composition of the internal environment and red blood cell physiology",
    icone: "🩸",
    learning: RED_BLOOD_CELLS_LEARNING,
    cards: RED_BLOOD_CELLS_FLASHCARDS,
  },
  {
    ordre: 6,
    titre_fr: "Volemie, hematopoiese et leucocytes",
    titre_en: "Volemia, Hematopoiesis, and Leukocytes",
    description_fr: "Regulation de la volemie, hematopoiese et role des leucocytes dans la defense de l'organisme",
    description_en: "Volemia regulation, hematopoiesis, and the role of leukocytes in the body's defense",
    icone: "🛡️",
    learning: HEMATOPOIESIS_LEUKOCYTES_LEARNING,
    cards: HEMATOPOIESIS_LEUKOCYTES_FLASHCARDS,
  },
  {
    ordre: 7,
    titre_fr: "Hemostase physiologique",
    titre_en: "Physiological Hemostasis",
    description_fr: "Hemostase primaire, coagulation et fibrinolyse",
    description_en: "Primary hemostasis, coagulation, and fibrinolysis",
    icone: "🩹",
    learning: HEMOSTASIS_LEARNING,
    cards: HEMOSTASIS_FLASHCARDS,
  },
  {
    ordre: 8,
    titre_fr: "Organisation du rein et filtration glomerulaire",
    titre_en: "Kidney Organization and Glomerular Filtration",
    description_fr: "Organisation fonctionnelle du rein, circulation renale et filtration glomerulaire",
    description_en: "Functional organization of the kidney, renal circulation, and glomerular filtration",
    icone: "🫘",
    learning: RENAL_FILTRATION_LEARNING,
    cards: RENAL_FILTRATION_FLASHCARDS,
  },
  {
    ordre: 9,
    titre_fr: "Fonctions tubulaires",
    titre_en: "Tubular Functions",
    description_fr: "Mecanismes generaux du transport tubulaire et physiologie du tube contourne proximal",
    description_en: "General mechanisms of tubular transport and physiology of the proximal convoluted tubule",
    icone: "🧪",
    learning: TUBULAR_FUNCTIONS_LEARNING,
    cards: TUBULAR_FUNCTIONS_FLASHCARDS,
  },
  {
    ordre: 10,
    titre_fr: "Excretion renale et epargne plasmatique",
    titre_en: "Renal Excretion and Plasma Sparing",
    description_fr: "Epargne et excretion renale des principaux composants plasmatiques",
    description_en: "Renal sparing and excretion of the main plasma components",
    icone: "💧",
    learning: RENAL_EXCRETION_LEARNING,
    cards: RENAL_EXCRETION_FLASHCARDS,
  },
  {
    ordre: 11,
    titre_fr: "Regulation de la fonction renale et miction",
    titre_en: "Regulation of Renal Function and Micturition",
    description_fr: "Controle nerveux et hormonal du rein, accumulation et evacuation de l'urine",
    description_en: "Nervous and hormonal control of the kidney, urine accumulation and evacuation",
    icone: "🚽",
    learning: RENAL_REGULATION_LEARNING,
    cards: RENAL_REGULATION_FLASHCARDS,
  },
  {
    ordre: 12,
    titre_fr: "Fonction secretoire du tube digestif",
    titre_en: "Secretory Function of the Digestive Tract",
    description_fr: "Secretions salivaire, gastrique, pancreatique et biliaire",
    description_en: "Salivary, gastric, pancreatic, and biliary secretions",
    icone: "🦷",
    learning: DIGESTIVE_SECRETION_LEARNING,
    cards: DIGESTIVE_SECRETION_FLASHCARDS,
  },
  {
    ordre: 13,
    titre_fr: "Digestion et absorption des principes nutritifs",
    titre_en: "Digestion and Absorption of Nutrients",
    description_fr: "Digestion et absorption des glucides, lipides et proteines",
    description_en: "Digestion and absorption of carbohydrates, lipids, and proteins",
    icone: "🍽️",
    learning: DIGESTION_ABSORPTION_LEARNING,
    cards: DIGESTION_ABSORPTION_FLASHCARDS,
  },
  {
    ordre: 14,
    titre_fr: "Motilite gastro-intestinale",
    titre_en: "Gastrointestinal Motility",
    description_fr: "Particularites du muscle lisse visceral et motilite des differents segments digestifs",
    description_en: "Particularities of visceral smooth muscle and motility of the digestive segments",
    icone: "🌀",
    learning: GI_MOTILITY_LEARNING,
    cards: GI_MOTILITY_FLASHCARDS,
  },

  // Chapitres de laboratoire (section "laboratoire") : fiches pratiques
  // preparees pour le TP/examen pratique a partir des quiz personnels de
  // l'utilisatrice (bases sur ses propres notes de laboratoire).
  {
    ordre: 101,
    section: "laboratoire",
    titre_fr: "TP — Osmolarité",
    titre_en: "Lab — Osmolarity",
    description_fr: "Osmolarité sanguine normale et calcul de l'osmolarité plasmatique",
    description_en: "Normal blood osmolarity and calculation of plasma osmolarity",
    icone: "💧",
    learning: OSMOLARITY_LEARNING,
    cards: OSMOLARITY_FLASHCARDS,
  },
  {
    ordre: 102,
    section: "laboratoire",
    titre_fr: "TP — Ionogramme",
    titre_en: "Lab — Ionogram",
    description_fr: "Valeurs normales de l'ionogramme sanguin (Na⁺, K⁺, Ca²⁺, Mg²⁺, Cl⁻)",
    description_en: "Normal blood ionogram values (Na⁺, K⁺, Ca²⁺, Mg²⁺, Cl⁻)",
    icone: "🧪",
    learning: IONOGRAMME_LEARNING,
    cards: IONOGRAMME_FLASHCARDS,
  },
  {
    ordre: 103,
    section: "laboratoire",
    titre_fr: "TP — Hématogramme",
    titre_en: "Lab — Complete Blood Count",
    description_fr: "Valeurs normales de l'hémogramme (hémoglobine, hématocrite, indices érythrocytaires)",
    description_en: "Normal complete blood count values (hemoglobin, hematocrit, red cell indices)",
    icone: "🩸",
    learning: HEMATOGRAMME_LEARNING,
    cards: HEMATOGRAMME_FLASHCARDS,
  },
  {
    ordre: 104,
    section: "laboratoire",
    titre_fr: "TP — Équilibre acido-basique (gaz du sang)",
    titre_en: "Lab — Acid-Base Balance (Blood Gases)",
    description_fr: "Interprétation normale et pathologique des gaz du sang",
    description_en: "Normal and pathological interpretation of blood gases",
    icone: "🫁",
    learning: ABB_LEARNING,
    cards: ABB_FLASHCARDS,
  },
  {
    ordre: 105,
    section: "laboratoire",
    titre_fr: "TP — Hémostase (fiche partielle)",
    titre_en: "Lab — Hemostasis (Partial Sheet)",
    description_fr: "Valeurs normales et pathologiques de l'hémostase — fiche partielle, certaines questions sources manquantes",
    description_en: "Normal and pathological hemostasis values — partial sheet, some source questions missing",
    icone: "🩹",
    learning: HEMOSTASIS_PARTIAL_LEARNING,
    cards: HEMOSTASIS_PARTIAL_FLASHCARDS,
  },
  {
    ordre: 106,
    section: "laboratoire",
    titre_fr: "TP — Protéinogramme",
    titre_en: "Lab — Protein Electrophoresis",
    description_fr: "Fractions normales du protéinogramme (albumine, α1, α2, β, γ-globulines)",
    description_en: "Normal protein electrophoresis fractions (albumin, α1, α2, β, γ-globulins)",
    icone: "📊",
    learning: PROTEINOGRAM_LEARNING,
    cards: PROTEINOGRAM_FLASHCARDS,
  },
  {
    ordre: 107,
    section: "laboratoire",
    titre_fr: "TP — Formules de physiologie rénale",
    titre_en: "Lab — Renal Physiology Formulas",
    description_fr: "Fraction de filtration, débit plasmatique rénal, trou anionique urinaire et débit de filtration glomérulaire",
    description_en: "Filtration fraction, renal plasma flow, urinary anion gap, and glomerular filtration rate",
    icone: "🧮",
    learning: URINE_FORMULA_LEARNING,
    cards: URINE_FORMULA_FLASHCARDS,
  },
  {
    ordre: 108,
    section: "laboratoire",
    titre_fr: "TP — Leucogramme",
    titre_en: "Lab — Leukogram",
    description_fr: "Valeurs normales et anormales de la formule leucocytaire",
    description_en: "Normal and abnormal white blood cell differential values",
    icone: "🛡️",
    learning: LEUKOGRAM_LEARNING,
    cards: LEUKOGRAM_FLASHCARDS,
  },
  {
    ordre: 109,
    section: "laboratoire",
    titre_fr: "TP — Diagnostic différentiel des anémies",
    titre_en: "Lab — Differential Diagnosis of Anemias",
    description_fr: "Classification des anémies par les indices érythrocytaires",
    description_en: "Classification of anemias by red cell indices",
    icone: "🔬",
    learning: ANEMIA_DIFFERENTIAL_LEARNING,
    cards: ANEMIA_DIFFERENTIAL_FLASHCARDS,
  },
  {
    ordre: 110,
    section: "laboratoire",
    titre_fr: "TP — Valeurs de référence (synthèse)",
    titre_en: "Lab — Reference Values (Summary)",
    description_fr: "Synthèse des valeurs normales de tous les examens de laboratoire du semestre",
    description_en: "Summary of normal values across all lab examinations of the semester",
    icone: "📋",
    learning: REFERENCE_VALUES_LEARNING,
    cards: REFERENCE_VALUES_FLASHCARDS,
  },
  {
    ordre: 111,
    section: "laboratoire",
    titre_fr: "TP — Tableaux d'interprétation (synthèse)",
    titre_en: "Lab — Interpretation Patterns (Summary)",
    description_fr: "Schémas d'interprétation clinique : dysprotéinémies, hémostase pathologique, fonction rénale, désordres acido-basiques",
    description_en: "Clinical interpretation patterns: dysproteinemias, pathological hemostasis, renal function, acid-base disorders",
    icone: "🗺️",
    learning: INTERPRETATION_PATTERNS_LEARNING,
    cards: INTERPRETATION_PATTERNS_FLASHCARDS,
  },
];
