// Sigles utilisés dans les schémas, avec leur signification (affichés sous chaque schéma).
export const ACRONYMS: Record<string, string> = {
  ATP: "adénosine triphosphate", ADP: "adénosine diphosphate", AMP: "adénosine monophosphate",
  GTP: "guanosine triphosphate", GDP: "guanosine diphosphate", GMP: "guanosine monophosphate",
  CTP: "cytidine triphosphate", UTP: "uridine triphosphate", UDP: "uridine diphosphate", UMP: "uridine monophosphate",
  IMP: "inosine monophosphate", OMP: "orotidine monophosphate", NTP: "nucléoside triphosphate", NDP: "nucléoside diphosphate",
  NAD: "nicotinamide adénine dinucléotide", NADH: "NAD sous forme réduite", NADP: "NAD phosphate", NADPH: "NADP sous forme réduite",
  FAD: "flavine adénine dinucléotide", FADH: "FAD sous forme réduite", FMN: "flavine mononucléotide", CoA: "coenzyme A",
  TPP: "pyrophosphate de thiamine", PLP: "phosphate de pyridoxal", PRPP: "phosphoribosyl pyrophosphate", THF: "tétrahydrofolate",
  PDH: "pyruvate déshydrogénase", PFK: "phosphofructokinase", LDH: "lactate déshydrogénase", MDH: "malate déshydrogénase",
  GLDH: "glutamate déshydrogénase", GAPDH: "glycéraldéhyde-3-phosphate déshydrogénase", PEPCK: "phosphoénolpyruvate carboxykinase",
  ALAT: "alanine aminotransférase", ASAT: "aspartate aminotransférase", ALT: "alanine aminotransférase", AST: "aspartate aminotransférase",
  GPT: "glutamate-pyruvate transaminase", GOT: "glutamate-oxaloacétate transaminase",
  PEP: "phosphoénolpyruvate", DHAP: "dihydroxyacétone phosphate", G6P: "glucose-6-phosphate", F6P: "fructose-6-phosphate", G1P: "glucose-1-phosphate",
  OAA: "oxaloacétate", AMPK: "protéine kinase activée par l'AMP", ACC: "acétyl-CoA carboxylase", FAS: "acide gras synthase",
  FFA: "acides gras libres", ATGL: "triglycéride lipase des adipocytes", HSL: "lipase hormonosensible", MGL: "monoacylglycérol lipase",
  CPT: "carnitine palmitoyltransférase", CPS1: "carbamoyl-phosphate synthétase 1", NAG: "N-acétylglutamate", OTC: "ornithine transcarbamylase",
  ASS: "argininosuccinate synthétase", ASL: "argininosuccinate lyase", HMG: "hydroxyméthylglutaryl", SCOT: "succinyl-CoA : acétoacétate CoA-transférase",
  G6PD: "glucose-6-phosphate déshydrogénase", PGDH: "6-phosphogluconate déshydrogénase", P450: "cytochrome P450",
  SREBP: "protéine de liaison à l'élément de réponse aux stérols", ACAT: "acyl-CoA cholestérol acyltransférase",
  LCAT: "lécithine-cholestérol acyltransférase", LPL: "lipoprotéine lipase",
  LDL: "lipoprotéine de basse densité", HDL: "lipoprotéine de haute densité", VLDL: "lipoprotéine de très basse densité", IDL: "lipoprotéine de densité intermédiaire",
  TG: "triglycérides", TAG: "triacylglycérols", PL: "phospholipides", PKA: "protéine kinase A", PKC: "protéine kinase C", PP1: "protéine phosphatase 1",
  DNP: "2,4-dinitrophénol", HbA: "hémoglobine adulte", HbF: "hémoglobine fœtale", HbS: "hémoglobine S (drépanocytose)",
  BPG: "2,3-bisphosphoglycérate", P50: "pression partielle d'O₂ pour 50 % de saturation", PrP: "protéine prion",
  ADN: "acide désoxyribonucléique", ARN: "acide ribonucléique", PTH: "parathormone", PABA: "acide para-aminobenzoïque",
  GR: "globules rouges", VGM: "volume globulaire moyen", CCMH: "concentration corpusculaire moyenne en hémoglobine",
  TCMH: "teneur corpusculaire moyenne en hémoglobine", EPO: "érythropoïétine", TPO: "thrombopoïétine", NK: "cellules tueuses naturelles",
  CD4: "grappe de différenciation 4 (lymphocyte T auxiliaire)", CD8: "grappe de différenciation 8 (lymphocyte T cytotoxique)", IgE: "immunoglobuline E",
  TxA: "thromboxane A₂", PGI: "prostacycline (prostaglandine I₂)", TS: "temps de saignement", APTT: "temps de céphaline activée", TP: "taux de prothrombine",
  PT: "temps de prothrombine", INR: "rapport international normalisé", WBC: "leucocytes", NE: "polynucléaires neutrophiles", LY: "lymphocytes",
  MO: "monocytes", EO: "polynucléaires éosinophiles", BA: "polynucléaires basophiles", AG: "trou anionique",
  DFG: "débit de filtration glomérulaire", RPF: "débit plasmatique rénal", FF: "fraction de filtration", PAH: "acide para-aminohippurique",
  ClPAH: "clairance du PAH", ADH: "hormone antidiurétique", SRAA: "système rénine-angiotensine-aldostérone", PGE: "prostaglandine E",
  AINS: "anti-inflammatoires non stéroïdiens", VIP: "peptide intestinal vasoactif", CCK: "cholécystokinine",
  TCP: "tube contourné proximal", TCD: "tube contourné distal", TC: "tube collecteur", MMCC: "mécanisme multiplicateur à contre-courant",
  FG: "filtration glomérulaire", EAB: "équilibre acido-basique", NKCC2: "cotransporteur Na⁺-K⁺-2Cl⁻",
  SNC: "système nerveux central", SNP: "système nerveux périphérique", PPSE: "potentiel post-synaptique excitateur",
  PPSI: "potentiel post-synaptique inhibiteur", COMT: "catéchol-O-méthyltransférase", GABA: "acide gamma-aminobutyrique",
  RyR: "récepteur de la ryanodine", DHPR: "récepteur des dihydropyridines", SERCA: "Ca²⁺-ATPase du réticulum sarcoplasmique",
  MLCK: "kinase de la chaîne légère de la myosine", MLCP: "phosphatase de la chaîne légère de la myosine", PLC: "phospholipase C",
  DAG: "diacylglycérol", RCPG: "récepteur couplé aux protéines G", LMM: "méromyosine légère", HMM: "méromyosine lourde", RS: "réticulum sarcoplasmique",
  GLUT: "transporteur de glucose (GLUT1 à GLUT5)", SGLT: "cotransporteur sodium-glucose", LEC: "liquide extracellulaire", LIC: "liquide intracellulaire",
  LCR: "liquide cérébro-spinal", EDTA: "éthylènediaminetétraacétate", HGPO: "hyperglycémie provoquée par voie orale", IMC: "indice de masse corporelle",
  BUN: "azote uréique sanguin", LH: "hormone lutéinisante", FSH: "hormone folliculo-stimulante", GnRH: "gonadolibérine",
  IDR: "intradermoréaction", VCI: "veine cave inférieure", UV: "ultraviolets", UVB: "ultraviolets B",
};
