// Images externes insérables dans un cours via [[image:clé]] (cf. MarkdownContent).
// Chaque entrée porte sa légende et son crédit : toute image ajoutée ici doit
// être libre de droits (domaine public ou licence libre) et sa licence vérifiée.
// Fichiers servis depuis client/public/anatomie/.
export interface CourseImage {
  src: string;
  caption: string;
  credit: string;
  license: string;
  sourceUrl: string;
}

const GRAY = "Henry Gray, Anatomy of the Human Body (1918), via Wikimedia Commons";
const gray = (n: number, caption: string): CourseImage => ({
  src: `/anatomie/gray-${n}.png`,
  caption,
  credit: GRAY,
  license: "Domaine public",
  sourceUrl: `https://commons.wikimedia.org/wiki/File:Gray${n}.png`,
});

export const COURSE_IMAGES: Record<string, CourseImage> = {
  "gray-409": gray(409, "Muscles reliant le membre supérieur à la colonne vertébrale (trapèze, grand dorsal, rhomboïdes), vue postérieure"),
  "gray-410": gray(410, "Grand pectoral et muscles de la face antérieure du thorax et de l'épaule"),
  "gray-411": gray(411, "Muscles du thorax et de la face antérieure du bras (biceps brachial, brachial, coracobrachial)"),
  "gray-412": gray(412, "Muscles dorsaux de la scapula et triceps brachial (face postérieure du bras)"),
  "gray-413": gray(413, "Coupe transversale du bras : compartiments antérieur et postérieur, nerfs et vaisseaux"),
  "gray-417": gray(417, "Coupe transversale de l'avant-bras : compartiments musculaires, radius et ulna"),
  "gray-414": gray(414, "Face antérieure de l'avant-bras : muscles du plan superficiel"),
  "gray-415": gray(415, "Face antérieure de l'avant-bras : muscles du plan profond"),
  "gray-418": gray(418, "Face postérieure de l'avant-bras : muscles du plan superficiel"),
  "gray-419": gray(419, "Face postérieure de l'avant-bras : muscles du plan profond"),
  "gray-423": gray(423, "Paume de la main : éminences thénar et hypothénar, gaines des tendons fléchisseurs"),
  "gray-424": gray(424, "Face dorsale de la main : rétinaculum des extenseurs et tendons"),
  "gray-326": gray(326, "Articulations de l'épaule et acromio-claviculaire, ligaments propres de la scapula"),
  "gray-327": gray(327, "Capsule de l'articulation gléno-humérale (distendue), vue antérieure"),
  "gray-329": gray(329, "Articulation du coude gauche : ligaments antérieur et médial"),
  "gray-330": gray(330, "Articulation du coude gauche : ligaments postérieur et latéral"),
  "gray-333": gray(333, "Ligament annulaire du radius, vu d'en haut (articulation radio-ulnaire proximale)"),
  "gray-200": gray(200, "Clavicule : face supérieure"),
  "gray-201": gray(201, "Clavicule : face inférieure"),
  "gray-202": gray(202, "Scapula : face ventrale (fosse subscapulaire), avec les insertions musculaires"),
  "gray-203": gray(203, "Scapula : face dorsale (fosses supra- et infra-épineuse), avec les insertions musculaires"),
  "gray-207": gray(207, "Humérus : face antérieure, avec les insertions musculaires"),
  "gray-208": gray(208, "Humérus : face postérieure, avec les insertions musculaires"),
  "gray-213": gray(213, "Radius et ulna : face antérieure, avec les insertions musculaires"),
  "gray-214": gray(214, "Radius et ulna : face postérieure, avec les insertions musculaires"),
  "gray-219": gray(219, "Os de la main : face palmaire"),
  "gray-220": gray(220, "Os de la main : face dorsale"),
  "gray-235": gray(235, "Os coxal : face latérale (externe), avec les insertions musculaires"),
  "gray-236": gray(236, "Os coxal : face médiale (interne), avec les insertions musculaires"),
  "gray-244": gray(244, "Fémur : face antérieure, avec les insertions musculaires"),
  "gray-245": gray(245, "Fémur : face postérieure, avec les insertions musculaires"),
  "gray-255": gray(255, "Patella : face antérieure"),
  "gray-256": gray(256, "Patella : face postérieure (surface articulaire)"),
  "gray-339": gray(339, "Articulation de la hanche droite, vue antérieure"),
  "gray-340": gray(340, "Articulation de la hanche, vue postérieure"),
  "gray-341": gray(341, "Articulation de la hanche gauche ouverte : ligament de la tête fémorale"),
  "gray-345": gray(345, "Genou droit, vue antérieure"),
  "gray-348": gray(348, "Genou : ligaments croisés, ligaments collatéraux et ménisques"),
  "gray-349": gray(349, "Ménisques et ligaments croisés, vus d'en haut (plateau tibial)"),
  "gray-350": gray(350, "Coupe sagittale de l'articulation du genou"),
  "gray-392": gray(392, "Paroi abdominale : muscle oblique externe et son aponévrose"),
  "gray-393": gray(393, "Région inguinale : anneau inguinal superficiel et aponévrose de l'oblique externe"),
  "gray-394": gray(394, "Os coxal : ligament inguinal, ligament lacunaire, tubercule pubien"),
  "gray-395": gray(395, "Muscle oblique interne gauche"),
  "gray-398": gray(398, "Muscle grand droit, ligne arquée et vaisseaux épigastriques inférieurs"),
  "gray-399": gray(399, "Coupe schématique de la gaine des droits"),
  "gray-401": gray(401, "Muscles larges de l'abdomen : transverse, oblique interne et anneau inguinal profond"),
  "gray-426": gray(426, "Muscles thénariens et hypothénariens : opposant du pouce, adducteur du pouce, opposant du 5e doigt"),
  "gray-427": gray(427, "Paume de la main : muscles lombricaux et tendons des fléchisseurs"),
  "gray-428": gray(428, "Muscles interosseux dorsaux (schéma)"),
  "gray-429": gray(429, "Muscles interosseux palmaires (schéma)"),
  "gray-430": gray(430, "Muscles de la région iliaque et de la face antérieure de la cuisse (iliopsoas, quadriceps)"),
  "gray-432": gray(432, "Coupe transversale de la cuisse : compartiments antérieur, médial et postérieur"),
  "gray-433": gray(433, "Muscles adducteurs de la cuisse (face médiale)"),
  "gray-434": gray(434, "Muscles de la région glutéale et de la face postérieure de la cuisse (ischio-jambiers)"),
  "gray-437": gray(437, "Muscles du compartiment antérieur de la jambe et du dos du pied"),
  "gray-438": gray(438, "Muscles superficiels du compartiment postérieur de la jambe (triceps sural)"),
  "gray-439": gray(439, "Muscles de la jambe, vue latérale"),
  "gray-440": gray(440, "Coupe transversale de la jambe : compartiments antérieur, latéral et postérieur"),
  "gray-443": gray(443, "Muscles de la plante du pied : première couche"),
  "gray-444": gray(444, "Muscles de la plante du pied : deuxième couche"),
  "gray-445": gray(445, "Muscles de la plante du pied : troisième couche"),
  "gray-523": gray(523, "Artère axillaire et ses branches (région de l'épaule et de l'aisselle)"),
  "gray-525": gray(525, "Artère brachiale et ses branches (face antérieure du bras)"),
  "gray-526": gray(526, "Artères du coude : anastomose péri-articulaire entre les artères brachiale, radiale et ulnaire"),
  "gray-527": gray(527, "Artères de l'avant-bras et de la main (face antérieure)"),
  "gray-528": gray(528, "Artères de l'avant-bras : artères radiale et ulnaire, récurrentes et interosseuse"),
  "gray-546": gray(546, "Région inguinale : nerf fémoral, artère et veine fémorales"),
  "gray-549": gray(549, "Triangle fémoral : vaisseaux fémoraux et veine grande saphène"),
  "gray-550": gray(550, "Artère fémorale et ses branches (face antérieure de la cuisse)"),
  "gray-551": gray(551, "Artères de la jambe (vue postérieure)"),
  "gray-552": gray(552, "Anastomoses artérielles autour du genou (artères géniculées)"),
  "gray-553": gray(553, "Artères de la jambe et du dos du pied (vue antérieure)"),
  "gray-554": gray(554, "Artères du dos du pied"),
  "gray-555": gray(555, "Artères de la plante du pied : arcade plantaire profonde"),
  "gray-573": gray(573, "Veines superficielles du dos de la main"),
  "gray-574": gray(574, "Veines superficielles de l'avant-bras et du bras"),
  "gray-575": gray(575, "Veines profondes du coude : veines comitantes de l'artère brachiale"),
  "gray-581": gray(581, "Veines superficielles du membre inférieur (vue antérieure)"),
  "gray-582": gray(582, "Veines superficielles du membre inférieur (vue postérieure)"),
  "gray-807": gray(807, "Plexus brachial : racines C5 à T1 et nerfs terminaux (schéma)"),
  "gray-809": gray(809, "Nerfs de l'aisselle : nerf musculo-cutané et branches du plexus brachial"),
  "gray-815": gray(815, "Nerfs de la paume de la main : nerfs médian et ulnaire"),
  "gray-817": gray(817, "Nerfs du dos de la main : nerfs radial et ulnaire"),
  "gray-822": gray(822, "Plexus lombaire (schéma)"),
  "gray-828": gray(828, "Plexus sacré (schéma)"),
  "gray-832": gray(832, "Nerf sciatique et ses branches (face postérieure de la cuisse et de la jambe)"),
  "gray-833": gray(833, "Nerfs de la plante du pied : nerfs plantaires médial et latéral"),
  "gray-835": gray(835, "Nerf fibulaire profond et vaisseaux tibiaux antérieurs (face antérieure de la jambe)"),
};
