// Structures moléculaires des cartes de révision : formule SMILES (dessinée par
// OpenChemLib côté client) + formule brute attendue, utilisée par le contrôle
// automatique (scripts/check-molecules.ts) pour détecter toute erreur de SMILES.
// Les acides aminés sont dessinés sous forme neutre (non zwitterionique).
export interface MoleculeDef {
  smiles: string;
  formula: string;
}

export const AMINO_SMILES: Record<string, MoleculeDef> = {
  Gly: { smiles: "NCC(=O)O", formula: "C2H5NO2" },
  Ala: { smiles: "C[C@H](N)C(=O)O", formula: "C3H7NO2" },
  Val: { smiles: "CC(C)[C@H](N)C(=O)O", formula: "C5H11NO2" },
  Leu: { smiles: "CC(C)C[C@H](N)C(=O)O", formula: "C6H13NO2" },
  Ile: { smiles: "CC[C@H](C)[C@H](N)C(=O)O", formula: "C6H13NO2" },
  Pro: { smiles: "OC(=O)[C@@H]1CCCN1", formula: "C5H9NO2" },
  Met: { smiles: "CSCC[C@H](N)C(=O)O", formula: "C5H11NO2S" },
  Phe: { smiles: "N[C@@H](Cc1ccccc1)C(=O)O", formula: "C9H11NO2" },
  Trp: { smiles: "N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O", formula: "C11H12N2O2" },
  Ser: { smiles: "N[C@@H](CO)C(=O)O", formula: "C3H7NO3" },
  Thr: { smiles: "C[C@@H](O)[C@H](N)C(=O)O", formula: "C4H9NO3" },
  Tyr: { smiles: "N[C@@H](Cc1ccc(O)cc1)C(=O)O", formula: "C9H11NO3" },
  Cys: { smiles: "N[C@@H](CS)C(=O)O", formula: "C3H7NO2S" },
  Asn: { smiles: "N[C@@H](CC(N)=O)C(=O)O", formula: "C4H8N2O3" },
  Gln: { smiles: "N[C@@H](CCC(N)=O)C(=O)O", formula: "C5H10N2O3" },
  Asp: { smiles: "N[C@@H](CC(=O)O)C(=O)O", formula: "C4H7NO4" },
  Glu: { smiles: "N[C@@H](CCC(=O)O)C(=O)O", formula: "C5H9NO4" },
  Lys: { smiles: "N[C@@H](CCCCN)C(=O)O", formula: "C6H14N2O2" },
  Arg: { smiles: "N[C@@H](CCCNC(N)=N)C(=O)O", formula: "C6H14N4O2" },
  His: { smiles: "N[C@@H](Cc1cnc[nH]1)C(=O)O", formula: "C6H9N3O2" },
};

export const MOLECULES: Record<string, MoleculeDef> = {
  // ── Glucides ──
  glucose: { smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O", formula: "C6H12O6" },
  galactose: { smiles: "C([C@@H]1[C@@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O", formula: "C6H12O6" },
  mannose: { smiles: "C([C@@H]1[C@H]([C@@H]([C@@H]([C@H](O1)O)O)O)O)O", formula: "C6H12O6" },
  fructose: { smiles: "C([C@@H]1[C@H]([C@@H]([C@](O1)(CO)O)O)O)O", formula: "C6H12O6" },
  ribose: { smiles: "C([C@@H]1[C@H]([C@H]([C@@H](O1)O)O)O)O", formula: "C5H10O5" },
  deoxyribose: { smiles: "C1[C@@H]([C@H](O[C@H]1O)CO)O", formula: "C5H10O4" },
  sucrose: { smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C@H]([C@@H]([C@H](O2)CO)O)O)CO)O)O)O)O", formula: "C12H22O11" },
  maltose: { smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[C@H](O[C@@H]([C@@H]([C@H]2O)O)O)CO)O)O)O)O", formula: "C12H22O11" },
  lactose: { smiles: "C([C@@H]1[C@@H]([C@@H]([C@H]([C@@H](O1)O[C@@H]2[C@H](OC([C@@H]([C@H]2O)O)O)CO)O)O)O)O", formula: "C12H22O11" },
  glcnac: { smiles: "CC(=O)N[C@@H]1[C@H]([C@@H]([C@H](O[C@H]1O)CO)O)O", formula: "C8H15NO6" },
  // ── Lipides ──
  palmitate: { smiles: "CCCCCCCCCCCCCCCC(=O)O", formula: "C16H32O2" },
  stearate: { smiles: "CCCCCCCCCCCCCCCCCC(=O)O", formula: "C18H36O2" },
  oleate: { smiles: "CCCCCCCC/C=C\\CCCCCCCC(=O)O", formula: "C18H34O2" },
  linoleate: { smiles: "CCCCC/C=C\\C/C=C\\CCCCCCCC(=O)O", formula: "C18H32O2" },
  linolenate: { smiles: "CC/C=C\\C/C=C\\C/C=C\\CCCCCCCC(=O)O", formula: "C18H30O2" },
  arachidonate: { smiles: "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)O", formula: "C20H32O2" },
  glycerol: { smiles: "OCC(O)CO", formula: "C3H8O3" },
  tripalmitin: { smiles: "CCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCC", formula: "C51H98O6" },
  dppc: { smiles: "CCCCCCCCCCCCCCCC(=O)OC[C@H](COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CCCCCCCCCCCCCCC", formula: "C40H80NO8P" },
  sphingosine: { smiles: "CCCCCCCCCCCCC/C=C/[C@H](O)[C@@H](N)CO", formula: "C18H37NO2" },
  cholesterol: { smiles: "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)C", formula: "C27H46O" },
  cholate: { smiles: "C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1([C@H](C[C@H]3[C@H]2[C@@H](C[C@@H]4[C@@]3(CC[C@H](C4)O)C)O)O)C", formula: "C24H40O5" },
  mevalonate: { smiles: "CC(O)(CCO)CC(=O)O", formula: "C6H12O4" },
  // ── Vitamines et cofacteurs ──
  ascorbate: { smiles: "C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O", formula: "C6H8O6" },
  thiamine: { smiles: "Cc1ncc(C[n+]2csc(CCO)c2C)c(N)n1", formula: "C12H17N4OS" },
  tpp: { smiles: "Cc1ncc(C[n+]2csc(CCOP(=O)(O)OP(=O)(O)O)c2C)c(N)n1", formula: "C12H19N4O7P2S" },
  riboflavin: { smiles: "Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)CO)c2cc1C", formula: "C17H20N4O6" },
  niacin: { smiles: "OC(=O)c1cccnc1", formula: "C6H5NO2" },
  nicotinamide: { smiles: "NC(=O)c1cccnc1", formula: "C6H6N2O" },
  pantothenate: { smiles: "CC(C)(CO)[C@@H](O)C(=O)NCCC(=O)O", formula: "C9H17NO5" },
  pyridoxal: { smiles: "Cc1ncc(CO)c(C=O)c1O", formula: "C8H9NO3" },
  plp: { smiles: "Cc1ncc(COP(=O)(O)O)c(C=O)c1O", formula: "C8H10NO6P" },
  biotin: { smiles: "O=C(O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@H]12", formula: "C10H16N2O3S" },
  folate: { smiles: "C1=CC(=CC=C1C(=O)N[C@@H](CCC(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)N=C(N3)N", formula: "C19H19N7O6" },
  retinol: { smiles: "C/C(=C\\CO)/C=C/C=C(\\C)/C=C/C1=C(C)CCCC1(C)C", formula: "C20H30O" },
  retinal: { smiles: "C/C(=C\\C=O)/C=C/C=C(\\C)/C=C/C1=C(C)CCCC1(C)C", formula: "C20H28O" },
  cholecalciferol: { smiles: "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]\\2[C@@]1(CCC/C2=C\\C=C/3\\C[C@H](CCC3=C)O)C", formula: "C27H44O" },
  tocopherol: { smiles: "CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C(=C1O)C)C", formula: "C29H50O2" },
  phylloquinone: { smiles: "CC1=C(C(=O)C2=CC=CC=C2C1=O)C/C=C(\\C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C", formula: "C31H46O2" },
  nad: { smiles: "NC(=O)c1ccc[n+](c1)[C@@H]1O[C@H](COP(=O)([O-])OP(=O)(O)OC[C@H]2O[C@@H](n3cnc4c(N)ncnc34)[C@H](O)[C@@H]2O)[C@@H](O)[C@H]1O", formula: "C21H27N7O14P2" },
  nadh: { smiles: "NC(=O)C1=CN(C=CC1)[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]2O[C@@H](n3cnc4c(N)ncnc34)[C@H](O)[C@@H]2O)[C@@H](O)[C@H]1O", formula: "C21H29N7O14P2" },
  fad: { smiles: "Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)c2cc1C", formula: "C27H33N9O15P2" },
  coa: { smiles: "CC(C)(COP(=O)(O)OP(=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)n2cnc3c2ncnc3N)O)OP(=O)(O)O)[C@H](C(=O)NCCC(=O)NCCS)O", formula: "C21H36N7O16P3S" },
  acetylcoa: { smiles: "CC(C)(COP(=O)(O)OP(=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)n2cnc3c2ncnc3N)O)OP(=O)(O)O)[C@H](C(=O)NCCC(=O)NCCSC(C)=O)O", formula: "C23H38N7O17P3S" },
  glutathione: { smiles: "N[C@@H](CCC(=O)N[C@@H](CS)C(=O)NCC(=O)O)C(=O)O", formula: "C10H17N3O6S" },
  carnitine: { smiles: "C[N+](C)(C)C[C@H](O)CC(=O)[O-]", formula: "C7H15NO3" },
  // ── Nucléotides ──
  adenine: { smiles: "Nc1ncnc2[nH]cnc12", formula: "C5H5N5" },
  guanine: { smiles: "Nc1nc2[nH]cnc2c(=O)[nH]1", formula: "C5H5N5O" },
  cytosine: { smiles: "Nc1cc[nH]c(=O)n1", formula: "C4H5N3O" },
  thymine: { smiles: "Cc1c[nH]c(=O)[nH]c1=O", formula: "C5H6N2O2" },
  uracil: { smiles: "O=c1cc[nH]c(=O)[nH]1", formula: "C4H4N2O2" },
  hypoxanthine: { smiles: "O=c1[nH]cnc2[nH]cnc12", formula: "C5H4N4O" },
  xanthine: { smiles: "O=c1[nH]c(=O)c2[nH]cnc2[nH]1", formula: "C5H4N4O2" },
  uricacid: { smiles: "O=c1[nH]c(=O)c2[nH]c(=O)[nH]c2[nH]1", formula: "C5H4N4O3" },
  adenosine: { smiles: "Nc1ncnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O", formula: "C10H13N5O4" },
  amp: { smiles: "Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H](O)[C@H]1O", formula: "C10H14N5O7P" },
  adp: { smiles: "Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O", formula: "C10H15N5O10P2" },
  atp: { smiles: "Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O", formula: "C10H16N5O13P3" },
  camp: { smiles: "Nc1ncnc2c1ncn2[C@@H]1O[C@@H]2COP(=O)(O)O[C@H]2[C@H]1O", formula: "C10H12N5O6P" },
  dtmp: { smiles: "Cc1cn([C@H]2C[C@H](O)[C@@H](COP(=O)(O)O)O2)c(=O)[nH]c1=O", formula: "C10H15N2O8P" },
  // ── Métabolites du carrefour énergétique ──
  g1p: { smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)OP(=O)(O)O)O)O)O)O", formula: "C6H13O9P" },
  g6p: { smiles: "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O)(O)O", formula: "C6H13O9P" },
  f6p: { smiles: "C([C@H]1[C@H]([C@@H]([C@](O1)(CO)O)O)O)OP(=O)(O)O", formula: "C6H13O9P" },
  fbp: { smiles: "C([C@H]1[C@H]([C@@H]([C@](O1)(COP(=O)(O)O)O)O)O)OP(=O)(O)O", formula: "C6H14O12P2" },
  dhap: { smiles: "C(C(=O)COP(=O)(O)O)O", formula: "C3H7O6P" },
  g3p: { smiles: "C([C@H](C=O)O)OP(=O)(O)O", formula: "C3H7O6P" },
  bpg13: { smiles: "C([C@H](C(=O)OP(=O)(O)O)O)OP(=O)(O)O", formula: "C3H8O10P2" },
  pg3: { smiles: "C([C@H](C(=O)O)O)OP(=O)(O)O", formula: "C3H7O7P" },
  pg2: { smiles: "C([C@H](C(=O)O)OP(=O)(O)O)O", formula: "C3H7O7P" },
  pep: { smiles: "C=C(OP(=O)(O)O)C(=O)O", formula: "C3H5O6P" },
  pyruvate: { smiles: "CC(=O)C(=O)O", formula: "C3H4O3" },
  lactate: { smiles: "C[C@H](O)C(=O)O", formula: "C3H6O3" },
  citrate: { smiles: "OC(=O)CC(O)(CC(=O)O)C(=O)O", formula: "C6H8O7" },
  isocitrate: { smiles: "OC(=O)C[C@H](C(=O)O)[C@@H](O)C(=O)O", formula: "C6H8O7" },
  akg: { smiles: "OC(=O)CCC(=O)C(=O)O", formula: "C5H6O5" },
  succinate: { smiles: "OC(=O)CCC(=O)O", formula: "C4H6O4" },
  fumarate: { smiles: "OC(=O)/C=C/C(=O)O", formula: "C4H4O4" },
  malate: { smiles: "C([C@@H](C(=O)O)O)C(=O)O", formula: "C4H6O5" },
  oxaloacetate: { smiles: "OC(=O)CC(=O)C(=O)O", formula: "C4H4O5" },
  glycerol3p: { smiles: "C(C(CO)O)OP(=O)(O)O", formula: "C3H9O6P" },
  ribose5p: { smiles: "C([C@@H]1[C@H]([C@H]([C@@H](O1)O)O)O)OP(=O)(O)O", formula: "C5H11O8P" },
  pgluconate6: { smiles: "C([C@H]([C@H]([C@@H]([C@H](C(=O)O)O)O)O)O)OP(=O)(O)O", formula: "C6H13O10P" },
  acetoacetate: { smiles: "CC(=O)CC(=O)O", formula: "C4H6O3" },
  bhb: { smiles: "C[C@@H](O)CC(=O)O", formula: "C4H8O3" },
  acetone: { smiles: "CC(C)=O", formula: "C3H6O" },
  urea: { smiles: "NC(N)=O", formula: "CH4N2O" },
  ornithine: { smiles: "NCCC[C@H](N)C(=O)O", formula: "C5H12N2O2" },
  citrulline: { smiles: "NC(=O)NCCC[C@H](N)C(=O)O", formula: "C6H13N3O3" },
  carbamoylp: { smiles: "NC(=O)OP(=O)(O)O", formula: "CH4NO5P" },
  creatine: { smiles: "CN(CC(=O)O)C(N)=N", formula: "C4H9N3O2" },
  creatinine: { smiles: "CN1CC(=O)N=C1N", formula: "C4H7N3O" },
  // ── Dérivés d'acides aminés ──
  phenylpyruvate: { smiles: "OC(=O)C(=O)Cc1ccccc1", formula: "C9H8O3" },
  homogentisate: { smiles: "OC(=O)Cc1cc(O)ccc1O", formula: "C8H8O4" },
  dopamine: { smiles: "NCCc1ccc(O)c(O)c1", formula: "C8H11NO2" },
  norepinephrine: { smiles: "NC[C@H](O)c1ccc(O)c(O)c1", formula: "C8H11NO3" },
  epinephrine: { smiles: "CNC[C@H](O)c1ccc(O)c(O)c1", formula: "C9H13NO3" },
  serotonin: { smiles: "NCCc1c[nH]c2ccc(O)cc12", formula: "C10H12N2O" },
  melatonin: { smiles: "COc1ccc2[nH]cc(CCNC(C)=O)c2c1", formula: "C13H16N2O2" },
  hiaa5: { smiles: "OC(=O)Cc1c[nH]c2ccc(O)cc12", formula: "C10H9NO3" },
  kynurenine: { smiles: "N[C@@H](CC(=O)c1ccccc1N)C(=O)O", formula: "C10H12N2O3" },
  thyroxine: { smiles: "N[C@@H](Cc1cc(I)c(Oc2cc(I)c(O)c(I)c2)c(I)c1)C(=O)O", formula: "C15H11I4NO4" },
  triiodothyronine: { smiles: "N[C@@H](Cc1cc(I)c(Oc2ccc(O)c(I)c2)c(I)c1)C(=O)O", formula: "C15H12I3NO4" },
};
